// Command genhtmlentities turns the WHATWG's entities.json into the named
// character reference table in package html.
//
// The table is generated rather than typed because it has 2231 entries, and
// generated from the specification's own published file rather than from a copy
// of somebody's parser, so it is the authoritative list by construction. That is
// the same arrangement the font tables had before they moved to forme.
//
// Fetch the input with `make html-entities`, then:
//
//	go run ./cmd/genhtmlentities -in testdata/html/entities.json -out html/entities.go
//
// The output is committed; the input is not.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"
)

type entity struct {
	Codepoints []rune `json:"codepoints"`
	Characters string `json:"characters"`
}

func main() {
	in := flag.String("in", "testdata/html/entities.json", "the WHATWG entities.json")
	out := flag.String("out", "html/entities.go", "the Go file to write")
	flag.Parse()

	raw, err := os.ReadFile(*in)
	if err != nil {
		log.Fatalf("reading %s: %v (run `make html-entities`)", *in, err)
	}
	var table map[string]entity
	if err := json.Unmarshal(raw, &table); err != nil {
		log.Fatalf("parsing %s: %v", *in, err)
	}
	if len(table) == 0 {
		log.Fatalf("%s holds no entities", *in)
	}

	names := make([]string, 0, len(table))
	longest := 0
	for name := range table {
		if !strings.HasPrefix(name, "&") {
			log.Fatalf("the entity %q does not begin with \"&\"", name)
		}
		// The key includes the "&"; the tokenizer matches what follows it.
		trimmed := name[1:]
		names = append(names, trimmed)
		if len(trimmed) > longest {
			longest = len(trimmed)
		}
	}
	sort.Strings(names)

	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by cmd/genhtmlentities. DO NOT EDIT.
//
// Source: https://html.spec.whatwg.org/entities.json — the named character
// references of the HTML standard, %d of them.

package html

// maxEntityNameLen is the longest name in the table, which bounds how far the
// tokenizer looks ahead when matching one.
const maxEntityNameLen = %d

// namedEntities maps a character reference name — everything after the "&",
// including the ";" when the name has one — to the text it stands for.
//
// Names both with and without the trailing semicolon are present, because the
// standard keeps %d historical names that browsers still accept without it.
// Which of the two matched decides whether it was a parse error, so the
// distinction is kept rather than normalised away.
var namedEntities = map[string]string{
`, len(table), longest, countLegacy(table))

	for _, name := range names {
		e := table["&"+name]
		fmt.Fprintf(&b, "\t%q: %q,\n", name, e.Characters)
	}
	b.WriteString("}\n")

	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		log.Fatalf("writing %s: %v", *out, err)
	}
	fmt.Printf("wrote %s: %d entities, longest name %d bytes\n", *out, len(table), longest)
}

func countLegacy(table map[string]entity) int {
	n := 0
	for name := range table {
		if !strings.HasSuffix(name, ";") {
			n++
		}
	}
	return n
}
