package pdf0

import (
	"encoding/xml"
	"os"
	"path/filepath"
	"testing"
)

// This test keeps the committed EN 16931 code-list tables (en16931_codelists.go,
// generated by testdata/en16931-codelists/gen.py) faithful to the official
// CEN/TC 434 genericode bundle by re-deriving each set from the genericode and
// asserting the committed maps match. It skips when the bundle is absent (run
// `make en16931-codelists`), so the tables remain the runtime source and the
// genericode is only the verification oracle.

// gcCodes reads the Code column of a genericode (.gc) file.
func gcCodes(t *testing.T, path string) map[string]bool {
	data, err := os.ReadFile(path)
	if err != nil {
		t.Skipf("genericode %s not present: %v", filepath.Base(path), err)
	}
	var cl struct {
		Rows []struct {
			Values []struct {
				ColumnRef   string `xml:"ColumnRef,attr"`
				SimpleValue string `xml:"SimpleValue"`
			} `xml:"Value"`
		} `xml:"SimpleCodeList>Row"`
	}
	if err := xml.Unmarshal(data, &cl); err != nil {
		t.Fatalf("%s: %v", path, err)
	}
	out := map[string]bool{}
	for _, r := range cl.Rows {
		for _, v := range r.Values {
			if v.ColumnRef == "Code" {
				out[v.SimpleValue] = true
			}
		}
	}
	return out
}

func TestEN16931CodeListsFaithful(t *testing.T) {
	dir := filepath.Join("testdata", "en16931-codelists", "genericode")
	if _, err := os.Stat(dir); err != nil {
		t.Skip("EN 16931 genericode bundle not present; run `make en16931-codelists`")
	}
	cases := []struct {
		name string
		have map[string]bool
		file string
	}{
		{"en16931Currencies", en16931Currencies, "Currency.gc"},
		{"en16931Countries", en16931Countries, "Country.gc"},
		{"en16931TypeCodes", en16931TypeCodes, "1001.gc"},
		{"en16931VATCategories", en16931VATCategories, "5305.gc"},
		{"en16931PaymentMeans", en16931PaymentMeans, "Payment.gc"},
		{"en16931AllowanceReasons", en16931AllowanceReasons, "Allowance.gc"},
		{"en16931ChargeReasons", en16931ChargeReasons, "Charge.gc"},
		{"en16931VATEX", en16931VATEX, "VATEX.gc"},
		{"en16931EAS", en16931EAS, "EAS.gc"},
		{"en16931ICD", en16931ICD, "ICD.gc"},
		{"en16931MIME", en16931MIME, "MIME.gc"},
		{"en16931RefTypeCodes", en16931RefTypeCodes, "1153.gc"},
		{"en16931ItemClassCodes", en16931ItemClassCodes, "Item.gc"},
		{"en16931Units", en16931Units, "Unit.gc"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			want := gcCodes(t, filepath.Join(dir, tc.file))
			if len(want) == 0 {
				t.Fatalf("no codes extracted from %s", tc.file)
			}
			for c := range want {
				if !tc.have[c] {
					t.Errorf("%s is missing %q, which the genericode lists", tc.name, c)
				}
			}
			for c := range tc.have {
				if !want[c] {
					t.Errorf("%s contains %q, which the genericode does not list", tc.name, c)
				}
			}
		})
	}
}
