// Command gencolors turns the CSS Color 4 specification's named colour table
// into the table in package style.
//
// The source is the specification's own Bikeshed document rather than the CSS
// parsing tests, and the distinction is deliberate. The tests hold the same 148
// mappings, and generating the table from them would make the oracle that checks
// it circular — it would prove only that a file round-trips through a generator.
// Taking the specification instead leaves the tests a real check on this
// transcription.
//
// Fetch the input with `make css-colors`, then:
//
//	go run ./cmd/gencolors -in testdata/css-color-4.bs -out style/colors.go
//
// The output is committed; the input is not.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// The specification writes each colour as one table row:
//
//	<th scope=row><dfn>aliceblue</dfn><td>#f0f8ff<td>240 248 255
//
// Both the hexadecimal and the decimal forms are captured so the generator can
// check them against each other — a row where they disagree is a mistake in the
// specification or in this pattern, and either is worth stopping for.
var row = regexp.MustCompile(
	`<dfn>([a-z]+)</dfn><td>#([0-9a-fA-F]{6})<td>\s*(\d+)\s+(\d+)\s+(\d+)`)

func main() {
	in := flag.String("in", "testdata/css-color-4.bs", "the CSS Color 4 Bikeshed source")
	out := flag.String("out", "style/colors.go", "the Go file to write")
	flag.Parse()

	raw, err := os.ReadFile(*in)
	if err != nil {
		log.Fatalf("reading %s: %v (run `make css-colors`)", *in, err)
	}

	matches := row.FindAllStringSubmatch(string(raw), -1)
	if len(matches) == 0 {
		log.Fatalf("%s holds no named-colour rows; the specification's table has changed shape", *in)
	}

	type colour struct {
		name    string
		r, g, b uint8
	}
	seen := map[string]bool{}
	var colours []colour

	for _, m := range matches {
		name := m[1]
		if seen[name] {
			log.Fatalf("the colour %q appears twice", name)
		}
		seen[name] = true

		hex, err := strconv.ParseUint(m[2], 16, 32)
		if err != nil {
			log.Fatalf("%s: %v", name, err)
		}
		hr, hg, hb := uint8(hex>>16), uint8(hex>>8), uint8(hex)

		dr, dg, db := atoi(name, m[3]), atoi(name, m[4]), atoi(name, m[5])
		// The two forms are written independently in the specification, so a
		// disagreement means one of them was read wrongly.
		if hr != dr || hg != dg || hb != db {
			log.Fatalf("%s: #%02x%02x%02x and %d %d %d disagree", name, hr, hg, hb, dr, dg, db)
		}
		colours = append(colours, colour{name, hr, hg, hb})
	}

	sort.Slice(colours, func(i, j int) bool { return colours[i].name < colours[j].name })

	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by cmd/gencolors. DO NOT EDIT.
//
// Source: the named colour table of CSS Color Module Level 4,
// https://drafts.csswg.org/css-color-4/#named-colors — %d colours.

package style

// namedColors maps a CSS colour keyword to its sRGB value, on the 0-255 scale.
// Every one is fully
// opaque; "transparent" is not here, because it is the one keyword whose alpha
// is not 1 and it is handled where the alpha is.
var namedColors = map[string]RGBA{
`, len(colours))

	for _, c := range colours {
		fmt.Fprintf(&b, "\t%q: {%d, %d, %d, 1},\n", c.name, c.r, c.g, c.b)
	}
	b.WriteString("}\n")

	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		log.Fatalf("writing %s: %v", *out, err)
	}
	fmt.Printf("wrote %s: %d named colours\n", *out, len(colours))
}

func atoi(name, s string) uint8 {
	v, err := strconv.Atoi(s)
	if err != nil || v < 0 || v > 255 {
		log.Fatalf("%s: %q is not a colour component", name, s)
	}
	return uint8(v)
}
