# Shapes the corpus with HarfBuzz and writes what it produced.
#
# The output is checked in and is what fonts/harfbuzz_test.go compares this
# package against. Regenerating it needs Python, uharfbuzz and the bundled font;
# running the test needs none of them, which is the point — an oracle that only
# a machine with the right Python on it can consult is an oracle nobody consults.
#
#   make hbshaping
#
# The header records what produced the file. The font checksum is the important
# one: these are answers about a particular font, and swapping the bundled font
# without regenerating would leave the test asserting yesterday's answers about
# today's glyphs. The Go test refuses to run if it does not match.
#
# HB_BUFFER_FLAG_REMOVE_DEFAULT_IGNORABLES is set because that is the policy
# this package has: a character nothing is drawn for is removed rather than
# mapped to an invisible glyph. HarfBuzz offers both; this is the comparable one.
import hashlib
import sys

import uharfbuzz as hb

font_path, corpus_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3]

data = open(font_path, "rb").read()
blob = hb.Blob(data)
face = hb.Face(blob)

lines = [l.rstrip("\n") for l in open(corpus_path, encoding="utf-8")]
lines = [l for l in lines if l != ""]

out = []
for s in lines:
    font = hb.Font(face)
    buf = hb.Buffer()
    buf.add_str(s)
    buf.guess_segment_properties()
    buf.flags = hb.BufferFlags.REMOVE_DEFAULT_IGNORABLES
    hb.shape(font, buf, None)
    fields = []
    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        # dx and dy are zero for all but the marks, and leaving them off where
        # they are zero halves the file.
        if pos.x_offset or pos.y_offset:
            fields.append(f"{info.codepoint},{pos.x_advance},{pos.x_offset},{pos.y_offset}")
        else:
            fields.append(f"{info.codepoint},{pos.x_advance}")
    out.append(" ".join(fields))

with open(out_path, "w", encoding="utf-8") as w:
    w.write("# Generated by testdata/harfbuzz/shape.py. DO NOT EDIT.\n")
    w.write("#\n")
    w.write("# What HarfBuzz produces for each line of corpus.txt, in order: the\n")
    w.write("# glyph index and advance of each glyph, and its offset where that is\n")
    w.write("# not zero. Advances and offsets are in font units.\n")
    w.write(f"# font-sha256 {hashlib.sha256(data).hexdigest()}\n")
    w.write(f"# harfbuzz {hb.version_string()}\n")
    w.write(f"# uharfbuzz {hb.__version__}\n")
    w.write(f"# cases {len(out)}\n")
    for line in out:
        w.write(line + "\n")

print(f"{len(out)} cases -> {out_path}", file=sys.stderr)
