// Command genstdfonts generates the metrics of the fourteen standard PDF fonts
// from Adobe's own AFM files.
//
// The metrics are data, not something to be typed from memory: a width that is
// wrong by a few units lays text out wrongly in a way nothing in this
// repository would notice, because there is no font program to check it
// against. So they are derived from the source Adobe published, and this
// command is how that derivation is repeated.
//
// The AFM files are the Adobe Core 14 set, freely redistributable and shipped
// with a good deal of software (Ghostscript, matplotlib, poppler-data). Point
// this at a directory holding them:
//
//	go run ./cmd/genstdfonts <dir> > fonts/standard14.go
package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// The fourteen, by the /BaseFont name a PDF uses.
var wanted = []string{
	"Courier", "Courier-Bold", "Courier-Oblique", "Courier-BoldOblique",
	"Helvetica", "Helvetica-Bold", "Helvetica-Oblique", "Helvetica-BoldOblique",
	"Times-Roman", "Times-Bold", "Times-Italic", "Times-BoldItalic",
	"Symbol", "ZapfDingbats",
}

type metrics struct {
	widths     map[string]int // glyph name -> advance width
	ascent     int
	descent    int
	capHeight  int
	italic     float64
	fixedPitch bool
	bbox       [4]int
	flags      int
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: genstdfonts <afm-directory>")
		os.Exit(2)
	}
	all := map[string]*metrics{}
	for _, name := range wanted {
		m, err := parseAFM(filepath.Join(os.Args[1], name+".afm"))
		if err != nil {
			fmt.Fprintf(os.Stderr, "%s: %v\n", name, err)
			os.Exit(1)
		}
		all[name] = m
	}
	emit(all)
}

func parseAFM(path string) (*metrics, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	m := &metrics{widths: map[string]int{}}
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	for sc.Scan() {
		line := sc.Text()
		switch {
		case strings.HasPrefix(line, "C "):
			var width int
			var glyph string
			for _, field := range strings.Split(line, ";") {
				field = strings.TrimSpace(field)
				switch {
				case strings.HasPrefix(field, "WX "):
					width, _ = strconv.Atoi(strings.TrimSpace(field[3:]))
				case strings.HasPrefix(field, "N "):
					glyph = strings.TrimSpace(field[2:])
				}
			}
			if glyph != "" {
				m.widths[glyph] = width
			}
		case strings.HasPrefix(line, "Ascender "):
			m.ascent, _ = strconv.Atoi(strings.TrimSpace(line[9:]))
		case strings.HasPrefix(line, "Descender "):
			m.descent, _ = strconv.Atoi(strings.TrimSpace(line[10:]))
		case strings.HasPrefix(line, "CapHeight "):
			m.capHeight, _ = strconv.Atoi(strings.TrimSpace(line[10:]))
		case strings.HasPrefix(line, "ItalicAngle "):
			m.italic, _ = strconv.ParseFloat(strings.TrimSpace(line[12:]), 64)
		case strings.HasPrefix(line, "IsFixedPitch "):
			m.fixedPitch = strings.TrimSpace(line[13:]) == "true"
		case strings.HasPrefix(line, "FontBBox "):
			fields := strings.Fields(line[9:])
			for i := 0; i < 4 && i < len(fields); i++ {
				m.bbox[i], _ = strconv.Atoi(fields[i])
			}
		}
	}
	if len(m.widths) == 0 {
		return nil, fmt.Errorf("no character metrics found")
	}
	return m, sc.Err()
}

func emit(all map[string]*metrics) {
	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()

	fmt.Fprint(w, `// Code generated by cmd/genstdfonts from Adobe's Core 14 AFM files. DO NOT EDIT.

// Derived from the Adobe Core 14 AFM files. Only the advance widths and the
// font-wide metrics below are taken from them; no outline, no font program and
// no character shape is reproduced here, and no AFM file is redistributed.
//
// The Adobe notices, retained as the licence requires:
//
//	Copyright (c) 1985, 1987, 1988, 1989, 1997 Adobe Systems Incorporated.
//	All Rights Reserved. ITC Zapf Dingbats is a registered trademark of
//	International Typeface Corporation.
//	Copyright (c) 1985, 1987, 1989, 1990, 1993, 1997 Adobe Systems Incorporated.
//	All Rights Reserved. Times is a trademark of Linotype-Hell AG and/or its
//	subsidiaries.
//	Copyright (c) 1985, 1987, 1989, 1990, 1997 Adobe Systems Incorporated.
//	All Rights Reserved. Helvetica is a trademark of Linotype-Hell AG and/or
//	its subsidiaries.
//	Copyright (c) 1985, 1987, 1989, 1990, 1997 Adobe Systems Incorporated.
//	All rights reserved.
//	Copyright (c) 1989, 1990, 1991, 1992, 1993, 1997 Adobe Systems Incorporated.
//	All Rights Reserved.
//	Copyright (c) 1989, 1990, 1991, 1993, 1997 Adobe Systems Incorporated.
//	All Rights Reserved.
//
// The licence, reproduced unmodified as it requires:
//
//	This file and the 14 PostScript(R) AFM files it accompanies may be used,
//	copied, and distributed for any purpose and without charge, with or without
//	modification, provided that all copyright notices are retained; that the AFM
//	files are not distributed without this file; that all modifications to this
//	file or any of the AFM files are prominently noted in the modified file(s);
//	and that this paragraph is not modified. Adobe Systems has no responsibility
//	or obligation to support the use of the AFM files.
//
// Modification noted, as the licence requires: the AFM files were not modified.
// This file is a derived work containing the advance width of each glyph by
// name, together with the ascent, descent, cap height, italic angle, fixed-pitch
// flag and bounding box of each face. Everything else in an AFM — kerning pairs,
// composites, character codes, the character-name ordering — was dropped.

package fonts

// The metrics of the fourteen standard fonts, as Adobe published them.
//
// A PDF reader is required to have these faces, so a document may name one and
// embed nothing. That makes them the only fonts whose metrics this package
// cannot read out of a program, and the reason the numbers are here: laying out
// text in one of them needs its widths whether or not anything is embedded.
//
// The names — Helvetica, Times, Courier, Symbol, ZapfDingbats — are the
// identifiers ISO 32000-2 9.6.2.2 gives these fourteen, and are what goes in a
// /BaseFont entry. Several are trademarks of their respective owners, noted
// above; naming one in a PDF is how the format says "the face the reader
// already has", not a claim to distribute it. Nothing here reproduces a
// typeface.
//
// They are generated rather than written, because a width wrong by a few units
// mis-sets a line in a way nothing here would catch — there is no program to
// check it against.

// stdMetrics is one standard face.
type stdMetrics struct {
	widths     map[string]int
	ascent     int
	descent    int
	capHeight  int
	italic     float64
	fixedPitch bool
	bbox       [4]int
}

`)
	names := make([]string, 0, len(all))
	for n := range all {
		names = append(names, n)
	}
	sort.Strings(names)

	fmt.Fprintln(w, "var standard14 = map[string]*stdMetrics{")
	for _, n := range names {
		m := all[n]
		fmt.Fprintf(w, "\t%q: {\n", n)
		fmt.Fprintf(w, "\t\tascent: %d, descent: %d, capHeight: %d, italic: %v, fixedPitch: %v,\n",
			m.ascent, m.descent, m.capHeight, m.italic, m.fixedPitch)
		fmt.Fprintf(w, "\t\tbbox: [4]int{%d, %d, %d, %d},\n", m.bbox[0], m.bbox[1], m.bbox[2], m.bbox[3])
		fmt.Fprintln(w, "\t\twidths: map[string]int{")
		glyphs := make([]string, 0, len(m.widths))
		for g := range m.widths {
			glyphs = append(glyphs, g)
		}
		sort.Strings(glyphs)
		for i, g := range glyphs {
			if i%4 == 0 {
				fmt.Fprint(w, "\t\t\t")
			}
			fmt.Fprintf(w, "%q: %d,", g, m.widths[g])
			if i%4 == 3 || i == len(glyphs)-1 {
				fmt.Fprintln(w)
			} else {
				fmt.Fprint(w, " ")
			}
		}
		fmt.Fprintln(w, "\t\t},")
		fmt.Fprintln(w, "\t},")
	}
	fmt.Fprintln(w, "}")
}
