// Code generated by cmd/genignorable from Unicode's DerivedCoreProperties.txt.
// DO NOT EDIT.

package fonts

// Default_Ignorable_Code_Point. Unicode 17.0.0.
//
// 17 ranges. A character in one of them is an instruction rather than a letter,
// and a renderer that can do nothing better than show a glyph for it should show
// nothing at all. Which of them this package acts on is decided in
// ignorable.go, not here: this table is Unicode's statement, not a policy.
var defaultIgnorableRanges = [...]struct{ lo, hi rune }{
	{0x00AD, 0x00AD},
	{0x034F, 0x034F},
	{0x061C, 0x061C},
	{0x115F, 0x1160},
	{0x17B4, 0x17B5},
	{0x180B, 0x180F},
	{0x200B, 0x200F},
	{0x202A, 0x202E},
	{0x2060, 0x206F},
	{0x3164, 0x3164},
	{0xFE00, 0xFE0F},
	{0xFEFF, 0xFEFF},
	{0xFFA0, 0xFFA0},
	{0xFFF0, 0xFFF8},
	{0x1BCA0, 0x1BCA3},
	{0x1D173, 0x1D17A},
	{0xE0000, 0xE0FFF},
}
