// Code generated by cmd/genmatra from UnicodeData.txt. DO NOT EDIT.

package fonts

// The vowel signs written as one character and drawn as two or three marks.
//
// A split sign cannot be placed while it is one character: its parts go to
// different places, one before the letter and one after. So the reordering
// takes it apart first, and then places the parts as it places any other sign.
// That is the shaping model's own second step, and these 17 characters are what
// it applies to.
//
// They are exactly the characters of the nine Indic blocks whose canonical
// decomposition is a sequence of combining marks. A character that decomposes
// into a *letter* and a mark is a letter written with a dot, not a split sign,
// and is left alone.
//
// The entries are sorted, so a lookup can binary-search.

// indicSplitMatra is one sign and the marks it is drawn as.
type indicSplitMatra struct {
	r     rune
	parts [3]rune // a two-part sign has a zero third
}

var indicSplitMatras = [...]indicSplitMatra{
	{0x09CB, [3]rune{0x09C7, 0x09BE, 0}},
	{0x09CC, [3]rune{0x09C7, 0x09D7, 0}},
	{0x0B48, [3]rune{0x0B47, 0x0B56, 0}},
	{0x0B4B, [3]rune{0x0B47, 0x0B3E, 0}},
	{0x0B4C, [3]rune{0x0B47, 0x0B57, 0}},
	{0x0BCA, [3]rune{0x0BC6, 0x0BBE, 0}},
	{0x0BCB, [3]rune{0x0BC7, 0x0BBE, 0}},
	{0x0BCC, [3]rune{0x0BC6, 0x0BD7, 0}},
	{0x0C48, [3]rune{0x0C46, 0x0C56, 0}},
	{0x0CC0, [3]rune{0x0CBF, 0x0CD5, 0}},
	{0x0CC7, [3]rune{0x0CC6, 0x0CD5, 0}},
	{0x0CC8, [3]rune{0x0CC6, 0x0CD6, 0}},
	{0x0CCA, [3]rune{0x0CC6, 0x0CC2, 0}},
	{0x0CCB, [3]rune{0x0CC6, 0x0CC2, 0x0CD5}},
	{0x0D4A, [3]rune{0x0D46, 0x0D3E, 0}},
	{0x0D4B, [3]rune{0x0D47, 0x0D3E, 0}},
	{0x0D4C, [3]rune{0x0D46, 0x0D57, 0}},
}
