// Code generated by cmd/genscripts from Unicode's Scripts.txt and
// PropertyValueAliases.txt. DO NOT EDIT.

package fonts

// Unicode scripts, and the OpenType script tags each one selects. Unicode 17.0.0.
//
// A font states its layout rules per script, so shaping a run has to know which
// script the run is in — that is Unicode's Script property, and these 984 ranges
// are it. A character no range names is of unknown script, which selects the
// default tag, as do Common and Inherited: a digit, a space and a combining
// accent are not text in a script of their own and take the script of what they
// are written among.
//
// A script's tags are in the order a shaper tries them, which matters only for
// the Indic scripts, where the second-generation tag comes first.

type scriptRange struct {
	lo, hi rune
	script uint16
}

// The three scripts that decide nothing, at fixed indices so the resolver can
// name them.
const (
	scriptCommon    = 0
	scriptInherited = 1
	scriptUnknown   = 2
)

// scriptOpenTypeTags gives the tags each script selects, indexed as
// scriptRanges indexes scripts. A nil entry selects no tag of its own.
var scriptOpenTypeTags = [...][]string{
	0:   nil,              // Common
	1:   nil,              // Inherited
	2:   nil,              // Unknown
	3:   {"adlm"},         // Adlam
	4:   {"ahom"},         // Ahom
	5:   {"hluw"},         // Anatolian_Hieroglyphs
	6:   {"arab"},         // Arabic
	7:   {"armn"},         // Armenian
	8:   {"avst"},         // Avestan
	9:   {"bali"},         // Balinese
	10:  {"bamu"},         // Bamum
	11:  {"bass"},         // Bassa_Vah
	12:  {"batk"},         // Batak
	13:  {"bng2", "beng"}, // Bengali
	14:  {"berf"},         // Beria_Erfe
	15:  {"bhks"},         // Bhaiksuki
	16:  {"bopo"},         // Bopomofo
	17:  {"brah"},         // Brahmi
	18:  {"brai"},         // Braille
	19:  {"bugi"},         // Buginese
	20:  {"buhd"},         // Buhid
	21:  {"cans"},         // Canadian_Aboriginal
	22:  {"cari"},         // Carian
	23:  {"aghb"},         // Caucasian_Albanian
	24:  {"cakm"},         // Chakma
	25:  {"cham"},         // Cham
	26:  {"cher"},         // Cherokee
	27:  {"chrs"},         // Chorasmian
	28:  {"copt"},         // Coptic
	29:  {"xsux"},         // Cuneiform
	30:  {"cprt"},         // Cypriot
	31:  {"cpmn"},         // Cypro_Minoan
	32:  {"cyrl"},         // Cyrillic
	33:  {"dsrt"},         // Deseret
	34:  {"dev2", "deva"}, // Devanagari
	35:  {"diak"},         // Dives_Akuru
	36:  {"dogr"},         // Dogra
	37:  {"dupl"},         // Duployan
	38:  {"egyp"},         // Egyptian_Hieroglyphs
	39:  {"elba"},         // Elbasan
	40:  {"elym"},         // Elymaic
	41:  {"ethi"},         // Ethiopic
	42:  {"gara"},         // Garay
	43:  {"geor"},         // Georgian
	44:  {"glag"},         // Glagolitic
	45:  {"goth"},         // Gothic
	46:  {"gran"},         // Grantha
	47:  {"grek"},         // Greek
	48:  {"gjr2", "gujr"}, // Gujarati
	49:  {"gong"},         // Gunjala_Gondi
	50:  {"gur2", "guru"}, // Gurmukhi
	51:  {"gukh"},         // Gurung_Khema
	52:  {"hani"},         // Han
	53:  {"hang"},         // Hangul
	54:  {"rohg"},         // Hanifi_Rohingya
	55:  {"hano"},         // Hanunoo
	56:  {"hatr"},         // Hatran
	57:  {"hebr"},         // Hebrew
	58:  {"kana"},         // Hiragana
	59:  {"armi"},         // Imperial_Aramaic
	60:  {"phli"},         // Inscriptional_Pahlavi
	61:  {"prti"},         // Inscriptional_Parthian
	62:  {"java"},         // Javanese
	63:  {"kthi"},         // Kaithi
	64:  {"knd2", "knda"}, // Kannada
	65:  {"kana"},         // Katakana
	66:  {"kawi"},         // Kawi
	67:  {"kali"},         // Kayah_Li
	68:  {"khar"},         // Kharoshthi
	69:  {"kits"},         // Khitan_Small_Script
	70:  {"khmr"},         // Khmer
	71:  {"khoj"},         // Khojki
	72:  {"sind"},         // Khudawadi
	73:  {"krai"},         // Kirat_Rai
	74:  {"lao "},         // Lao
	75:  {"latn"},         // Latin
	76:  {"lepc"},         // Lepcha
	77:  {"limb"},         // Limbu
	78:  {"lina"},         // Linear_A
	79:  {"linb"},         // Linear_B
	80:  {"lisu"},         // Lisu
	81:  {"lyci"},         // Lycian
	82:  {"lydi"},         // Lydian
	83:  {"mahj"},         // Mahajani
	84:  {"maka"},         // Makasar
	85:  {"mlm2", "mlym"}, // Malayalam
	86:  {"mand"},         // Mandaic
	87:  {"mani"},         // Manichaean
	88:  {"marc"},         // Marchen
	89:  {"gonm"},         // Masaram_Gondi
	90:  {"medf"},         // Medefaidrin
	91:  {"mtei"},         // Meetei_Mayek
	92:  {"mend"},         // Mende_Kikakui
	93:  {"merc"},         // Meroitic_Cursive
	94:  {"mero"},         // Meroitic_Hieroglyphs
	95:  {"plrd"},         // Miao
	96:  {"modi"},         // Modi
	97:  {"mong"},         // Mongolian
	98:  {"mroo"},         // Mro
	99:  {"mult"},         // Multani
	100: {"mym2", "mymr"}, // Myanmar
	101: {"nbat"},         // Nabataean
	102: {"nagm"},         // Nag_Mundari
	103: {"nand"},         // Nandinagari
	104: {"talu"},         // New_Tai_Lue
	105: {"newa"},         // Newa
	106: {"nko "},         // Nko
	107: {"nshu"},         // Nushu
	108: {"hmnp"},         // Nyiakeng_Puachue_Hmong
	109: {"ogam"},         // Ogham
	110: {"olck"},         // Ol_Chiki
	111: {"onao"},         // Ol_Onal
	112: {"hung"},         // Old_Hungarian
	113: {"ital"},         // Old_Italic
	114: {"narb"},         // Old_North_Arabian
	115: {"perm"},         // Old_Permic
	116: {"xpeo"},         // Old_Persian
	117: {"sogo"},         // Old_Sogdian
	118: {"sarb"},         // Old_South_Arabian
	119: {"orkh"},         // Old_Turkic
	120: {"ougr"},         // Old_Uyghur
	121: {"ory2", "orya"}, // Oriya
	122: {"osge"},         // Osage
	123: {"osma"},         // Osmanya
	124: {"hmng"},         // Pahawh_Hmong
	125: {"palm"},         // Palmyrene
	126: {"pauc"},         // Pau_Cin_Hau
	127: {"phag"},         // Phags_Pa
	128: {"phnx"},         // Phoenician
	129: {"phlp"},         // Psalter_Pahlavi
	130: {"rjng"},         // Rejang
	131: {"runr"},         // Runic
	132: {"samr"},         // Samaritan
	133: {"saur"},         // Saurashtra
	134: {"shrd"},         // Sharada
	135: {"shaw"},         // Shavian
	136: {"sidd"},         // Siddham
	137: {"sidt"},         // Sidetic
	138: {"sgnw"},         // SignWriting
	139: {"sinh"},         // Sinhala
	140: {"sogd"},         // Sogdian
	141: {"sora"},         // Sora_Sompeng
	142: {"soyo"},         // Soyombo
	143: {"sund"},         // Sundanese
	144: {"sunu"},         // Sunuwar
	145: {"sylo"},         // Syloti_Nagri
	146: {"syrc"},         // Syriac
	147: {"tglg"},         // Tagalog
	148: {"tagb"},         // Tagbanwa
	149: {"tale"},         // Tai_Le
	150: {"lana"},         // Tai_Tham
	151: {"tavt"},         // Tai_Viet
	152: {"tayo"},         // Tai_Yo
	153: {"takr"},         // Takri
	154: {"tml2", "taml"}, // Tamil
	155: {"tnsa"},         // Tangsa
	156: {"tang"},         // Tangut
	157: {"tel2", "telu"}, // Telugu
	158: {"thaa"},         // Thaana
	159: {"thai"},         // Thai
	160: {"tibt"},         // Tibetan
	161: {"tfng"},         // Tifinagh
	162: {"tirh"},         // Tirhuta
	163: {"todr"},         // Todhri
	164: {"tols"},         // Tolong_Siki
	165: {"toto"},         // Toto
	166: {"tutg"},         // Tulu_Tigalari
	167: {"ugar"},         // Ugaritic
	168: {"vai "},         // Vai
	169: {"vith"},         // Vithkuqi
	170: {"wcho"},         // Wancho
	171: {"wara"},         // Warang_Citi
	172: {"yezi"},         // Yezidi
	173: {"yi  "},         // Yi
	174: {"zanb"},         // Zanabazar_Square
}

// scriptRanges maps a character to its script, sorted by code point.
var scriptRanges = [...]scriptRange{
	{0x0000, 0x0040, 0},     // Common
	{0x0041, 0x005A, 75},    // Latin
	{0x005B, 0x0060, 0},     // Common
	{0x0061, 0x007A, 75},    // Latin
	{0x007B, 0x00A9, 0},     // Common
	{0x00AA, 0x00AA, 75},    // Latin
	{0x00AB, 0x00B9, 0},     // Common
	{0x00BA, 0x00BA, 75},    // Latin
	{0x00BB, 0x00BF, 0},     // Common
	{0x00C0, 0x00D6, 75},    // Latin
	{0x00D7, 0x00D7, 0},     // Common
	{0x00D8, 0x00F6, 75},    // Latin
	{0x00F7, 0x00F7, 0},     // Common
	{0x00F8, 0x02B8, 75},    // Latin
	{0x02B9, 0x02DF, 0},     // Common
	{0x02E0, 0x02E4, 75},    // Latin
	{0x02E5, 0x02E9, 0},     // Common
	{0x02EA, 0x02EB, 16},    // Bopomofo
	{0x02EC, 0x02FF, 0},     // Common
	{0x0300, 0x036F, 1},     // Inherited
	{0x0370, 0x0373, 47},    // Greek
	{0x0374, 0x0374, 0},     // Common
	{0x0375, 0x0377, 47},    // Greek
	{0x037A, 0x037D, 47},    // Greek
	{0x037E, 0x037E, 0},     // Common
	{0x037F, 0x037F, 47},    // Greek
	{0x0384, 0x0384, 47},    // Greek
	{0x0385, 0x0385, 0},     // Common
	{0x0386, 0x0386, 47},    // Greek
	{0x0387, 0x0387, 0},     // Common
	{0x0388, 0x038A, 47},    // Greek
	{0x038C, 0x038C, 47},    // Greek
	{0x038E, 0x03A1, 47},    // Greek
	{0x03A3, 0x03E1, 47},    // Greek
	{0x03E2, 0x03EF, 28},    // Coptic
	{0x03F0, 0x03FF, 47},    // Greek
	{0x0400, 0x0484, 32},    // Cyrillic
	{0x0485, 0x0486, 1},     // Inherited
	{0x0487, 0x052F, 32},    // Cyrillic
	{0x0531, 0x0556, 7},     // Armenian
	{0x0559, 0x058A, 7},     // Armenian
	{0x058D, 0x058F, 7},     // Armenian
	{0x0591, 0x05C7, 57},    // Hebrew
	{0x05D0, 0x05EA, 57},    // Hebrew
	{0x05EF, 0x05F4, 57},    // Hebrew
	{0x0600, 0x0604, 6},     // Arabic
	{0x0605, 0x0605, 0},     // Common
	{0x0606, 0x060B, 6},     // Arabic
	{0x060C, 0x060C, 0},     // Common
	{0x060D, 0x061A, 6},     // Arabic
	{0x061B, 0x061B, 0},     // Common
	{0x061C, 0x061E, 6},     // Arabic
	{0x061F, 0x061F, 0},     // Common
	{0x0620, 0x063F, 6},     // Arabic
	{0x0640, 0x0640, 0},     // Common
	{0x0641, 0x064A, 6},     // Arabic
	{0x064B, 0x0655, 1},     // Inherited
	{0x0656, 0x066F, 6},     // Arabic
	{0x0670, 0x0670, 1},     // Inherited
	{0x0671, 0x06DC, 6},     // Arabic
	{0x06DD, 0x06DD, 0},     // Common
	{0x06DE, 0x06FF, 6},     // Arabic
	{0x0700, 0x070D, 146},   // Syriac
	{0x070F, 0x074A, 146},   // Syriac
	{0x074D, 0x074F, 146},   // Syriac
	{0x0750, 0x077F, 6},     // Arabic
	{0x0780, 0x07B1, 158},   // Thaana
	{0x07C0, 0x07FA, 106},   // Nko
	{0x07FD, 0x07FF, 106},   // Nko
	{0x0800, 0x082D, 132},   // Samaritan
	{0x0830, 0x083E, 132},   // Samaritan
	{0x0840, 0x085B, 86},    // Mandaic
	{0x085E, 0x085E, 86},    // Mandaic
	{0x0860, 0x086A, 146},   // Syriac
	{0x0870, 0x0891, 6},     // Arabic
	{0x0897, 0x08E1, 6},     // Arabic
	{0x08E2, 0x08E2, 0},     // Common
	{0x08E3, 0x08FF, 6},     // Arabic
	{0x0900, 0x0950, 34},    // Devanagari
	{0x0951, 0x0954, 1},     // Inherited
	{0x0955, 0x0963, 34},    // Devanagari
	{0x0964, 0x0965, 0},     // Common
	{0x0966, 0x097F, 34},    // Devanagari
	{0x0980, 0x0983, 13},    // Bengali
	{0x0985, 0x098C, 13},    // Bengali
	{0x098F, 0x0990, 13},    // Bengali
	{0x0993, 0x09A8, 13},    // Bengali
	{0x09AA, 0x09B0, 13},    // Bengali
	{0x09B2, 0x09B2, 13},    // Bengali
	{0x09B6, 0x09B9, 13},    // Bengali
	{0x09BC, 0x09C4, 13},    // Bengali
	{0x09C7, 0x09C8, 13},    // Bengali
	{0x09CB, 0x09CE, 13},    // Bengali
	{0x09D7, 0x09D7, 13},    // Bengali
	{0x09DC, 0x09DD, 13},    // Bengali
	{0x09DF, 0x09E3, 13},    // Bengali
	{0x09E6, 0x09FE, 13},    // Bengali
	{0x0A01, 0x0A03, 50},    // Gurmukhi
	{0x0A05, 0x0A0A, 50},    // Gurmukhi
	{0x0A0F, 0x0A10, 50},    // Gurmukhi
	{0x0A13, 0x0A28, 50},    // Gurmukhi
	{0x0A2A, 0x0A30, 50},    // Gurmukhi
	{0x0A32, 0x0A33, 50},    // Gurmukhi
	{0x0A35, 0x0A36, 50},    // Gurmukhi
	{0x0A38, 0x0A39, 50},    // Gurmukhi
	{0x0A3C, 0x0A3C, 50},    // Gurmukhi
	{0x0A3E, 0x0A42, 50},    // Gurmukhi
	{0x0A47, 0x0A48, 50},    // Gurmukhi
	{0x0A4B, 0x0A4D, 50},    // Gurmukhi
	{0x0A51, 0x0A51, 50},    // Gurmukhi
	{0x0A59, 0x0A5C, 50},    // Gurmukhi
	{0x0A5E, 0x0A5E, 50},    // Gurmukhi
	{0x0A66, 0x0A76, 50},    // Gurmukhi
	{0x0A81, 0x0A83, 48},    // Gujarati
	{0x0A85, 0x0A8D, 48},    // Gujarati
	{0x0A8F, 0x0A91, 48},    // Gujarati
	{0x0A93, 0x0AA8, 48},    // Gujarati
	{0x0AAA, 0x0AB0, 48},    // Gujarati
	{0x0AB2, 0x0AB3, 48},    // Gujarati
	{0x0AB5, 0x0AB9, 48},    // Gujarati
	{0x0ABC, 0x0AC5, 48},    // Gujarati
	{0x0AC7, 0x0AC9, 48},    // Gujarati
	{0x0ACB, 0x0ACD, 48},    // Gujarati
	{0x0AD0, 0x0AD0, 48},    // Gujarati
	{0x0AE0, 0x0AE3, 48},    // Gujarati
	{0x0AE6, 0x0AF1, 48},    // Gujarati
	{0x0AF9, 0x0AFF, 48},    // Gujarati
	{0x0B01, 0x0B03, 121},   // Oriya
	{0x0B05, 0x0B0C, 121},   // Oriya
	{0x0B0F, 0x0B10, 121},   // Oriya
	{0x0B13, 0x0B28, 121},   // Oriya
	{0x0B2A, 0x0B30, 121},   // Oriya
	{0x0B32, 0x0B33, 121},   // Oriya
	{0x0B35, 0x0B39, 121},   // Oriya
	{0x0B3C, 0x0B44, 121},   // Oriya
	{0x0B47, 0x0B48, 121},   // Oriya
	{0x0B4B, 0x0B4D, 121},   // Oriya
	{0x0B55, 0x0B57, 121},   // Oriya
	{0x0B5C, 0x0B5D, 121},   // Oriya
	{0x0B5F, 0x0B63, 121},   // Oriya
	{0x0B66, 0x0B77, 121},   // Oriya
	{0x0B82, 0x0B83, 154},   // Tamil
	{0x0B85, 0x0B8A, 154},   // Tamil
	{0x0B8E, 0x0B90, 154},   // Tamil
	{0x0B92, 0x0B95, 154},   // Tamil
	{0x0B99, 0x0B9A, 154},   // Tamil
	{0x0B9C, 0x0B9C, 154},   // Tamil
	{0x0B9E, 0x0B9F, 154},   // Tamil
	{0x0BA3, 0x0BA4, 154},   // Tamil
	{0x0BA8, 0x0BAA, 154},   // Tamil
	{0x0BAE, 0x0BB9, 154},   // Tamil
	{0x0BBE, 0x0BC2, 154},   // Tamil
	{0x0BC6, 0x0BC8, 154},   // Tamil
	{0x0BCA, 0x0BCD, 154},   // Tamil
	{0x0BD0, 0x0BD0, 154},   // Tamil
	{0x0BD7, 0x0BD7, 154},   // Tamil
	{0x0BE6, 0x0BFA, 154},   // Tamil
	{0x0C00, 0x0C0C, 157},   // Telugu
	{0x0C0E, 0x0C10, 157},   // Telugu
	{0x0C12, 0x0C28, 157},   // Telugu
	{0x0C2A, 0x0C39, 157},   // Telugu
	{0x0C3C, 0x0C44, 157},   // Telugu
	{0x0C46, 0x0C48, 157},   // Telugu
	{0x0C4A, 0x0C4D, 157},   // Telugu
	{0x0C55, 0x0C56, 157},   // Telugu
	{0x0C58, 0x0C5A, 157},   // Telugu
	{0x0C5C, 0x0C5D, 157},   // Telugu
	{0x0C60, 0x0C63, 157},   // Telugu
	{0x0C66, 0x0C6F, 157},   // Telugu
	{0x0C77, 0x0C7F, 157},   // Telugu
	{0x0C80, 0x0C8C, 64},    // Kannada
	{0x0C8E, 0x0C90, 64},    // Kannada
	{0x0C92, 0x0CA8, 64},    // Kannada
	{0x0CAA, 0x0CB3, 64},    // Kannada
	{0x0CB5, 0x0CB9, 64},    // Kannada
	{0x0CBC, 0x0CC4, 64},    // Kannada
	{0x0CC6, 0x0CC8, 64},    // Kannada
	{0x0CCA, 0x0CCD, 64},    // Kannada
	{0x0CD5, 0x0CD6, 64},    // Kannada
	{0x0CDC, 0x0CDE, 64},    // Kannada
	{0x0CE0, 0x0CE3, 64},    // Kannada
	{0x0CE6, 0x0CEF, 64},    // Kannada
	{0x0CF1, 0x0CF3, 64},    // Kannada
	{0x0D00, 0x0D0C, 85},    // Malayalam
	{0x0D0E, 0x0D10, 85},    // Malayalam
	{0x0D12, 0x0D44, 85},    // Malayalam
	{0x0D46, 0x0D48, 85},    // Malayalam
	{0x0D4A, 0x0D4F, 85},    // Malayalam
	{0x0D54, 0x0D63, 85},    // Malayalam
	{0x0D66, 0x0D7F, 85},    // Malayalam
	{0x0D81, 0x0D83, 139},   // Sinhala
	{0x0D85, 0x0D96, 139},   // Sinhala
	{0x0D9A, 0x0DB1, 139},   // Sinhala
	{0x0DB3, 0x0DBB, 139},   // Sinhala
	{0x0DBD, 0x0DBD, 139},   // Sinhala
	{0x0DC0, 0x0DC6, 139},   // Sinhala
	{0x0DCA, 0x0DCA, 139},   // Sinhala
	{0x0DCF, 0x0DD4, 139},   // Sinhala
	{0x0DD6, 0x0DD6, 139},   // Sinhala
	{0x0DD8, 0x0DDF, 139},   // Sinhala
	{0x0DE6, 0x0DEF, 139},   // Sinhala
	{0x0DF2, 0x0DF4, 139},   // Sinhala
	{0x0E01, 0x0E3A, 159},   // Thai
	{0x0E3F, 0x0E3F, 0},     // Common
	{0x0E40, 0x0E5B, 159},   // Thai
	{0x0E81, 0x0E82, 74},    // Lao
	{0x0E84, 0x0E84, 74},    // Lao
	{0x0E86, 0x0E8A, 74},    // Lao
	{0x0E8C, 0x0EA3, 74},    // Lao
	{0x0EA5, 0x0EA5, 74},    // Lao
	{0x0EA7, 0x0EBD, 74},    // Lao
	{0x0EC0, 0x0EC4, 74},    // Lao
	{0x0EC6, 0x0EC6, 74},    // Lao
	{0x0EC8, 0x0ECE, 74},    // Lao
	{0x0ED0, 0x0ED9, 74},    // Lao
	{0x0EDC, 0x0EDF, 74},    // Lao
	{0x0F00, 0x0F47, 160},   // Tibetan
	{0x0F49, 0x0F6C, 160},   // Tibetan
	{0x0F71, 0x0F97, 160},   // Tibetan
	{0x0F99, 0x0FBC, 160},   // Tibetan
	{0x0FBE, 0x0FCC, 160},   // Tibetan
	{0x0FCE, 0x0FD4, 160},   // Tibetan
	{0x0FD5, 0x0FD8, 0},     // Common
	{0x0FD9, 0x0FDA, 160},   // Tibetan
	{0x1000, 0x109F, 100},   // Myanmar
	{0x10A0, 0x10C5, 43},    // Georgian
	{0x10C7, 0x10C7, 43},    // Georgian
	{0x10CD, 0x10CD, 43},    // Georgian
	{0x10D0, 0x10FA, 43},    // Georgian
	{0x10FB, 0x10FB, 0},     // Common
	{0x10FC, 0x10FF, 43},    // Georgian
	{0x1100, 0x11FF, 53},    // Hangul
	{0x1200, 0x1248, 41},    // Ethiopic
	{0x124A, 0x124D, 41},    // Ethiopic
	{0x1250, 0x1256, 41},    // Ethiopic
	{0x1258, 0x1258, 41},    // Ethiopic
	{0x125A, 0x125D, 41},    // Ethiopic
	{0x1260, 0x1288, 41},    // Ethiopic
	{0x128A, 0x128D, 41},    // Ethiopic
	{0x1290, 0x12B0, 41},    // Ethiopic
	{0x12B2, 0x12B5, 41},    // Ethiopic
	{0x12B8, 0x12BE, 41},    // Ethiopic
	{0x12C0, 0x12C0, 41},    // Ethiopic
	{0x12C2, 0x12C5, 41},    // Ethiopic
	{0x12C8, 0x12D6, 41},    // Ethiopic
	{0x12D8, 0x1310, 41},    // Ethiopic
	{0x1312, 0x1315, 41},    // Ethiopic
	{0x1318, 0x135A, 41},    // Ethiopic
	{0x135D, 0x137C, 41},    // Ethiopic
	{0x1380, 0x1399, 41},    // Ethiopic
	{0x13A0, 0x13F5, 26},    // Cherokee
	{0x13F8, 0x13FD, 26},    // Cherokee
	{0x1400, 0x167F, 21},    // Canadian_Aboriginal
	{0x1680, 0x169C, 109},   // Ogham
	{0x16A0, 0x16EA, 131},   // Runic
	{0x16EB, 0x16ED, 0},     // Common
	{0x16EE, 0x16F8, 131},   // Runic
	{0x1700, 0x1715, 147},   // Tagalog
	{0x171F, 0x171F, 147},   // Tagalog
	{0x1720, 0x1734, 55},    // Hanunoo
	{0x1735, 0x1736, 0},     // Common
	{0x1740, 0x1753, 20},    // Buhid
	{0x1760, 0x176C, 148},   // Tagbanwa
	{0x176E, 0x1770, 148},   // Tagbanwa
	{0x1772, 0x1773, 148},   // Tagbanwa
	{0x1780, 0x17DD, 70},    // Khmer
	{0x17E0, 0x17E9, 70},    // Khmer
	{0x17F0, 0x17F9, 70},    // Khmer
	{0x1800, 0x1801, 97},    // Mongolian
	{0x1802, 0x1803, 0},     // Common
	{0x1804, 0x1804, 97},    // Mongolian
	{0x1805, 0x1805, 0},     // Common
	{0x1806, 0x1819, 97},    // Mongolian
	{0x1820, 0x1878, 97},    // Mongolian
	{0x1880, 0x18AA, 97},    // Mongolian
	{0x18B0, 0x18F5, 21},    // Canadian_Aboriginal
	{0x1900, 0x191E, 77},    // Limbu
	{0x1920, 0x192B, 77},    // Limbu
	{0x1930, 0x193B, 77},    // Limbu
	{0x1940, 0x1940, 77},    // Limbu
	{0x1944, 0x194F, 77},    // Limbu
	{0x1950, 0x196D, 149},   // Tai_Le
	{0x1970, 0x1974, 149},   // Tai_Le
	{0x1980, 0x19AB, 104},   // New_Tai_Lue
	{0x19B0, 0x19C9, 104},   // New_Tai_Lue
	{0x19D0, 0x19DA, 104},   // New_Tai_Lue
	{0x19DE, 0x19DF, 104},   // New_Tai_Lue
	{0x19E0, 0x19FF, 70},    // Khmer
	{0x1A00, 0x1A1B, 19},    // Buginese
	{0x1A1E, 0x1A1F, 19},    // Buginese
	{0x1A20, 0x1A5E, 150},   // Tai_Tham
	{0x1A60, 0x1A7C, 150},   // Tai_Tham
	{0x1A7F, 0x1A89, 150},   // Tai_Tham
	{0x1A90, 0x1A99, 150},   // Tai_Tham
	{0x1AA0, 0x1AAD, 150},   // Tai_Tham
	{0x1AB0, 0x1ADD, 1},     // Inherited
	{0x1AE0, 0x1AEB, 1},     // Inherited
	{0x1B00, 0x1B4C, 9},     // Balinese
	{0x1B4E, 0x1B7F, 9},     // Balinese
	{0x1B80, 0x1BBF, 143},   // Sundanese
	{0x1BC0, 0x1BF3, 12},    // Batak
	{0x1BFC, 0x1BFF, 12},    // Batak
	{0x1C00, 0x1C37, 76},    // Lepcha
	{0x1C3B, 0x1C49, 76},    // Lepcha
	{0x1C4D, 0x1C4F, 76},    // Lepcha
	{0x1C50, 0x1C7F, 110},   // Ol_Chiki
	{0x1C80, 0x1C8A, 32},    // Cyrillic
	{0x1C90, 0x1CBA, 43},    // Georgian
	{0x1CBD, 0x1CBF, 43},    // Georgian
	{0x1CC0, 0x1CC7, 143},   // Sundanese
	{0x1CD0, 0x1CD2, 1},     // Inherited
	{0x1CD3, 0x1CD3, 0},     // Common
	{0x1CD4, 0x1CE0, 1},     // Inherited
	{0x1CE1, 0x1CE1, 0},     // Common
	{0x1CE2, 0x1CE8, 1},     // Inherited
	{0x1CE9, 0x1CEC, 0},     // Common
	{0x1CED, 0x1CED, 1},     // Inherited
	{0x1CEE, 0x1CF3, 0},     // Common
	{0x1CF4, 0x1CF4, 1},     // Inherited
	{0x1CF5, 0x1CF7, 0},     // Common
	{0x1CF8, 0x1CF9, 1},     // Inherited
	{0x1CFA, 0x1CFA, 0},     // Common
	{0x1D00, 0x1D25, 75},    // Latin
	{0x1D26, 0x1D2A, 47},    // Greek
	{0x1D2B, 0x1D2B, 32},    // Cyrillic
	{0x1D2C, 0x1D5C, 75},    // Latin
	{0x1D5D, 0x1D61, 47},    // Greek
	{0x1D62, 0x1D65, 75},    // Latin
	{0x1D66, 0x1D6A, 47},    // Greek
	{0x1D6B, 0x1D77, 75},    // Latin
	{0x1D78, 0x1D78, 32},    // Cyrillic
	{0x1D79, 0x1DBE, 75},    // Latin
	{0x1DBF, 0x1DBF, 47},    // Greek
	{0x1DC0, 0x1DFF, 1},     // Inherited
	{0x1E00, 0x1EFF, 75},    // Latin
	{0x1F00, 0x1F15, 47},    // Greek
	{0x1F18, 0x1F1D, 47},    // Greek
	{0x1F20, 0x1F45, 47},    // Greek
	{0x1F48, 0x1F4D, 47},    // Greek
	{0x1F50, 0x1F57, 47},    // Greek
	{0x1F59, 0x1F59, 47},    // Greek
	{0x1F5B, 0x1F5B, 47},    // Greek
	{0x1F5D, 0x1F5D, 47},    // Greek
	{0x1F5F, 0x1F7D, 47},    // Greek
	{0x1F80, 0x1FB4, 47},    // Greek
	{0x1FB6, 0x1FC4, 47},    // Greek
	{0x1FC6, 0x1FD3, 47},    // Greek
	{0x1FD6, 0x1FDB, 47},    // Greek
	{0x1FDD, 0x1FEF, 47},    // Greek
	{0x1FF2, 0x1FF4, 47},    // Greek
	{0x1FF6, 0x1FFE, 47},    // Greek
	{0x2000, 0x200B, 0},     // Common
	{0x200C, 0x200D, 1},     // Inherited
	{0x200E, 0x2064, 0},     // Common
	{0x2066, 0x2070, 0},     // Common
	{0x2071, 0x2071, 75},    // Latin
	{0x2074, 0x207E, 0},     // Common
	{0x207F, 0x207F, 75},    // Latin
	{0x2080, 0x208E, 0},     // Common
	{0x2090, 0x209C, 75},    // Latin
	{0x20A0, 0x20C1, 0},     // Common
	{0x20D0, 0x20F0, 1},     // Inherited
	{0x2100, 0x2125, 0},     // Common
	{0x2126, 0x2126, 47},    // Greek
	{0x2127, 0x2129, 0},     // Common
	{0x212A, 0x212B, 75},    // Latin
	{0x212C, 0x2131, 0},     // Common
	{0x2132, 0x2132, 75},    // Latin
	{0x2133, 0x214D, 0},     // Common
	{0x214E, 0x214E, 75},    // Latin
	{0x214F, 0x215F, 0},     // Common
	{0x2160, 0x2188, 75},    // Latin
	{0x2189, 0x218B, 0},     // Common
	{0x2190, 0x2429, 0},     // Common
	{0x2440, 0x244A, 0},     // Common
	{0x2460, 0x27FF, 0},     // Common
	{0x2800, 0x28FF, 18},    // Braille
	{0x2900, 0x2B73, 0},     // Common
	{0x2B76, 0x2BFF, 0},     // Common
	{0x2C00, 0x2C5F, 44},    // Glagolitic
	{0x2C60, 0x2C7F, 75},    // Latin
	{0x2C80, 0x2CF3, 28},    // Coptic
	{0x2CF9, 0x2CFF, 28},    // Coptic
	{0x2D00, 0x2D25, 43},    // Georgian
	{0x2D27, 0x2D27, 43},    // Georgian
	{0x2D2D, 0x2D2D, 43},    // Georgian
	{0x2D30, 0x2D67, 161},   // Tifinagh
	{0x2D6F, 0x2D70, 161},   // Tifinagh
	{0x2D7F, 0x2D7F, 161},   // Tifinagh
	{0x2D80, 0x2D96, 41},    // Ethiopic
	{0x2DA0, 0x2DA6, 41},    // Ethiopic
	{0x2DA8, 0x2DAE, 41},    // Ethiopic
	{0x2DB0, 0x2DB6, 41},    // Ethiopic
	{0x2DB8, 0x2DBE, 41},    // Ethiopic
	{0x2DC0, 0x2DC6, 41},    // Ethiopic
	{0x2DC8, 0x2DCE, 41},    // Ethiopic
	{0x2DD0, 0x2DD6, 41},    // Ethiopic
	{0x2DD8, 0x2DDE, 41},    // Ethiopic
	{0x2DE0, 0x2DFF, 32},    // Cyrillic
	{0x2E00, 0x2E5D, 0},     // Common
	{0x2E80, 0x2E99, 52},    // Han
	{0x2E9B, 0x2EF3, 52},    // Han
	{0x2F00, 0x2FD5, 52},    // Han
	{0x2FF0, 0x3004, 0},     // Common
	{0x3005, 0x3005, 52},    // Han
	{0x3006, 0x3006, 0},     // Common
	{0x3007, 0x3007, 52},    // Han
	{0x3008, 0x3020, 0},     // Common
	{0x3021, 0x3029, 52},    // Han
	{0x302A, 0x302D, 1},     // Inherited
	{0x302E, 0x302F, 53},    // Hangul
	{0x3030, 0x3037, 0},     // Common
	{0x3038, 0x303B, 52},    // Han
	{0x303C, 0x303F, 0},     // Common
	{0x3041, 0x3096, 58},    // Hiragana
	{0x3099, 0x309A, 1},     // Inherited
	{0x309B, 0x309C, 0},     // Common
	{0x309D, 0x309F, 58},    // Hiragana
	{0x30A0, 0x30A0, 0},     // Common
	{0x30A1, 0x30FA, 65},    // Katakana
	{0x30FB, 0x30FC, 0},     // Common
	{0x30FD, 0x30FF, 65},    // Katakana
	{0x3105, 0x312F, 16},    // Bopomofo
	{0x3131, 0x318E, 53},    // Hangul
	{0x3190, 0x319F, 0},     // Common
	{0x31A0, 0x31BF, 16},    // Bopomofo
	{0x31C0, 0x31E5, 0},     // Common
	{0x31EF, 0x31EF, 0},     // Common
	{0x31F0, 0x31FF, 65},    // Katakana
	{0x3200, 0x321E, 53},    // Hangul
	{0x3220, 0x325F, 0},     // Common
	{0x3260, 0x327E, 53},    // Hangul
	{0x327F, 0x32CF, 0},     // Common
	{0x32D0, 0x32FE, 65},    // Katakana
	{0x32FF, 0x32FF, 0},     // Common
	{0x3300, 0x3357, 65},    // Katakana
	{0x3358, 0x33FF, 0},     // Common
	{0x3400, 0x4DBF, 52},    // Han
	{0x4DC0, 0x4DFF, 0},     // Common
	{0x4E00, 0x9FFF, 52},    // Han
	{0xA000, 0xA48C, 173},   // Yi
	{0xA490, 0xA4C6, 173},   // Yi
	{0xA4D0, 0xA4FF, 80},    // Lisu
	{0xA500, 0xA62B, 168},   // Vai
	{0xA640, 0xA69F, 32},    // Cyrillic
	{0xA6A0, 0xA6F7, 10},    // Bamum
	{0xA700, 0xA721, 0},     // Common
	{0xA722, 0xA787, 75},    // Latin
	{0xA788, 0xA78A, 0},     // Common
	{0xA78B, 0xA7DC, 75},    // Latin
	{0xA7F1, 0xA7FF, 75},    // Latin
	{0xA800, 0xA82C, 145},   // Syloti_Nagri
	{0xA830, 0xA839, 0},     // Common
	{0xA840, 0xA877, 127},   // Phags_Pa
	{0xA880, 0xA8C5, 133},   // Saurashtra
	{0xA8CE, 0xA8D9, 133},   // Saurashtra
	{0xA8E0, 0xA8FF, 34},    // Devanagari
	{0xA900, 0xA92D, 67},    // Kayah_Li
	{0xA92E, 0xA92E, 0},     // Common
	{0xA92F, 0xA92F, 67},    // Kayah_Li
	{0xA930, 0xA953, 130},   // Rejang
	{0xA95F, 0xA95F, 130},   // Rejang
	{0xA960, 0xA97C, 53},    // Hangul
	{0xA980, 0xA9CD, 62},    // Javanese
	{0xA9CF, 0xA9CF, 0},     // Common
	{0xA9D0, 0xA9D9, 62},    // Javanese
	{0xA9DE, 0xA9DF, 62},    // Javanese
	{0xA9E0, 0xA9FE, 100},   // Myanmar
	{0xAA00, 0xAA36, 25},    // Cham
	{0xAA40, 0xAA4D, 25},    // Cham
	{0xAA50, 0xAA59, 25},    // Cham
	{0xAA5C, 0xAA5F, 25},    // Cham
	{0xAA60, 0xAA7F, 100},   // Myanmar
	{0xAA80, 0xAAC2, 151},   // Tai_Viet
	{0xAADB, 0xAADF, 151},   // Tai_Viet
	{0xAAE0, 0xAAF6, 91},    // Meetei_Mayek
	{0xAB01, 0xAB06, 41},    // Ethiopic
	{0xAB09, 0xAB0E, 41},    // Ethiopic
	{0xAB11, 0xAB16, 41},    // Ethiopic
	{0xAB20, 0xAB26, 41},    // Ethiopic
	{0xAB28, 0xAB2E, 41},    // Ethiopic
	{0xAB30, 0xAB5A, 75},    // Latin
	{0xAB5B, 0xAB5B, 0},     // Common
	{0xAB5C, 0xAB64, 75},    // Latin
	{0xAB65, 0xAB65, 47},    // Greek
	{0xAB66, 0xAB69, 75},    // Latin
	{0xAB6A, 0xAB6B, 0},     // Common
	{0xAB70, 0xABBF, 26},    // Cherokee
	{0xABC0, 0xABED, 91},    // Meetei_Mayek
	{0xABF0, 0xABF9, 91},    // Meetei_Mayek
	{0xAC00, 0xD7A3, 53},    // Hangul
	{0xD7B0, 0xD7C6, 53},    // Hangul
	{0xD7CB, 0xD7FB, 53},    // Hangul
	{0xF900, 0xFA6D, 52},    // Han
	{0xFA70, 0xFAD9, 52},    // Han
	{0xFB00, 0xFB06, 75},    // Latin
	{0xFB13, 0xFB17, 7},     // Armenian
	{0xFB1D, 0xFB36, 57},    // Hebrew
	{0xFB38, 0xFB3C, 57},    // Hebrew
	{0xFB3E, 0xFB3E, 57},    // Hebrew
	{0xFB40, 0xFB41, 57},    // Hebrew
	{0xFB43, 0xFB44, 57},    // Hebrew
	{0xFB46, 0xFB4F, 57},    // Hebrew
	{0xFB50, 0xFD3D, 6},     // Arabic
	{0xFD3E, 0xFD3F, 0},     // Common
	{0xFD40, 0xFDCF, 6},     // Arabic
	{0xFDF0, 0xFDFF, 6},     // Arabic
	{0xFE00, 0xFE0F, 1},     // Inherited
	{0xFE10, 0xFE19, 0},     // Common
	{0xFE20, 0xFE2D, 1},     // Inherited
	{0xFE2E, 0xFE2F, 32},    // Cyrillic
	{0xFE30, 0xFE52, 0},     // Common
	{0xFE54, 0xFE66, 0},     // Common
	{0xFE68, 0xFE6B, 0},     // Common
	{0xFE70, 0xFE74, 6},     // Arabic
	{0xFE76, 0xFEFC, 6},     // Arabic
	{0xFEFF, 0xFEFF, 0},     // Common
	{0xFF01, 0xFF20, 0},     // Common
	{0xFF21, 0xFF3A, 75},    // Latin
	{0xFF3B, 0xFF40, 0},     // Common
	{0xFF41, 0xFF5A, 75},    // Latin
	{0xFF5B, 0xFF65, 0},     // Common
	{0xFF66, 0xFF6F, 65},    // Katakana
	{0xFF70, 0xFF70, 0},     // Common
	{0xFF71, 0xFF9D, 65},    // Katakana
	{0xFF9E, 0xFF9F, 0},     // Common
	{0xFFA0, 0xFFBE, 53},    // Hangul
	{0xFFC2, 0xFFC7, 53},    // Hangul
	{0xFFCA, 0xFFCF, 53},    // Hangul
	{0xFFD2, 0xFFD7, 53},    // Hangul
	{0xFFDA, 0xFFDC, 53},    // Hangul
	{0xFFE0, 0xFFE6, 0},     // Common
	{0xFFE8, 0xFFEE, 0},     // Common
	{0xFFF9, 0xFFFD, 0},     // Common
	{0x10000, 0x1000B, 79},  // Linear_B
	{0x1000D, 0x10026, 79},  // Linear_B
	{0x10028, 0x1003A, 79},  // Linear_B
	{0x1003C, 0x1003D, 79},  // Linear_B
	{0x1003F, 0x1004D, 79},  // Linear_B
	{0x10050, 0x1005D, 79},  // Linear_B
	{0x10080, 0x100FA, 79},  // Linear_B
	{0x10100, 0x10102, 0},   // Common
	{0x10107, 0x10133, 0},   // Common
	{0x10137, 0x1013F, 0},   // Common
	{0x10140, 0x1018E, 47},  // Greek
	{0x10190, 0x1019C, 0},   // Common
	{0x101A0, 0x101A0, 47},  // Greek
	{0x101D0, 0x101FC, 0},   // Common
	{0x101FD, 0x101FD, 1},   // Inherited
	{0x10280, 0x1029C, 81},  // Lycian
	{0x102A0, 0x102D0, 22},  // Carian
	{0x102E0, 0x102E0, 1},   // Inherited
	{0x102E1, 0x102FB, 0},   // Common
	{0x10300, 0x10323, 113}, // Old_Italic
	{0x1032D, 0x1032F, 113}, // Old_Italic
	{0x10330, 0x1034A, 45},  // Gothic
	{0x10350, 0x1037A, 115}, // Old_Permic
	{0x10380, 0x1039D, 167}, // Ugaritic
	{0x1039F, 0x1039F, 167}, // Ugaritic
	{0x103A0, 0x103C3, 116}, // Old_Persian
	{0x103C8, 0x103D5, 116}, // Old_Persian
	{0x10400, 0x1044F, 33},  // Deseret
	{0x10450, 0x1047F, 135}, // Shavian
	{0x10480, 0x1049D, 123}, // Osmanya
	{0x104A0, 0x104A9, 123}, // Osmanya
	{0x104B0, 0x104D3, 122}, // Osage
	{0x104D8, 0x104FB, 122}, // Osage
	{0x10500, 0x10527, 39},  // Elbasan
	{0x10530, 0x10563, 23},  // Caucasian_Albanian
	{0x1056F, 0x1056F, 23},  // Caucasian_Albanian
	{0x10570, 0x1057A, 169}, // Vithkuqi
	{0x1057C, 0x1058A, 169}, // Vithkuqi
	{0x1058C, 0x10592, 169}, // Vithkuqi
	{0x10594, 0x10595, 169}, // Vithkuqi
	{0x10597, 0x105A1, 169}, // Vithkuqi
	{0x105A3, 0x105B1, 169}, // Vithkuqi
	{0x105B3, 0x105B9, 169}, // Vithkuqi
	{0x105BB, 0x105BC, 169}, // Vithkuqi
	{0x105C0, 0x105F3, 163}, // Todhri
	{0x10600, 0x10736, 78},  // Linear_A
	{0x10740, 0x10755, 78},  // Linear_A
	{0x10760, 0x10767, 78},  // Linear_A
	{0x10780, 0x10785, 75},  // Latin
	{0x10787, 0x107B0, 75},  // Latin
	{0x107B2, 0x107BA, 75},  // Latin
	{0x10800, 0x10805, 30},  // Cypriot
	{0x10808, 0x10808, 30},  // Cypriot
	{0x1080A, 0x10835, 30},  // Cypriot
	{0x10837, 0x10838, 30},  // Cypriot
	{0x1083C, 0x1083C, 30},  // Cypriot
	{0x1083F, 0x1083F, 30},  // Cypriot
	{0x10840, 0x10855, 59},  // Imperial_Aramaic
	{0x10857, 0x1085F, 59},  // Imperial_Aramaic
	{0x10860, 0x1087F, 125}, // Palmyrene
	{0x10880, 0x1089E, 101}, // Nabataean
	{0x108A7, 0x108AF, 101}, // Nabataean
	{0x108E0, 0x108F2, 56},  // Hatran
	{0x108F4, 0x108F5, 56},  // Hatran
	{0x108FB, 0x108FF, 56},  // Hatran
	{0x10900, 0x1091B, 128}, // Phoenician
	{0x1091F, 0x1091F, 128}, // Phoenician
	{0x10920, 0x10939, 82},  // Lydian
	{0x1093F, 0x1093F, 82},  // Lydian
	{0x10940, 0x10959, 137}, // Sidetic
	{0x10980, 0x1099F, 94},  // Meroitic_Hieroglyphs
	{0x109A0, 0x109B7, 93},  // Meroitic_Cursive
	{0x109BC, 0x109CF, 93},  // Meroitic_Cursive
	{0x109D2, 0x109FF, 93},  // Meroitic_Cursive
	{0x10A00, 0x10A03, 68},  // Kharoshthi
	{0x10A05, 0x10A06, 68},  // Kharoshthi
	{0x10A0C, 0x10A13, 68},  // Kharoshthi
	{0x10A15, 0x10A17, 68},  // Kharoshthi
	{0x10A19, 0x10A35, 68},  // Kharoshthi
	{0x10A38, 0x10A3A, 68},  // Kharoshthi
	{0x10A3F, 0x10A48, 68},  // Kharoshthi
	{0x10A50, 0x10A58, 68},  // Kharoshthi
	{0x10A60, 0x10A7F, 118}, // Old_South_Arabian
	{0x10A80, 0x10A9F, 114}, // Old_North_Arabian
	{0x10AC0, 0x10AE6, 87},  // Manichaean
	{0x10AEB, 0x10AF6, 87},  // Manichaean
	{0x10B00, 0x10B35, 8},   // Avestan
	{0x10B39, 0x10B3F, 8},   // Avestan
	{0x10B40, 0x10B55, 61},  // Inscriptional_Parthian
	{0x10B58, 0x10B5F, 61},  // Inscriptional_Parthian
	{0x10B60, 0x10B72, 60},  // Inscriptional_Pahlavi
	{0x10B78, 0x10B7F, 60},  // Inscriptional_Pahlavi
	{0x10B80, 0x10B91, 129}, // Psalter_Pahlavi
	{0x10B99, 0x10B9C, 129}, // Psalter_Pahlavi
	{0x10BA9, 0x10BAF, 129}, // Psalter_Pahlavi
	{0x10C00, 0x10C48, 119}, // Old_Turkic
	{0x10C80, 0x10CB2, 112}, // Old_Hungarian
	{0x10CC0, 0x10CF2, 112}, // Old_Hungarian
	{0x10CFA, 0x10CFF, 112}, // Old_Hungarian
	{0x10D00, 0x10D27, 54},  // Hanifi_Rohingya
	{0x10D30, 0x10D39, 54},  // Hanifi_Rohingya
	{0x10D40, 0x10D65, 42},  // Garay
	{0x10D69, 0x10D85, 42},  // Garay
	{0x10D8E, 0x10D8F, 42},  // Garay
	{0x10E60, 0x10E7E, 6},   // Arabic
	{0x10E80, 0x10EA9, 172}, // Yezidi
	{0x10EAB, 0x10EAD, 172}, // Yezidi
	{0x10EB0, 0x10EB1, 172}, // Yezidi
	{0x10EC2, 0x10EC7, 6},   // Arabic
	{0x10ED0, 0x10ED8, 6},   // Arabic
	{0x10EFA, 0x10EFF, 6},   // Arabic
	{0x10F00, 0x10F27, 117}, // Old_Sogdian
	{0x10F30, 0x10F59, 140}, // Sogdian
	{0x10F70, 0x10F89, 120}, // Old_Uyghur
	{0x10FB0, 0x10FCB, 27},  // Chorasmian
	{0x10FE0, 0x10FF6, 40},  // Elymaic
	{0x11000, 0x1104D, 17},  // Brahmi
	{0x11052, 0x11075, 17},  // Brahmi
	{0x1107F, 0x1107F, 17},  // Brahmi
	{0x11080, 0x110C2, 63},  // Kaithi
	{0x110CD, 0x110CD, 63},  // Kaithi
	{0x110D0, 0x110E8, 141}, // Sora_Sompeng
	{0x110F0, 0x110F9, 141}, // Sora_Sompeng
	{0x11100, 0x11134, 24},  // Chakma
	{0x11136, 0x11147, 24},  // Chakma
	{0x11150, 0x11176, 83},  // Mahajani
	{0x11180, 0x111DF, 134}, // Sharada
	{0x111E1, 0x111F4, 139}, // Sinhala
	{0x11200, 0x11211, 71},  // Khojki
	{0x11213, 0x11241, 71},  // Khojki
	{0x11280, 0x11286, 99},  // Multani
	{0x11288, 0x11288, 99},  // Multani
	{0x1128A, 0x1128D, 99},  // Multani
	{0x1128F, 0x1129D, 99},  // Multani
	{0x1129F, 0x112A9, 99},  // Multani
	{0x112B0, 0x112EA, 72},  // Khudawadi
	{0x112F0, 0x112F9, 72},  // Khudawadi
	{0x11300, 0x11303, 46},  // Grantha
	{0x11305, 0x1130C, 46},  // Grantha
	{0x1130F, 0x11310, 46},  // Grantha
	{0x11313, 0x11328, 46},  // Grantha
	{0x1132A, 0x11330, 46},  // Grantha
	{0x11332, 0x11333, 46},  // Grantha
	{0x11335, 0x11339, 46},  // Grantha
	{0x1133B, 0x1133B, 1},   // Inherited
	{0x1133C, 0x11344, 46},  // Grantha
	{0x11347, 0x11348, 46},  // Grantha
	{0x1134B, 0x1134D, 46},  // Grantha
	{0x11350, 0x11350, 46},  // Grantha
	{0x11357, 0x11357, 46},  // Grantha
	{0x1135D, 0x11363, 46},  // Grantha
	{0x11366, 0x1136C, 46},  // Grantha
	{0x11370, 0x11374, 46},  // Grantha
	{0x11380, 0x11389, 166}, // Tulu_Tigalari
	{0x1138B, 0x1138B, 166}, // Tulu_Tigalari
	{0x1138E, 0x1138E, 166}, // Tulu_Tigalari
	{0x11390, 0x113B5, 166}, // Tulu_Tigalari
	{0x113B7, 0x113C0, 166}, // Tulu_Tigalari
	{0x113C2, 0x113C2, 166}, // Tulu_Tigalari
	{0x113C5, 0x113C5, 166}, // Tulu_Tigalari
	{0x113C7, 0x113CA, 166}, // Tulu_Tigalari
	{0x113CC, 0x113D5, 166}, // Tulu_Tigalari
	{0x113D7, 0x113D8, 166}, // Tulu_Tigalari
	{0x113E1, 0x113E2, 166}, // Tulu_Tigalari
	{0x11400, 0x1145B, 105}, // Newa
	{0x1145D, 0x11461, 105}, // Newa
	{0x11480, 0x114C7, 162}, // Tirhuta
	{0x114D0, 0x114D9, 162}, // Tirhuta
	{0x11580, 0x115B5, 136}, // Siddham
	{0x115B8, 0x115DD, 136}, // Siddham
	{0x11600, 0x11644, 96},  // Modi
	{0x11650, 0x11659, 96},  // Modi
	{0x11660, 0x1166C, 97},  // Mongolian
	{0x11680, 0x116B9, 153}, // Takri
	{0x116C0, 0x116C9, 153}, // Takri
	{0x116D0, 0x116E3, 100}, // Myanmar
	{0x11700, 0x1171A, 4},   // Ahom
	{0x1171D, 0x1172B, 4},   // Ahom
	{0x11730, 0x11746, 4},   // Ahom
	{0x11800, 0x1183B, 36},  // Dogra
	{0x118A0, 0x118F2, 171}, // Warang_Citi
	{0x118FF, 0x118FF, 171}, // Warang_Citi
	{0x11900, 0x11906, 35},  // Dives_Akuru
	{0x11909, 0x11909, 35},  // Dives_Akuru
	{0x1190C, 0x11913, 35},  // Dives_Akuru
	{0x11915, 0x11916, 35},  // Dives_Akuru
	{0x11918, 0x11935, 35},  // Dives_Akuru
	{0x11937, 0x11938, 35},  // Dives_Akuru
	{0x1193B, 0x11946, 35},  // Dives_Akuru
	{0x11950, 0x11959, 35},  // Dives_Akuru
	{0x119A0, 0x119A7, 103}, // Nandinagari
	{0x119AA, 0x119D7, 103}, // Nandinagari
	{0x119DA, 0x119E4, 103}, // Nandinagari
	{0x11A00, 0x11A47, 174}, // Zanabazar_Square
	{0x11A50, 0x11AA2, 142}, // Soyombo
	{0x11AB0, 0x11ABF, 21},  // Canadian_Aboriginal
	{0x11AC0, 0x11AF8, 126}, // Pau_Cin_Hau
	{0x11B00, 0x11B09, 34},  // Devanagari
	{0x11B60, 0x11B67, 134}, // Sharada
	{0x11BC0, 0x11BE1, 144}, // Sunuwar
	{0x11BF0, 0x11BF9, 144}, // Sunuwar
	{0x11C00, 0x11C08, 15},  // Bhaiksuki
	{0x11C0A, 0x11C36, 15},  // Bhaiksuki
	{0x11C38, 0x11C45, 15},  // Bhaiksuki
	{0x11C50, 0x11C6C, 15},  // Bhaiksuki
	{0x11C70, 0x11C8F, 88},  // Marchen
	{0x11C92, 0x11CA7, 88},  // Marchen
	{0x11CA9, 0x11CB6, 88},  // Marchen
	{0x11D00, 0x11D06, 89},  // Masaram_Gondi
	{0x11D08, 0x11D09, 89},  // Masaram_Gondi
	{0x11D0B, 0x11D36, 89},  // Masaram_Gondi
	{0x11D3A, 0x11D3A, 89},  // Masaram_Gondi
	{0x11D3C, 0x11D3D, 89},  // Masaram_Gondi
	{0x11D3F, 0x11D47, 89},  // Masaram_Gondi
	{0x11D50, 0x11D59, 89},  // Masaram_Gondi
	{0x11D60, 0x11D65, 49},  // Gunjala_Gondi
	{0x11D67, 0x11D68, 49},  // Gunjala_Gondi
	{0x11D6A, 0x11D8E, 49},  // Gunjala_Gondi
	{0x11D90, 0x11D91, 49},  // Gunjala_Gondi
	{0x11D93, 0x11D98, 49},  // Gunjala_Gondi
	{0x11DA0, 0x11DA9, 49},  // Gunjala_Gondi
	{0x11DB0, 0x11DDB, 164}, // Tolong_Siki
	{0x11DE0, 0x11DE9, 164}, // Tolong_Siki
	{0x11EE0, 0x11EF8, 84},  // Makasar
	{0x11F00, 0x11F10, 66},  // Kawi
	{0x11F12, 0x11F3A, 66},  // Kawi
	{0x11F3E, 0x11F5A, 66},  // Kawi
	{0x11FB0, 0x11FB0, 80},  // Lisu
	{0x11FC0, 0x11FF1, 154}, // Tamil
	{0x11FFF, 0x11FFF, 154}, // Tamil
	{0x12000, 0x12399, 29},  // Cuneiform
	{0x12400, 0x1246E, 29},  // Cuneiform
	{0x12470, 0x12474, 29},  // Cuneiform
	{0x12480, 0x12543, 29},  // Cuneiform
	{0x12F90, 0x12FF2, 31},  // Cypro_Minoan
	{0x13000, 0x13455, 38},  // Egyptian_Hieroglyphs
	{0x13460, 0x143FA, 38},  // Egyptian_Hieroglyphs
	{0x14400, 0x14646, 5},   // Anatolian_Hieroglyphs
	{0x16100, 0x16139, 51},  // Gurung_Khema
	{0x16800, 0x16A38, 10},  // Bamum
	{0x16A40, 0x16A5E, 98},  // Mro
	{0x16A60, 0x16A69, 98},  // Mro
	{0x16A6E, 0x16A6F, 98},  // Mro
	{0x16A70, 0x16ABE, 155}, // Tangsa
	{0x16AC0, 0x16AC9, 155}, // Tangsa
	{0x16AD0, 0x16AED, 11},  // Bassa_Vah
	{0x16AF0, 0x16AF5, 11},  // Bassa_Vah
	{0x16B00, 0x16B45, 124}, // Pahawh_Hmong
	{0x16B50, 0x16B59, 124}, // Pahawh_Hmong
	{0x16B5B, 0x16B61, 124}, // Pahawh_Hmong
	{0x16B63, 0x16B77, 124}, // Pahawh_Hmong
	{0x16B7D, 0x16B8F, 124}, // Pahawh_Hmong
	{0x16D40, 0x16D79, 73},  // Kirat_Rai
	{0x16E40, 0x16E9A, 90},  // Medefaidrin
	{0x16EA0, 0x16EB8, 14},  // Beria_Erfe
	{0x16EBB, 0x16ED3, 14},  // Beria_Erfe
	{0x16F00, 0x16F4A, 95},  // Miao
	{0x16F4F, 0x16F87, 95},  // Miao
	{0x16F8F, 0x16F9F, 95},  // Miao
	{0x16FE0, 0x16FE0, 156}, // Tangut
	{0x16FE1, 0x16FE1, 107}, // Nushu
	{0x16FE2, 0x16FE3, 52},  // Han
	{0x16FE4, 0x16FE4, 69},  // Khitan_Small_Script
	{0x16FF0, 0x16FF6, 52},  // Han
	{0x17000, 0x18AFF, 156}, // Tangut
	{0x18B00, 0x18CD5, 69},  // Khitan_Small_Script
	{0x18CFF, 0x18CFF, 69},  // Khitan_Small_Script
	{0x18D00, 0x18D1E, 156}, // Tangut
	{0x18D80, 0x18DF2, 156}, // Tangut
	{0x1AFF0, 0x1AFF3, 65},  // Katakana
	{0x1AFF5, 0x1AFFB, 65},  // Katakana
	{0x1AFFD, 0x1AFFE, 65},  // Katakana
	{0x1B000, 0x1B000, 65},  // Katakana
	{0x1B001, 0x1B11F, 58},  // Hiragana
	{0x1B120, 0x1B122, 65},  // Katakana
	{0x1B132, 0x1B132, 58},  // Hiragana
	{0x1B150, 0x1B152, 58},  // Hiragana
	{0x1B155, 0x1B155, 65},  // Katakana
	{0x1B164, 0x1B167, 65},  // Katakana
	{0x1B170, 0x1B2FB, 107}, // Nushu
	{0x1BC00, 0x1BC6A, 37},  // Duployan
	{0x1BC70, 0x1BC7C, 37},  // Duployan
	{0x1BC80, 0x1BC88, 37},  // Duployan
	{0x1BC90, 0x1BC99, 37},  // Duployan
	{0x1BC9C, 0x1BC9F, 37},  // Duployan
	{0x1BCA0, 0x1BCA3, 0},   // Common
	{0x1CC00, 0x1CCFC, 0},   // Common
	{0x1CD00, 0x1CEB3, 0},   // Common
	{0x1CEBA, 0x1CED0, 0},   // Common
	{0x1CEE0, 0x1CEF0, 0},   // Common
	{0x1CF00, 0x1CF2D, 1},   // Inherited
	{0x1CF30, 0x1CF46, 1},   // Inherited
	{0x1CF50, 0x1CFC3, 0},   // Common
	{0x1D000, 0x1D0F5, 0},   // Common
	{0x1D100, 0x1D126, 0},   // Common
	{0x1D129, 0x1D166, 0},   // Common
	{0x1D167, 0x1D169, 1},   // Inherited
	{0x1D16A, 0x1D17A, 0},   // Common
	{0x1D17B, 0x1D182, 1},   // Inherited
	{0x1D183, 0x1D184, 0},   // Common
	{0x1D185, 0x1D18B, 1},   // Inherited
	{0x1D18C, 0x1D1A9, 0},   // Common
	{0x1D1AA, 0x1D1AD, 1},   // Inherited
	{0x1D1AE, 0x1D1EA, 0},   // Common
	{0x1D200, 0x1D245, 47},  // Greek
	{0x1D2C0, 0x1D2D3, 0},   // Common
	{0x1D2E0, 0x1D2F3, 0},   // Common
	{0x1D300, 0x1D356, 0},   // Common
	{0x1D360, 0x1D378, 0},   // Common
	{0x1D400, 0x1D454, 0},   // Common
	{0x1D456, 0x1D49C, 0},   // Common
	{0x1D49E, 0x1D49F, 0},   // Common
	{0x1D4A2, 0x1D4A2, 0},   // Common
	{0x1D4A5, 0x1D4A6, 0},   // Common
	{0x1D4A9, 0x1D4AC, 0},   // Common
	{0x1D4AE, 0x1D4B9, 0},   // Common
	{0x1D4BB, 0x1D4BB, 0},   // Common
	{0x1D4BD, 0x1D4C3, 0},   // Common
	{0x1D4C5, 0x1D505, 0},   // Common
	{0x1D507, 0x1D50A, 0},   // Common
	{0x1D50D, 0x1D514, 0},   // Common
	{0x1D516, 0x1D51C, 0},   // Common
	{0x1D51E, 0x1D539, 0},   // Common
	{0x1D53B, 0x1D53E, 0},   // Common
	{0x1D540, 0x1D544, 0},   // Common
	{0x1D546, 0x1D546, 0},   // Common
	{0x1D54A, 0x1D550, 0},   // Common
	{0x1D552, 0x1D6A5, 0},   // Common
	{0x1D6A8, 0x1D7CB, 0},   // Common
	{0x1D7CE, 0x1D7FF, 0},   // Common
	{0x1D800, 0x1DA8B, 138}, // SignWriting
	{0x1DA9B, 0x1DA9F, 138}, // SignWriting
	{0x1DAA1, 0x1DAAF, 138}, // SignWriting
	{0x1DF00, 0x1DF1E, 75},  // Latin
	{0x1DF25, 0x1DF2A, 75},  // Latin
	{0x1E000, 0x1E006, 44},  // Glagolitic
	{0x1E008, 0x1E018, 44},  // Glagolitic
	{0x1E01B, 0x1E021, 44},  // Glagolitic
	{0x1E023, 0x1E024, 44},  // Glagolitic
	{0x1E026, 0x1E02A, 44},  // Glagolitic
	{0x1E030, 0x1E06D, 32},  // Cyrillic
	{0x1E08F, 0x1E08F, 32},  // Cyrillic
	{0x1E100, 0x1E12C, 108}, // Nyiakeng_Puachue_Hmong
	{0x1E130, 0x1E13D, 108}, // Nyiakeng_Puachue_Hmong
	{0x1E140, 0x1E149, 108}, // Nyiakeng_Puachue_Hmong
	{0x1E14E, 0x1E14F, 108}, // Nyiakeng_Puachue_Hmong
	{0x1E290, 0x1E2AE, 165}, // Toto
	{0x1E2C0, 0x1E2F9, 170}, // Wancho
	{0x1E2FF, 0x1E2FF, 170}, // Wancho
	{0x1E4D0, 0x1E4F9, 102}, // Nag_Mundari
	{0x1E5D0, 0x1E5FA, 111}, // Ol_Onal
	{0x1E5FF, 0x1E5FF, 111}, // Ol_Onal
	{0x1E6C0, 0x1E6DE, 152}, // Tai_Yo
	{0x1E6E0, 0x1E6F5, 152}, // Tai_Yo
	{0x1E6FE, 0x1E6FF, 152}, // Tai_Yo
	{0x1E7E0, 0x1E7E6, 41},  // Ethiopic
	{0x1E7E8, 0x1E7EB, 41},  // Ethiopic
	{0x1E7ED, 0x1E7EE, 41},  // Ethiopic
	{0x1E7F0, 0x1E7FE, 41},  // Ethiopic
	{0x1E800, 0x1E8C4, 92},  // Mende_Kikakui
	{0x1E8C7, 0x1E8D6, 92},  // Mende_Kikakui
	{0x1E900, 0x1E94B, 3},   // Adlam
	{0x1E950, 0x1E959, 3},   // Adlam
	{0x1E95E, 0x1E95F, 3},   // Adlam
	{0x1EC71, 0x1ECB4, 0},   // Common
	{0x1ED01, 0x1ED3D, 0},   // Common
	{0x1EE00, 0x1EE03, 6},   // Arabic
	{0x1EE05, 0x1EE1F, 6},   // Arabic
	{0x1EE21, 0x1EE22, 6},   // Arabic
	{0x1EE24, 0x1EE24, 6},   // Arabic
	{0x1EE27, 0x1EE27, 6},   // Arabic
	{0x1EE29, 0x1EE32, 6},   // Arabic
	{0x1EE34, 0x1EE37, 6},   // Arabic
	{0x1EE39, 0x1EE39, 6},   // Arabic
	{0x1EE3B, 0x1EE3B, 6},   // Arabic
	{0x1EE42, 0x1EE42, 6},   // Arabic
	{0x1EE47, 0x1EE47, 6},   // Arabic
	{0x1EE49, 0x1EE49, 6},   // Arabic
	{0x1EE4B, 0x1EE4B, 6},   // Arabic
	{0x1EE4D, 0x1EE4F, 6},   // Arabic
	{0x1EE51, 0x1EE52, 6},   // Arabic
	{0x1EE54, 0x1EE54, 6},   // Arabic
	{0x1EE57, 0x1EE57, 6},   // Arabic
	{0x1EE59, 0x1EE59, 6},   // Arabic
	{0x1EE5B, 0x1EE5B, 6},   // Arabic
	{0x1EE5D, 0x1EE5D, 6},   // Arabic
	{0x1EE5F, 0x1EE5F, 6},   // Arabic
	{0x1EE61, 0x1EE62, 6},   // Arabic
	{0x1EE64, 0x1EE64, 6},   // Arabic
	{0x1EE67, 0x1EE6A, 6},   // Arabic
	{0x1EE6C, 0x1EE72, 6},   // Arabic
	{0x1EE74, 0x1EE77, 6},   // Arabic
	{0x1EE79, 0x1EE7C, 6},   // Arabic
	{0x1EE7E, 0x1EE7E, 6},   // Arabic
	{0x1EE80, 0x1EE89, 6},   // Arabic
	{0x1EE8B, 0x1EE9B, 6},   // Arabic
	{0x1EEA1, 0x1EEA3, 6},   // Arabic
	{0x1EEA5, 0x1EEA9, 6},   // Arabic
	{0x1EEAB, 0x1EEBB, 6},   // Arabic
	{0x1EEF0, 0x1EEF1, 6},   // Arabic
	{0x1F000, 0x1F02B, 0},   // Common
	{0x1F030, 0x1F093, 0},   // Common
	{0x1F0A0, 0x1F0AE, 0},   // Common
	{0x1F0B1, 0x1F0BF, 0},   // Common
	{0x1F0C1, 0x1F0CF, 0},   // Common
	{0x1F0D1, 0x1F0F5, 0},   // Common
	{0x1F100, 0x1F1AD, 0},   // Common
	{0x1F1E6, 0x1F1FF, 0},   // Common
	{0x1F200, 0x1F200, 58},  // Hiragana
	{0x1F201, 0x1F202, 0},   // Common
	{0x1F210, 0x1F23B, 0},   // Common
	{0x1F240, 0x1F248, 0},   // Common
	{0x1F250, 0x1F251, 0},   // Common
	{0x1F260, 0x1F265, 0},   // Common
	{0x1F300, 0x1F6D8, 0},   // Common
	{0x1F6DC, 0x1F6EC, 0},   // Common
	{0x1F6F0, 0x1F6FC, 0},   // Common
	{0x1F700, 0x1F7D9, 0},   // Common
	{0x1F7E0, 0x1F7EB, 0},   // Common
	{0x1F7F0, 0x1F7F0, 0},   // Common
	{0x1F800, 0x1F80B, 0},   // Common
	{0x1F810, 0x1F847, 0},   // Common
	{0x1F850, 0x1F859, 0},   // Common
	{0x1F860, 0x1F887, 0},   // Common
	{0x1F890, 0x1F8AD, 0},   // Common
	{0x1F8B0, 0x1F8BB, 0},   // Common
	{0x1F8C0, 0x1F8C1, 0},   // Common
	{0x1F8D0, 0x1F8D8, 0},   // Common
	{0x1F900, 0x1FA57, 0},   // Common
	{0x1FA60, 0x1FA6D, 0},   // Common
	{0x1FA70, 0x1FA7C, 0},   // Common
	{0x1FA80, 0x1FA8A, 0},   // Common
	{0x1FA8E, 0x1FAC6, 0},   // Common
	{0x1FAC8, 0x1FAC8, 0},   // Common
	{0x1FACD, 0x1FADC, 0},   // Common
	{0x1FADF, 0x1FAEA, 0},   // Common
	{0x1FAEF, 0x1FAF8, 0},   // Common
	{0x1FB00, 0x1FB92, 0},   // Common
	{0x1FB94, 0x1FBFA, 0},   // Common
	{0x20000, 0x2A6DF, 52},  // Han
	{0x2A700, 0x2B81D, 52},  // Han
	{0x2B820, 0x2CEAD, 52},  // Han
	{0x2CEB0, 0x2EBE0, 52},  // Han
	{0x2EBF0, 0x2EE5D, 52},  // Han
	{0x2F800, 0x2FA1D, 52},  // Han
	{0x30000, 0x3134A, 52},  // Han
	{0x31350, 0x33479, 52},  // Han
	{0xE0001, 0xE0001, 0},   // Common
	{0xE0020, 0xE007F, 0},   // Common
	{0xE0100, 0xE01EF, 1},   // Inherited
}
