// Command gengrapheme turns the Unicode Character Database into the property
// tables internal/grapheme needs to find grapheme cluster boundaries.
//
// Three files, because UAX #29's rules are keyed on three separate properties
// and no one file carries all of them:
//
//   - GraphemeBreakProperty.txt is Grapheme_Cluster_Break, which drives most of
//     the rules and every one of the Hangul ones;
//   - emoji-data.txt is Extended_Pictographic, which rule GB11 needs to tell an
//     emoji joined to another emoji from a ZWJ that happens to fall between two
//     unrelated characters;
//   - DerivedCoreProperties.txt is Indic_Conjunct_Break, which rule GB9c needs
//     to keep a consonant conjunct — a consonant, a virama and another
//     consonant — in one cluster. Its three values are not derivable from
//     Grapheme_Cluster_Break: InCB=Extend is a subset of GCB=Extend plus ZWJ,
//     and InCB=Linker is a handful of viramas that GCB calls Extend as well.
//
// The three are emitted as three tables rather than as one merged partition.
// Merging would mean one bisection per character instead of three, and it would
// also mean a table whose rows no longer correspond to anything in the database
// — a row that is wrong could not be found by looking up the character in the
// file it came from. The lookups are not on a hot path (they run only where a
// document asks to break inside a word) and the tables are checked against
// Unicode's own conformance file, so the readable arrangement wins.
//
// The generated file is committed and the input is not, exactly as cmd/genbidi
// does it: a checkout builds without a network, and regenerating is the rare
// errand of moving to a new Unicode version.
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// rng is one run of code points sharing a value.
type rng struct {
	lo, hi rune
	val    string
}

func main() {
	ucd := flag.String("ucd", "testdata/unicode", "directory holding the UCD files")
	out := flag.String("out", "internal/grapheme/tables.go", "file to write")
	version := flag.String("version", "17.0.0", "the Unicode version the files came from")
	flag.Parse()

	gcb := parse(filepath.Join(*ucd, "auxiliary", "GraphemeBreakProperty.txt"), nil)
	pict := parse(filepath.Join(*ucd, "emoji", "emoji-data.txt"),
		func(v string) bool { return v == "Extended_Pictographic" })
	incb := parseINCB(filepath.Join(*ucd, "DerivedCoreProperties.txt"))

	// A value that names nothing in the Go source is a table that would compile
	// to the wrong thing, so the mapping is checked rather than assumed.
	for _, r := range gcb {
		if _, ok := gcbConst[r.val]; !ok {
			fatalf("GraphemeBreakProperty.txt has value %q, which this generator "+
				"does not know; a new Unicode version has added a class", r.val)
		}
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, `// Code generated by cmd/gengrapheme from Unicode's GraphemeBreakProperty.txt,
// emoji-data.txt and DerivedCoreProperties.txt. DO NOT EDIT.
//
// The data is the Unicode Character Database, Unicode %s, used under the
// Unicode terms of use: https://www.unicode.org/terms_of_use.html

package grapheme

// The Unicode version these tables were generated from. The conformance test
// reads it, so a table regenerated from one release and a GraphemeBreakTest.txt
// fetched from another is a failure rather than a puzzle.
const UnicodeVersion = %q
`, *version, *version)

	emit(&b, "breakRange", "Break", gcb, gcbConst,
		fmt.Sprintf(`// breakRanges maps a character to its Grapheme_Cluster_Break, sorted by code
// point and searched by bisection.
//
// %d ranges. Other is the default and so is not listed: absence from the table
// is the answer for most of the code space and for every character in an ASCII
// document.`, len(gcb)))

	emit(&b, "pictRange", "bool", pict, nil,
		fmt.Sprintf(`// pictRanges holds Extended_Pictographic, which rule GB11 tests. %d ranges;
// membership is the whole of the property, so the ranges carry no value.`, len(pict)))

	emit(&b, "conjunctRange", "conjunct", incb, incbConst,
		fmt.Sprintf(`// conjunctRanges maps a character to its Indic_Conjunct_Break, which rule GB9c
// tests. %d ranges; None is the default and is not listed.`, len(incb)))

	if err := os.WriteFile(*out, b.Bytes(), 0o644); err != nil {
		fatalf("writing %s: %v", *out, err)
	}
	fmt.Fprintf(os.Stderr, "gengrapheme: %d break, %d pictographic, %d conjunct ranges\n",
		len(gcb), len(pict), len(incb))
}

// gcbConst names the Go constant for each Grapheme_Cluster_Break value. Other is
// the default and is never emitted.
var gcbConst = map[string]string{
	"CR": "CR", "LF": "LF", "Control": "Control", "Extend": "Extend",
	"ZWJ": "ZWJ", "Regional_Indicator": "RegionalIndicator", "Prepend": "Prepend",
	"SpacingMark": "SpacingMark", "L": "HangulL", "V": "HangulV", "T": "HangulT",
	"LV": "HangulLV", "LVT": "HangulLVT",
}

var incbConst = map[string]string{
	"Consonant": "conjunctConsonant",
	"Extend":    "conjunctExtend",
	"Linker":    "conjunctLinker",
}

// emit writes one table. names maps a UCD value to a Go constant; a nil map
// means the range carries no value and membership is the whole property.
func emit(b *bytes.Buffer, typeName, valType string, rs []rng, names map[string]string, doc string) {
	fmt.Fprintf(b, "\n// %s is one run of code points sharing a value.\ntype %s struct {\n\tlo, hi rune\n",
		typeName, typeName)
	if names != nil {
		fmt.Fprintf(b, "\tval    %s\n", valType)
	}
	fmt.Fprintf(b, "}\n\n%s\nvar %ss = [...]%s{\n", doc, typeName, typeName)
	for _, r := range rs {
		if names == nil {
			fmt.Fprintf(b, "\t{0x%04X, 0x%04X},\n", r.lo, r.hi)
			continue
		}
		fmt.Fprintf(b, "\t{0x%04X, 0x%04X, %s},\n", r.lo, r.hi, names[r.val])
	}
	fmt.Fprint(b, "}\n")
}

// parse reads a UCD file of "range ; value" lines. keep selects which values to
// take; a nil keep takes all of them.
func parse(path string, keep func(string) bool) []rng {
	f, err := os.Open(path)
	if err != nil {
		fatalf("%v", err)
	}
	defer f.Close()

	var out []rng
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		lo, hi, fields, ok := fieldsOf(sc.Text())
		if !ok || len(fields) < 2 {
			continue
		}
		val := fields[1]
		if keep != nil && !keep(val) {
			continue
		}
		out = append(out, rng{lo, hi, val})
	}
	if err := sc.Err(); err != nil {
		fatalf("reading %s: %v", path, err)
	}
	return normalise(out, path)
}

// parseINCB reads the Indic_Conjunct_Break lines out of DerivedCoreProperties,
// which is a file of many properties and states this one in three fields rather
// than two.
func parseINCB(path string) []rng {
	f, err := os.Open(path)
	if err != nil {
		fatalf("%v", err)
	}
	defer f.Close()

	var out []rng
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		lo, hi, fields, ok := fieldsOf(sc.Text())
		if !ok || len(fields) < 3 || fields[1] != "InCB" {
			continue
		}
		if _, known := incbConst[fields[2]]; !known {
			fatalf("DerivedCoreProperties.txt has InCB value %q, which this "+
				"generator does not know", fields[2])
		}
		out = append(out, rng{lo, hi, fields[2]})
	}
	if err := sc.Err(); err != nil {
		fatalf("reading %s: %v", path, err)
	}
	return normalise(out, path)
}

// fieldsOf splits one UCD line into its code point range and its fields.
func fieldsOf(line string) (lo, hi rune, fields []string, ok bool) {
	if i := strings.IndexByte(line, '#'); i >= 0 {
		line = line[:i]
	}
	if strings.TrimSpace(line) == "" {
		return 0, 0, nil, false
	}
	fields = strings.Split(line, ";")
	for i := range fields {
		fields[i] = strings.TrimSpace(fields[i])
	}
	span := fields[0]
	if i := strings.Index(span, ".."); i >= 0 {
		lo, hi = codePoint(span[:i]), codePoint(span[i+2:])
	} else {
		lo = codePoint(span)
		hi = lo
	}
	if lo > hi {
		fatalf("range %s runs backwards", span)
	}
	return lo, hi, fields, true
}

func codePoint(s string) rune {
	n, err := strconv.ParseUint(strings.TrimSpace(s), 16, 32)
	if err != nil {
		fatalf("bad code point %q: %v", s, err)
	}
	if n > 0x10FFFF {
		fatalf("code point %q is outside Unicode", s)
	}
	return rune(n)
}

// normalise sorts the ranges, refuses any that overlap, and coalesces the
// adjacent ones that share a value.
//
// The overlap check is the one that matters: two rows claiming the same
// character would make the table's answer depend on where the bisection landed,
// which is a bug that reproduces only for some inputs. A UCD property file
// should never contain one, so finding one means the file was parsed wrongly.
func normalise(rs []rng, path string) []rng {
	sort.Slice(rs, func(i, j int) bool { return rs[i].lo < rs[j].lo })
	var out []rng
	for _, r := range rs {
		if n := len(out); n > 0 {
			last := &out[n-1]
			if r.lo <= last.hi {
				fatalf("%s: %04X..%04X overlaps %04X..%04X", path, r.lo, r.hi, last.lo, last.hi)
			}
			if r.lo == last.hi+1 && r.val == last.val {
				last.hi = r.hi
				continue
			}
		}
		out = append(out, r)
	}
	return out
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gengrapheme: "+format+"\n", args...)
	os.Exit(1)
}
