// Command genindic generates the Indic syllabic and positional categories from
// Unicode's own IndicSyllabicCategory.txt and IndicPositionalCategory.txt.
//
// Text in Devanagari and its relatives is not stored in the order it is drawn:
// a vowel sign written after its consonant is drawn before it, and an initial
// Ra followed by a virama is drawn at the end of the syllable, above it. A
// shaper that is to put those glyphs where they belong has first to know what
// each character *is* — a consonant, a dependent vowel, a virama, a nukta — and
// where the mark it stands for sits relative to the letter it belongs to. Both
// are properties of the character rather than of any font, so both are
// Unicode's to state and neither is inferred here.
//
// The two files are read together because the shaper needs both facts about the
// same character and one range table carrying the pair is smaller, and quicker
// to search, than two tables searched twice.
//
// The table covers every character Unicode gives either property to, not only
// the ones the shaper acts on. That is deliberate: it is Unicode's property,
// stated whole, and the narrower question of which scripts this package
// actually reorders belongs in the shaper (see fonts/indic.go) rather than in
// the data it reads.
//
//	go run ./cmd/genindic <IndicSyllabicCategory.txt> <IndicPositionalCategory.txt> > fonts/indiccategory.go
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
	"strings"
)

// neededSyllabic and neededPositional are the property values the shaper names.
// The generator fails if the data does not have one, so a value renamed or
// withdrawn upstream is noticed here — where the table is built — rather than
// by the shaper silently classifying a character as Other and setting it in the
// wrong place.
var neededSyllabic = []string{
	"Avagraha",
	"Bindu",
	"Cantillation_Mark",
	"Consonant",
	"Consonant_Dead",
	"Consonant_Medial",
	"Consonant_Placeholder",
	"Consonant_Preceding_Repha",
	"Consonant_With_Stacker",
	"Gemination_Mark",
	"Invisible_Stacker",
	"Joiner",
	"Non_Joiner",
	"Nukta",
	"Number",
	"Pure_Killer",
	"Register_Shifter",
	"Syllable_Modifier",
	"Tone_Mark",
	"Virama",
	"Visarga",
	"Vowel",
	"Vowel_Dependent",
	"Vowel_Independent",
}

var neededPositional = []string{
	"Bottom",
	"Left",
	"Right",
	"Top",
	"Visual_Order_Left",
}

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: genindic <IndicSyllabicCategory.txt> <IndicPositionalCategory.txt>")
		os.Exit(2)
	}
	sylVersion, syllabic := readProperty(os.Args[1], "IndicSyllabicCategory-")
	posVersion, positional := readProperty(os.Args[2], "IndicPositionalCategory-")
	if sylVersion != posVersion {
		// The two properties are read as one table, so they have to describe
		// the same Unicode. Mixing versions would put a character's category
		// from one release beside its position from another.
		fmt.Fprintf(os.Stderr, "genindic: syllabic categories are Unicode %s but positional are %s\n",
			sylVersion, posVersion)
		os.Exit(1)
	}

	sylValues := valueNames(syllabic)
	posValues := valueNames(positional)
	requireAll(sylValues, neededSyllabic, "syllabic")
	requireAll(posValues, neededPositional, "positional")

	// "Other" and "Not_Applicable" are what a character no line names has, so
	// they come first and are the zero value of each type.
	sylOrder := append([]string{"Other"}, sylValues...)
	posOrder := append([]string{"Not_Applicable"}, posValues...)

	// One range table carrying both properties. A character in neither file is
	// absent, and reads as (Other, Not_Applicable).
	chars := map[rune]bool{}
	for r := range syllabic {
		chars[r] = true
	}
	for r := range positional {
		chars[r] = true
	}
	all := make([]rune, 0, len(chars))
	for r := range chars {
		all = append(all, r)
	}
	sort.Slice(all, func(i, j int) bool { return all[i] < all[j] })

	type entry struct {
		lo, hi   rune
		syl, pos string
	}
	var merged []entry
	for _, r := range all {
		s, p := syllabic[r], positional[r]
		if s == "" {
			s = "Other"
		}
		if p == "" {
			p = "Not_Applicable"
		}
		if n := len(merged); n > 0 && merged[n-1].hi+1 == r && merged[n-1].syl == s && merged[n-1].pos == p {
			merged[n-1].hi = r
			continue
		}
		merged = append(merged, entry{r, r, s, p})
	}

	// The file is written into a buffer and formatted before it is emitted, so
	// that the committed table is gofmt-clean however the generator was run.
	w := &bytes.Buffer{}
	fmt.Fprintf(w, `// Code generated by cmd/genindic from Unicode's IndicSyllabicCategory.txt
// and IndicPositionalCategory.txt. DO NOT EDIT.

package fonts

// The Indic syllabic and positional categories, from Unicode %s.
//
// A syllable in Devanagari and its relatives is stored in an order that is not
// the order it is drawn, and putting its glyphs where they belong means first
// knowing what each character is and where the mark it stands for sits. Those
// are the two properties here: what kind of thing a character is — consonant,
// dependent vowel, virama, nukta — and which side of the letter it attaches to.
//
// %d ranges cover every character Unicode gives either property to. Anything
// else is of no Indic category and in no Indic position, which is the zero
// value of each type and what every character outside these scripts reads as.
//
// The table is the whole property. Which scripts this package actually reorders
// is a narrower question, and indic.go answers it.

type indicRange struct {
	lo, hi rune
	syl    indicSyllabic
	pos    indicPosition
}

// indicSyllabic is Unicode's Indic_Syllabic_Category: what kind of thing a
// character is within a syllable.
type indicSyllabic uint8

const (
`, sylVersion, len(merged))
	for i, name := range sylOrder {
		fmt.Fprintf(w, "\tindicSyl%s indicSyllabic = %d\n", ident(name), i)
	}
	fmt.Fprint(w, `)

// indicPosition is Unicode's Indic_Positional_Category: where the mark a
// character stands for is drawn, relative to the letter it belongs to.
type indicPosition uint8

const (
`)
	for i, name := range posOrder {
		fmt.Fprintf(w, "\tindicPos%s indicPosition = %d\n", ident(name), i)
	}
	fmt.Fprint(w, `)

// indicRanges maps a character to both categories, sorted by code point.
var indicRanges = [...]indicRange{
`)
	for _, e := range merged {
		fmt.Fprintf(w, "\t{0x%04X, 0x%04X, indicSyl%s, indicPos%s},\n",
			e.lo, e.hi, ident(e.syl), ident(e.pos))
	}
	fmt.Fprintln(w, "}")

	src, err := format.Source(w.Bytes())
	if err != nil {
		fmt.Fprintln(os.Stderr, "genindic:", err)
		os.Exit(1)
	}
	if _, err := os.Stdout.Write(src); err != nil {
		fmt.Fprintln(os.Stderr, "genindic:", err)
		os.Exit(1)
	}
}

// ident turns a Unicode property value name into a Go identifier:
// Consonant_With_Stacker becomes ConsonantWithStacker.
func ident(name string) string {
	return strings.ReplaceAll(name, "_", "")
}

// readProperty parses one of the UCD's simple "range ; value" files, returning
// the Unicode version its first line declares and the value of every character
// it names.
func readProperty(path, prefix string) (string, map[rune]string) {
	f, err := os.Open(path)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	version := "unknown"
	out := map[rune]string{}
	sc := bufio.NewScanner(f)
	first := true
	for sc.Scan() {
		line := sc.Text()
		if first {
			// The first line names the file, and with it the version:
			// "# IndicSyllabicCategory-17.0.0.txt".
			first = false
			if i := strings.Index(line, prefix); i >= 0 {
				if j := strings.Index(line[i:], ".txt"); j > 0 {
					version = line[i+len(prefix) : i+j]
				}
			}
		}
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		fields := strings.Split(line, ";")
		if len(fields) < 2 {
			continue
		}
		lo, hi, ok := parseRange(strings.TrimSpace(fields[0]))
		if !ok {
			continue
		}
		value := strings.TrimSpace(fields[1])
		for r := lo; r <= hi; r++ {
			out[r] = value
		}
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if len(out) == 0 {
		fmt.Fprintf(os.Stderr, "genindic: %s named no characters\n", path)
		os.Exit(1)
	}
	return version, out
}

// parseRange reads "0041..005A" or "0041".
func parseRange(s string) (rune, rune, bool) {
	lo, hi := s, s
	if i := strings.Index(s, ".."); i >= 0 {
		lo, hi = s[:i], s[i+2:]
	}
	a, err := strconv.ParseUint(lo, 16, 32)
	if err != nil {
		return 0, 0, false
	}
	b, err := strconv.ParseUint(hi, 16, 32)
	if err != nil || b < a {
		return 0, 0, false
	}
	return rune(a), rune(b), true
}

// valueNames is every distinct value the file uses, sorted so that the emitted
// constants keep the same numbers from one run to the next.
func valueNames(m map[rune]string) []string {
	seen := map[string]bool{}
	for _, v := range m {
		seen[v] = true
	}
	out := make([]string, 0, len(seen))
	for v := range seen {
		out = append(out, v)
	}
	sort.Strings(out)
	return out
}

func requireAll(have, want []string, what string) {
	set := map[string]bool{}
	for _, v := range have {
		set[v] = true
	}
	for _, v := range want {
		if !set[v] {
			fmt.Fprintf(os.Stderr, "genindic: the shaper names the %s category %q, which the data does not have\n", what, v)
			os.Exit(1)
		}
	}
}
