//go:build devtools

// Command gensaslprep writes internal/saslprep/tables.go from the text of
// RFC 3454 (stringprep).
//
// ISO 32000-2 7.6.4.1 requires every revision-6 password to be prepared with
// the SASLprep profile (RFC 4013) of stringprep, and stringprep is defined by
// its tables: which code points are mapped to nothing, which are spaces, which
// are prohibited, which are right-to-left, which were unassigned in Unicode 3.2.
// Transcribing ~800 ranges by hand is exactly the kind of work that goes wrong
// silently, so the tables are parsed out of the RFC itself. The RFC is fetched
// from the RFC Editor and its SHA-256 checked before a single range is read, so
// the output is a deterministic function of one fixed document.
//
// TestTablesMatchPythonStringprep (internal/saslprep) cross-checks the result
// against Python's stdlib stringprep module, an independent transcription of
// the same tables, whenever python3 is available.
//
//	go run -tags devtools ./internal/cmd/gensaslprep
package main

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"regexp"
	"strconv"
	"strings"
)

const (
	rfcURL    = "https://www.rfc-editor.org/rfc/rfc3454.txt"
	rfcSHA256 = "eb722fa698fb7e8823b835d9fd263e4cdb8f1c7b0d234edf7f0e3bd2ccbb2c79"
	outFile   = "internal/saslprep/tables.go"
)

// The tables SASLprep uses (RFC 4013 §2), and the Go identifier each becomes.
var tables = []struct{ id, name, doc string }{
	{"A.1", "unassignedA1", "unassigned code points in Unicode 3.2"},
	{"B.1", "mappedToNothingB1", "commonly mapped to nothing"},
	{"C.1.2", "nonASCIISpaceC12", "non-ASCII space characters"},
	{"C.2.1", "asciiControlC21", "ASCII control characters"},
	{"C.2.2", "nonASCIIControlC22", "non-ASCII control characters"},
	{"C.3", "privateUseC3", "private use"},
	{"C.4", "nonCharacterC4", "non-character code points"},
	{"C.5", "surrogateC5", "surrogate codes"},
	{"C.6", "notPlainTextC6", "inappropriate for plain text"},
	{"C.7", "notCanonicalC7", "inappropriate for canonical representation"},
	{"C.8", "displayPropertyC8", "change display properties or are deprecated"},
	{"C.9", "taggingC9", "tagging characters"},
	{"D.1", "randALCatD1", "characters with bidirectional property R or AL"},
	{"D.2", "lCatD2", "characters with bidirectional property L"},
}

// A table row is a code point or an inclusive range, optionally followed by
// "; ..." (a mapping or a comment). Everything else inside a table — the page
// headers and footers the RFC's pagination drops in — is ignored.
var row = regexp.MustCompile(`^   ([0-9A-F]{4,6})(?:-([0-9A-F]{4,6}))?(?:;.*)?$`)

func main() {
	text, err := fetch()
	if err != nil {
		fail(err)
	}
	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by internal/cmd/gensaslprep from RFC 3454 (SHA-256 %s). DO NOT EDIT.\n\n", rfcSHA256)
	out.WriteString("package saslprep\n\n")
	for _, t := range tables {
		ranges, err := parse(text, t.id)
		if err != nil {
			fail(err)
		}
		fmt.Fprintf(&out, "// %s is RFC 3454 table %s: %s.\n", t.name, t.id, t.doc)
		fmt.Fprintf(&out, "var %s = table{\n", t.name)
		for _, r := range ranges {
			fmt.Fprintf(&out, "\t{0x%04X, 0x%04X},\n", r[0], r[1])
		}
		out.WriteString("}\n\n")
		fmt.Printf("gensaslprep: table %s: %d ranges\n", t.id, len(ranges))
	}
	src, err := format.Source(out.Bytes())
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(outFile, src, 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("gensaslprep: wrote %s\n", outFile)
}

func fetch() ([]byte, error) {
	resp, err := http.Get(rfcURL)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("GET %s: %s", rfcURL, resp.Status)
	}
	body, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return nil, err
	}
	sum := sha256.Sum256(body)
	if got := hex.EncodeToString(sum[:]); got != rfcSHA256 {
		return nil, fmt.Errorf("RFC 3454 SHA-256 is %s, want %s: refusing to generate tables from a different text", got, rfcSHA256)
	}
	return body, nil
}

// parse returns the ranges of one table, sorted and merged, failing unless the
// table is present, non-empty, and strictly ascending as printed.
func parse(text []byte, id string) ([][2]rune, error) {
	start, end := "----- Start Table "+id+" -----", "----- End Table "+id+" -----"
	var ranges [][2]rune
	in, found := false, false
	sc := bufio.NewScanner(bytes.NewReader(text))
	for sc.Scan() {
		line := strings.TrimRight(sc.Text(), " \r")
		switch strings.TrimSpace(line) {
		case start:
			in, found = true, true
			continue
		case end:
			in = false
			continue
		}
		if !in {
			continue
		}
		m := row.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		lo, err := strconv.ParseUint(m[1], 16, 32)
		if err != nil {
			return nil, err
		}
		hi := lo
		if m[2] != "" {
			if hi, err = strconv.ParseUint(m[2], 16, 32); err != nil {
				return nil, err
			}
		}
		if hi < lo || hi > 0x10FFFF {
			return nil, fmt.Errorf("table %s: bad range %s", id, line)
		}
		if n := len(ranges); n > 0 && rune(lo) <= ranges[n-1][1] {
			return nil, fmt.Errorf("table %s: %s is not ascending", id, line)
		}
		if n := len(ranges); n > 0 && rune(lo) == ranges[n-1][1]+1 {
			ranges[n-1][1] = rune(hi) // adjacent: merge
			continue
		}
		ranges = append(ranges, [2]rune{rune(lo), rune(hi)})
	}
	if !found || len(ranges) == 0 {
		return nil, fmt.Errorf("table %s not found in RFC 3454", id)
	}
	return ranges, nil
}

func fail(err error) {
	fmt.Fprintf(os.Stderr, "gensaslprep: %v\n", err)
	os.Exit(1)
}
