package render

import (
	"strings"

	"github.com/mgilbir/pdf0/html"
	"github.com/mgilbir/pdf0/style"
)

// The box tree: the fourth of §3's stages, turning a styled document into the
// boxes layout will position.
//
// It is a separate stage because the document tree and the box tree are not the
// same shape, and the places they differ are where layout goes wrong if the
// distinction is skipped. An element can produce no box, or several. A run of
// text between two block children needs a box of its own that no element
// generated. And whether a box is block-level or inline-level is a property of
// the *box*, decided by the cascade, not of the tag that produced it.
//
// # Why this is in package render rather than its own
//
// §3 sketches each stage as a package. What it actually requires is that each
// stage have "a data structure at its boundary" so §7's oracle can attach, and
// Box is that. Splitting the stages into packages would mean moving the finding
// vocabulary below them all — the box stage reports, so it cannot sit above the
// package that defines a finding — and that is a rearrangement to make on
// evidence rather than in advance.

// Outer is how a box participates in its parent's formatting context: as a
// block, as something in a line, or not at all.
type Outer uint8

const (
	// OuterNone is "display: none". The element and everything inside it
	// produce no boxes, which is different from producing an invisible one:
	// nothing inside is laid out, measured or painted.
	OuterNone Outer = iota
	// OuterBlock takes a line of its own.
	OuterBlock
	// OuterInline sits in a line with its siblings.
	OuterInline
)

func (o Outer) String() string {
	switch o {
	case OuterBlock:
		return "block"
	case OuterInline:
		return "inline"
	}
	return "none"
}

// Inner is what formatting context a box establishes for its children.
type Inner uint8

const (
	// InnerFlow is ordinary block-and-inline layout.
	InnerFlow Inner = iota
	// InnerFlowRoot is the same, but as an independent formatting context —
	// what an inline-block establishes, and what stops margins collapsing
	// through it.
	InnerFlowRoot
	// InnerFlex, InnerTable and the table-internal contexts are named here and
	// laid out later; naming them now is what lets the box tree be built once.
	InnerFlex
	InnerTable
	InnerTableRowGroup
	InnerTableRow
	InnerTableCell
	InnerTableCaption
	InnerTableColumnGroup
	InnerTableColumn
	// InnerText is a run of text, which has no children and no context.
	InnerText
)

func (i Inner) String() string {
	switch i {
	case InnerFlowRoot:
		return "flow-root"
	case InnerFlex:
		return "flex"
	case InnerTable:
		return "table"
	case InnerTableRowGroup:
		return "table-row-group"
	case InnerTableRow:
		return "table-row"
	case InnerTableCell:
		return "table-cell"
	case InnerTableCaption:
		return "table-caption"
	case InnerTableColumnGroup:
		return "table-column-group"
	case InnerTableColumn:
		return "table-column"
	case InnerText:
		return "text"
	}
	return "flow"
}

// Box is a node of the box tree.
type Box struct {
	Outer Outer
	Inner Inner

	// Element is the element that generated this box, or nil when nothing did.
	// An anonymous box has no element and no style of its own — it inherits
	// everything, which is what the specification means by anonymous.
	Element *html.Node

	// Style is the computed style of the generating element. An anonymous box
	// carries the style it inherits from, so that a consumer never has to walk
	// up looking for one.
	Style style.ComputedStyle

	// Text is the content of a text box, after white-space processing. It is
	// empty for every other kind.
	Text string

	// ListItem marks a box that generates a marker — a bullet or a number.
	ListItem bool

	Children []*Box
	Parent   *Box
}

// Anonymous reports whether a box was generated by the engine rather than by an
// element.
func (b *Box) Anonymous() bool { return b.Element == nil && b.Inner != InnerText }

// IsText reports whether a box is a run of text.
func (b *Box) IsText() bool { return b.Inner == InnerText }

// maxBoxes bounds the tree. A document is untrusted, and anonymous box
// generation can produce more boxes than there were elements, so the html
// package's node cap does not bound this on its own.
//
// It is a variable rather than a constant only so that a test can lower it.
// Building a million boxes to watch a cap fire would take longer than the rest
// of the suite put together, and a bound that is never seen to fire is one
// nobody knows works — which was found the hard way: the first test for this
// built five thousand boxes, nowhere near the cap, and passed just as happily
// with the cap removed.
var maxBoxes = 1 << 20

// BuildBoxes turns a styled document into a box tree.
//
// The root box is the one the document element generated. It is nil when the
// document produces no boxes at all, which is what "html { display: none }"
// means and is not an error.
func BuildBoxes(doc *html.Node, styles map[*html.Node]style.ComputedStyle, rec *Recorder) *Box {
	b := &boxBuilder{styles: styles, rec: rec}
	root := documentElementOf(doc)
	if root == nil {
		return nil
	}
	box := b.build(root, nil)
	if box == nil {
		return nil
	}
	// Anonymous boxes are added after the whole tree exists, because the rule
	// that generates them is about a box's *set* of children — a block child
	// anywhere makes every inline run a candidate — and that set is not known
	// while the children are still being made.
	b.fixup(box)
	return box
}

func documentElementOf(doc *html.Node) *html.Node {
	if doc == nil {
		return nil
	}
	if doc.Type == html.ElementNode {
		return doc
	}
	for _, c := range doc.Children {
		if c.Type == html.ElementNode {
			return c
		}
	}
	return nil
}

type boxBuilder struct {
	styles map[*html.Node]style.ComputedStyle
	rec    *Recorder
	count  int
	// stopped records that the box cap was reached, so it is reported once
	// rather than per box.
	stopped bool
}

// build makes the box or boxes for one node, or nil for none.
func (b *boxBuilder) build(n *html.Node, inherited style.ComputedStyle) *Box {
	switch n.Type {
	case html.TextNode:
		return b.textBox(n, inherited)
	case html.ElementNode:
		return b.elementBox(n)
	}
	return nil
}

func (b *boxBuilder) elementBox(n *html.Node) *Box {
	cs := b.styles[n]
	outer, inner, listItem := displayOf(cs)
	if outer == OuterNone {
		// Nothing inside is laid out either, which is the difference between
		// display:none and visibility:hidden.
		return nil
	}
	if !b.room(n) {
		return nil
	}

	box := &Box{Outer: outer, Inner: inner, Element: n, Style: cs, ListItem: listItem}
	for _, child := range n.Children {
		if c := b.build(child, cs); c != nil {
			c.Parent = box
			box.Children = append(box.Children, c)
		}
	}
	return box
}

// room reports whether another box may be made.
func (b *boxBuilder) room(n *html.Node) bool {
	if b.count >= maxBoxes {
		if !b.stopped {
			b.stopped = true
			b.rec.Report(RuleLimit, AtHTML(n.Offset),
				"the document produces more boxes than this engine will build; "+
					"the rest of it was not laid out")
		}
		return false
	}
	b.count++
	return true
}

// textBox makes a text box, applying white-space processing.
//
// Text whose content collapses to nothing produces no box. That is not an
// optimisation: an empty text box between two blocks would make the parent a
// block container with inline content, and so generate an anonymous block that
// occupies a line.
func (b *boxBuilder) textBox(n *html.Node, inherited style.ComputedStyle) *Box {
	text := collapseWhitespace(n.Text, inherited["white-space"])
	if text == "" {
		return nil
	}
	if !b.room(n) {
		return nil
	}
	return &Box{
		Outer: OuterInline, Inner: InnerText,
		Style: inherited, Text: text,
	}
}

// collapseWhitespace applies the white-space property to a run of text.
//
// The rules are CSS Text §4. What is done here is the part that does not need a
// line: sequences of white space become one space, or are preserved. Removing
// the space at the two ends of a *line* is line layout's job, because where a
// line ends is not known yet.
func collapseWhitespace(text, whiteSpace string) string {
	switch strings.ToLower(whiteSpace) {
	case "pre", "pre-wrap", "break-spaces":
		// Preserved entirely, newlines included.
		return text
	case "pre-line":
		// Spaces and tabs collapse; newlines survive, because pre-line exists
		// precisely to keep them.
		return collapseRuns(text, true)
	default:
		// normal and nowrap. They differ in whether a line may break at a
		// space, not in how the spaces themselves collapse, so both are here.
		return collapseRuns(text, false)
	}
}

// collapseRuns turns each run of white space into a single space, or into a
// newline when keepNewlines is set and the run held one.
func collapseRuns(text string, keepNewlines bool) string {
	var out strings.Builder
	out.Grow(len(text))

	inRun, runHadNewline := false, false
	flush := func() {
		if !inRun {
			return
		}
		if keepNewlines && runHadNewline {
			out.WriteByte('\n')
		} else {
			out.WriteByte(' ')
		}
		inRun, runHadNewline = false, false
	}

	for i := 0; i < len(text); i++ {
		c := text[i]
		if isCollapsibleSpace(c) {
			inRun = true
			if c == '\n' || c == '\r' {
				runHadNewline = true
			}
			continue
		}
		flush()
		out.WriteByte(c)
	}
	flush()
	return out.String()
}

// isCollapsibleSpace is the set CSS Text calls "document white space". A
// no-break space is deliberately absent: it is not white space for this purpose,
// which is the whole reason an author writes one.
func isCollapsibleSpace(c byte) bool {
	return c == ' ' || c == '\t' || c == '\n' || c == '\r' || c == '\f'
}

// displayOf reads the display property into the outer/inner pair.
//
// CSS now defines display as two values — how a box behaves in its parent, and
// what context it makes for its children — and the single keywords are
// shorthands for pairs. Modelling it as the pair is what makes "inline-block"
// stop being a special case: it is simply inline outside and flow-root inside.
func displayOf(cs style.ComputedStyle) (Outer, Inner, bool) {
	value := strings.ToLower(strings.TrimSpace(cs["display"]))

	// The two-value syntax, "inline flow-root" and friends.
	if outer, inner, ok := twoValueDisplay(value); ok {
		return outer, inner, false
	}

	switch value {
	case "none":
		return OuterNone, InnerFlow, false
	case "block", "flow-root":
		inner := InnerFlow
		if value == "flow-root" {
			inner = InnerFlowRoot
		}
		return OuterBlock, inner, false
	case "inline":
		return OuterInline, InnerFlow, false
	case "inline-block":
		return OuterInline, InnerFlowRoot, false
	case "list-item":
		return OuterBlock, InnerFlow, true
	case "flex":
		return OuterBlock, InnerFlex, false
	case "inline-flex":
		return OuterInline, InnerFlex, false
	case "table":
		return OuterBlock, InnerTable, false
	case "inline-table":
		return OuterInline, InnerTable, false
	case "table-row-group":
		return OuterBlock, InnerTableRowGroup, false
	case "table-header-group":
		return OuterBlock, InnerTableRowGroup, false
	case "table-footer-group":
		return OuterBlock, InnerTableRowGroup, false
	case "table-row":
		return OuterBlock, InnerTableRow, false
	case "table-cell":
		return OuterBlock, InnerTableCell, false
	case "table-caption":
		return OuterBlock, InnerTableCaption, false
	case "table-column-group":
		return OuterBlock, InnerTableColumnGroup, false
	case "table-column":
		return OuterBlock, InnerTableColumn, false
	case "contents":
		// "display: contents" replaces the element with its children. It is not
		// implemented, and the closest available answer — treating it as inline
		// — is wrong in a way that shows: the element's own box would take part
		// in layout when the author asked for it not to. Treated as inline and
		// reported by the caller.
		return OuterInline, InnerFlow, false
	}
	// An unrecognised value: the initial one, which is what the cascade would
	// have used had the declaration been invalid.
	return OuterInline, InnerFlow, false
}

// twoValueDisplay reads the "outer inner" form.
func twoValueDisplay(value string) (Outer, Inner, bool) {
	parts := strings.Fields(value)
	if len(parts) != 2 {
		return 0, 0, false
	}
	var outer Outer
	switch parts[0] {
	case "block":
		outer = OuterBlock
	case "inline":
		outer = OuterInline
	default:
		return 0, 0, false
	}
	var inner Inner
	switch parts[1] {
	case "flow":
		inner = InnerFlow
	case "flow-root":
		inner = InnerFlowRoot
	case "flex":
		inner = InnerFlex
	case "table":
		inner = InnerTable
	default:
		return 0, 0, false
	}
	return outer, inner, true
}

// fixup adds the anonymous boxes the specification requires, depth first so a
// parent sees children that are already settled.
func (b *boxBuilder) fixup(box *Box) {
	for _, c := range box.Children {
		b.fixup(c)
	}
	box.Children = b.wrapInlines(box)
}

// wrapInlines is the anonymous block box rule of CSS Display §2.1: when a block
// container has any block-level child, every run of inline-level children is
// wrapped in an anonymous block box.
//
// Without it a block container would have two kinds of child and layout would
// have to handle a mixture at every step. With it, a block container's children
// are either all block-level or all inline-level, which is the invariant the
// whole of block layout is written against.
func (b *boxBuilder) wrapInlines(parent *Box) []*Box {
	if len(parent.Children) == 0 {
		return parent.Children
	}
	// The rule applies to block containers. A box that establishes some other
	// context — a flex container, a table — has its own rules for what its
	// children become, and those arrive with those layouts.
	if parent.Inner != InnerFlow && parent.Inner != InnerFlowRoot {
		return parent.Children
	}

	hasBlock := false
	for _, c := range parent.Children {
		if c.Outer == OuterBlock {
			hasBlock = true
			break
		}
	}
	if !hasBlock {
		// All inline: the parent is an inline formatting context and no
		// anonymous box is needed.
		return parent.Children
	}

	var out []*Box
	var run []*Box
	flush := func() {
		if len(run) == 0 {
			return
		}
		// A run that is nothing but collapsible white space generates no
		// anonymous box. Otherwise "<div>\n<p>a</p>\n</div>" — whose newlines
		// are text nodes — would gain two anonymous blocks and two blank lines
		// that the author did not write and cannot see in the markup.
		if allWhitespace(run) {
			run = nil
			return
		}
		anon := &Box{
			Outer: OuterBlock, Inner: InnerFlow,
			Style: parent.Style, Parent: parent,
			Children: run,
		}
		for _, c := range run {
			c.Parent = anon
		}
		out = append(out, anon)
		run = nil
	}

	for _, c := range parent.Children {
		if c.Outer == OuterBlock {
			flush()
			out = append(out, c)
			continue
		}
		run = append(run, c)
	}
	flush()
	return out
}

// allWhitespace reports whether a run of inline boxes is nothing but
// collapsible white space.
func allWhitespace(run []*Box) bool {
	for _, c := range run {
		if !c.IsText() {
			return false
		}
		if strings.TrimSpace(c.Text) != "" {
			return false
		}
	}
	return true
}
