package render

import (
	"strconv"
	"strings"
	"testing"

	"github.com/mgilbir/pdf0/fonts"
	"github.com/mgilbir/pdf0/style"
)

// Form controls as static boxes: what is on the page, what is bounded, and what
// is reported.
//
// The reftests are a weak guard here and are honest about it — both documents of
// a pair are rendered by this engine, and the suite has almost no control in it —
// so these are the primary evidence. Each of them was watched to fail with the
// rule it pins removed.

// controlBuild builds a document and hands back the tree, the boxes and the
// findings, which is what nearly every case below wants.
func controlBuild(t *testing.T, htmlSrc string, cssSrc ...string) Built {
	t.Helper()
	in := Input{HTML: htmlSrc}
	for _, c := range cssSrc {
		in.CSS = append(in.CSS, Stylesheet{Source: c})
	}
	return Build(in)
}

// boxFor finds the first box generated by an element of the given name.
func boxFor(root *Box, name string) *Box {
	if root == nil {
		return nil
	}
	if root.Element != nil && strings.EqualFold(root.Element.Name, name) {
		return root
	}
	for _, c := range root.Children {
		if got := boxFor(c, name); got != nil {
			return got
		}
	}
	return nil
}

// textIn collects the text of every text box in a subtree, in order.
func textIn(b *Box) string {
	if b == nil {
		return ""
	}
	if b.IsText() {
		return b.Text
	}
	var out strings.Builder
	for _, c := range b.Children {
		out.WriteString(textIn(c))
	}
	return out.String()
}

func findingsWith(fs []Finding, rule Rule) []Finding {
	var out []Finding
	for _, f := range fs {
		if f.Rule == rule {
			out = append(out, f)
		}
	}
	return out
}

// TestControlsAreLaidOutAsStaticBoxes is the headline of this change: a control
// is a box on the page, and the content the markup gave it is on the page too.
//
// It is written as "there is a box and the text is in it" rather than as
// geometry on purpose. The geometry is pinned below, one rule at a time; what
// this holds is the boundary that moved — that none of these elements vanishes
// any more, which is what dropping them did and is the fault being fixed.
func TestControlsAreLaidOutAsStaticBoxes(t *testing.T) {
	cases := []struct {
		name, elem, markup, want string
	}{
		{"textarea", "textarea", `<textarea>words here</textarea>`, "words here"},
		{"input", "input", `<input value="typed">`, "typed"},
		{"submit", "input", `<input type=submit value="Send">`, "Send"},
		{"submit-default", "input", `<input type=submit>`, "Submit"},
		{"reset-default", "input", `<input type=reset>`, "Reset"},
		{"button", "button", `<button>press</button>`, "press"},
		{"select", "select", `<select><option>only</option></select>`, "only"},
		{"label", "label", `<label>name</label>`, "name"},
		{"fieldset", "fieldset", `<fieldset><legend>who</legend>rest</fieldset>`, "whorest"},
		{"form", "form", `<form>inside</form>`, "inside"},
	}
	for _, tc := range cases {
		built := controlBuild(t, "<body>"+tc.markup+"</body>")
		box := boxFor(built.Root, tc.elem)
		if box == nil {
			t.Errorf("%s: no box was generated:\n%v", tc.name, built.Findings)
			continue
		}
		if got := textIn(box); got != tc.want {
			t.Errorf("%s: the box holds %q, want %q", tc.name, got, tc.want)
		}
		// And none of it is reported as an element this engine does not lay out,
		// which is what it used to be.
		for _, f := range built.Findings {
			if f.Rule == RuleUnsupportedElement && strings.Contains(f.Message, "<"+tc.elem+">") {
				t.Errorf("%s: still reported as unsupported: %s", tc.name, f.Error())
			}
		}
	}
}

// TestControlsAreNotInteractiveAndMakeNoFormField pins the boundary that did
// *not* move.
//
// The reason the controls used to be dropped was interactivity, and narrowing
// that reason to layout is the whole of this change — so the part of it that is
// still true has to be checked rather than asserted in a comment. Nothing here
// produces a PDF form field: the box tree has no such notion at all, and this is
// the test that would fail the day somebody adds one to it by accident.
func TestControlsAreNotInteractiveAndMakeNoFormField(t *testing.T) {
	built := controlBuild(t, `<form action="/x" method=post>
		<input name=a value=v><button type=submit>go</button></form>`)
	// A control is an ordinary box, told apart only by where its size comes
	// from. If one ever grows an annotation, an action or a field name, this is
	// where that has to be justified.
	var walk func(*Box)
	walk = func(b *Box) {
		if b == nil {
			return
		}
		if b.Control != nil {
			switch b.Control.Kind {
			case controlField, controlButton, controlTextArea, controlSelect,
				controlToggle, controlWidget:
			default:
				t.Errorf("a control has kind %d, which nothing produces", b.Control.Kind)
			}
		}
		for _, c := range b.Children {
			walk(c)
		}
	}
	walk(built.Root)

	// The action and the method are attributes that mean nothing here, and
	// nothing must be reported about them either: an author is not owed a
	// warning that their form will not submit from a PDF.
	for _, f := range built.Findings {
		if strings.Contains(f.Message, "/x") || strings.Contains(f.Message, "post") {
			t.Errorf("a form's submission attributes produced a finding: %s", f.Error())
		}
	}
}

// TestTextareaIntrinsicSizeFromColsAndRows pins HTML's sizing: a textarea is
// cols characters wide and rows lines tall, in the element's own font.
//
// The numbers are arithmetic rather than measurements from this engine: the
// content width must be exactly cols times the advance of "0", and the content
// height exactly rows times the line height. A monospaced face is used so that
// the advance is a number the test can restate.
func TestTextareaIntrinsicSizeFromColsAndRows(t *testing.T) {
	const css = `
html, body { margin: 0; padding: 0 }
textarea { font-family: monospace; font-size: 20px; line-height: 25px;
  margin: 0; padding: 0; border: none }
`
	set := StandardFonts()
	zero := zeroAdvanceOf(t, set, "monospace", 20)

	for _, tc := range []struct {
		name       string
		markup     string
		cols, rows float64
	}{
		{"defaults", `<textarea id=x></textarea>`, 20, 2},
		{"declared", `<textarea id=x cols=7 rows=5></textarea>`, 7, 5},
		// HTML's cols and rows are "limited to only positive numbers", so zero
		// is invalid and the default applies. Zero and unset are the *same*
		// control, and an engine that read the attribute as a plain integer
		// would produce a box of no width that no browser produces.
		{"zero", `<textarea id=x cols=0 rows=0></textarea>`, 20, 2},
		{"negative", `<textarea id=x cols=-4 rows=-1></textarea>`, 20, 2},
		{"not a number", `<textarea id=x cols=wide rows=tall></textarea>`, 20, 2},
	} {
		root := layoutWithFonts(t, set, tc.markup, css)
		f := find(t, root, "x")
		wantW := zero.Mul(tc.cols)
		wantH := mustPx(25).Mul(tc.rows)
		if got := f.ContentRect().W; got != wantW {
			t.Errorf("%s: content width %v, want %v (%v cols of %v)",
				tc.name, got, wantW, tc.cols, zero)
		}
		if got := f.ContentRect().H; got != wantH {
			t.Errorf("%s: content height %v, want %v (%v rows of 25px)",
				tc.name, got, wantH, tc.rows)
		}
	}
}

// TestDeclaredSizeBeatsTheIntrinsicOne pins that the intrinsic size is what
// "auto" means and not a floor.
//
// It matters because the two readings differ on every styled document in the
// world: a stylesheet saying "textarea { width: 100% }" must get a full-width
// control, and an engine that treated cols as a minimum would give it one twenty
// characters wide inside a narrow column.
func TestDeclaredSizeBeatsTheIntrinsicOne(t *testing.T) {
	const css = `
html, body { margin: 0; padding: 0 }
textarea { font-family: monospace; font-size: 20px; margin: 0; padding: 0;
  border: none; width: 33px; height: 44px }
`
	root := layoutWithFonts(t, StandardFonts(), `<textarea id=x cols=80 rows=40></textarea>`, css)
	f := find(t, root, "x")
	if got, want := f.ContentRect().W, mustPx(33); got != want {
		t.Errorf("a declared width lost to cols: %v, want %v", got, want)
	}
	if got, want := f.ContentRect().H, mustPx(44); got != want {
		t.Errorf("a declared height lost to rows: %v, want %v", got, want)
	}
}

// TestInputSizeGivesAnIntrinsicWidth pins the other half of the same rule, and
// pins it on a *block-level* input.
//
// "display: block" on an ordinary box means "fill the containing block". On a
// control it does not: the control has an intrinsic width, exactly as a replaced
// element does, so it stays size characters wide inside a wide parent. That is
// what browsers produce and it is what css/CSS2/normal-flow/blocks-026 is about.
func TestInputSizeGivesAnIntrinsicWidth(t *testing.T) {
	const css = `
html, body { margin: 0; padding: 0 }
input { font-family: monospace; font-size: 20px; margin: 0; padding: 0;
  border: none; display: block }
`
	set := StandardFonts()
	zero := zeroAdvanceOf(t, set, "monospace", 20)

	root := layoutWithFonts(t, set, `<input id=x size=6>`, css)
	if got, want := find(t, root, "x").ContentRect().W, zero.Mul(6); got != want {
		t.Errorf("a block-level input is %v wide, want %v — it filled its parent "+
			"instead of taking its intrinsic width", got, want)
	}
	// And the default is twenty, which is HTML's.
	root = layoutWithFonts(t, set, `<input id=x>`, css)
	if got, want := find(t, root, "x").ContentRect().W, zero.Mul(20); got != want {
		t.Errorf("an input with no size is %v wide, want %v", got, want)
	}
}

// TestControlAttributesAreClamped is the security bound. cols, rows and size are
// integers in untrusted markup, and each multiplies a font metric.
//
// The clamp is checked by watching it *decide*: the control comes out at the
// limit and not at the number the document asked for, and the limit is reported.
// A bound nobody has seen fire is decoration.
func TestControlAttributesAreClamped(t *testing.T) {
	const css = `
html, body { margin: 0; padding: 0 }
textarea { font-family: monospace; font-size: 20px; line-height: 20px;
  margin: 0; padding: 0; border: none }
`
	set := StandardFonts()
	zero := zeroAdvanceOf(t, set, "monospace", 20)

	built := controlBuild(t, `<textarea id=x cols=2000000000 rows=1999999999></textarea>`,
		css)
	rec := NewRecorder(nil)
	w, _ := style.FromPx(600)
	h, _ := style.FromPx(10000)
	root := Layout(built.Root, Size{W: w, H: h}, set, rec)

	f := find(t, root, "x")
	if got, want := f.ContentRect().W, zero.Mul(maxControlChars); got != want {
		t.Errorf("cols=2000000000 gave a content width of %v, want the clamp at %v", got, want)
	}
	if got, want := f.ContentRect().H, mustPx(20).Mul(maxControlLines); got != want {
		t.Errorf("rows=1999999999 gave a content height of %v, want the clamp at %v", got, want)
	}

	limits := findingsWith(built.Findings, RuleLimit)
	var cols, rows bool
	for _, l := range limits {
		if strings.Contains(l.Message, "cols") {
			cols = true
		}
		if strings.Contains(l.Message, "rows") {
			rows = true
		}
	}
	if !cols || !rows {
		t.Errorf("the clamp was silent: %v", built.Findings)
	}

	// The same bound on an input's size, which is a separate attribute read by
	// the same function — and one the test would not notice if only cols were
	// checked.
	built = controlBuild(t, `<input size=123456789>`)
	if len(findingsWith(built.Findings, RuleLimit)) == 0 {
		t.Errorf("an input with size=123456789 clamped silently: %v", built.Findings)
	}
}

// TestControlValueIsBounded bounds what one control draws.
//
// The value attribute is untrusted and is bounded only by the document, which is
// megabytes. This is not a general bound on text — every other run in the
// document is set at the length it has — it is a bound on what a single control
// contributes, and it is reported when it decides.
func TestControlValueIsBounded(t *testing.T) {
	long := strings.Repeat("x", maxLabelRunes+500)
	built := controlBuild(t, `<input value="`+long+`">`)
	box := boxFor(built.Root, "input")
	if box == nil {
		t.Fatal("no input box")
	}
	if got := len(textIn(box)); got != maxLabelRunes {
		t.Errorf("the value was drawn at %d characters, want the cut at %d", got, maxLabelRunes)
	}
	if len(findingsWith(built.Findings, RuleLimit)) == 0 {
		t.Errorf("the value was cut silently: %v", built.Findings)
	}
}

// TestPasswordValueIsMasked pins the one rule here that is not about layout.
//
// A page that printed a password's value would be a page that leaked it: the
// markup is untrusted, the PDF is not private, and a value that was hidden on
// the screen it came from must not become plain text on paper. Every user agent
// masks it, so this is the faithful rendering as well as the safe one.
func TestPasswordValueIsMasked(t *testing.T) {
	built := controlBuild(t, `<input type=password value="hunter2">`)
	box := boxFor(built.Root, "input")
	if box == nil {
		t.Fatal("no input box")
	}
	got := textIn(box)
	if strings.Contains(got, "hunter2") {
		t.Fatalf("a password's value reached the page as %q", got)
	}
	if want := strings.Repeat("•", len("hunter2")); got != want {
		t.Errorf("the mask is %q, want %q", got, want)
	}
	// In characters and not in bytes, so a multi-byte password is not masked to
	// three times its length — which would say how long it was.
	built = controlBuild(t, `<input type=password value="ünïcø">`)
	if got, want := textIn(boxFor(built.Root, "input")), strings.Repeat("•", 5); got != want {
		t.Errorf("a five-character password masked to %q, want %q", got, want)
	}
}

// TestHiddenInputGeneratesNoBox pins the one input type that is not on the page
// at all. A hidden field drawn as an empty box would put a rectangle in the
// middle of a form that a browser shows nothing for.
func TestHiddenInputGeneratesNoBox(t *testing.T) {
	built := controlBuild(t, `<p>a<input type=hidden name=t value=v>b</p>`)
	if boxFor(built.Root, "input") != nil {
		t.Error("a hidden input generated a box")
	}
	if got := textIn(built.Root); !strings.Contains(got, "ab") {
		t.Errorf("the text around it is %q", got)
	}
}

// TestSelectShowsOnlyItsSelectedOption pins what a drop-down is on paper.
//
// A browser shows one row; the others exist and are not visible. Laying out all
// of them would produce a tall list nothing on screen or on paper resembles, and
// laying out none would lose the label — so it is the selected one, and the
// options that are not on the page are reported rather than dropped in silence.
func TestSelectShowsOnlyItsSelectedOption(t *testing.T) {
	const markup = `<select id=x>
		<option>first</option>
		<option selected>second</option>
		<option>third</option>
	</select>`
	built := controlBuild(t, markup)
	box := boxFor(built.Root, "select")
	if box == nil {
		t.Fatal("no select box")
	}
	if got := strings.TrimSpace(textIn(box)); got != "second" {
		t.Errorf("the drop-down shows %q, want %q", got, "second")
	}
	approx := findingsWith(built.Findings, RuleControlApproximated)
	if len(approx) == 0 {
		t.Fatalf("the two hidden options were not reported: %v", built.Findings)
	}
	if !strings.Contains(approx[0].Message, "2") {
		t.Errorf("the report does not say how many are missing: %s", approx[0].Message)
	}

	// With nothing selected the first option is the selected one, which is
	// HTML's rule and is what makes an ordinary drop-down show its first entry
	// rather than nothing.
	built = controlBuild(t, `<select><option>alpha</option><option>beta</option></select>`)
	if got := strings.TrimSpace(textIn(boxFor(built.Root, "select"))); got != "alpha" {
		t.Errorf("a select with nothing selected shows %q, want %q", got, "alpha")
	}

	// A single-option drop-down hides nothing, so it says nothing. A rule that
	// fired on every select would be one nobody reads.
	built = controlBuild(t, `<select><option>only</option></select>`)
	if got := findingsWith(built.Findings, RuleControlApproximated); len(got) != 0 {
		t.Errorf("a drop-down hiding nothing was reported: %v", got)
	}

	// A list box shows its rows, so every option is laid out.
	built = controlBuild(t, `<select size=3><option>a</option><option>b</option></select>`)
	if got := textIn(boxFor(built.Root, "select")); !strings.Contains(got, "a") ||
		!strings.Contains(got, "b") {
		t.Errorf("a list box shows %q, want both options", got)
	}
}

// TestSelectedOptionIsTheLastOneNamed pins HTML's selectedness where markup
// names two, which is the rule as written rather than the one an implementation
// reaches for first.
func TestSelectedOptionIsTheLastOneNamed(t *testing.T) {
	built := controlBuild(t,
		`<select><option selected>one</option><option selected>two</option></select>`)
	if got := strings.TrimSpace(textIn(boxFor(built.Root, "select"))); got != "two" {
		t.Errorf("with two options selected the drop-down shows %q, want %q", got, "two")
	}
}

// TestSelectedOptionInsideAnOptgroup pins that the chosen option is found
// through a group, and that the group's other options still go.
func TestSelectedOptionInsideAnOptgroup(t *testing.T) {
	built := controlBuild(t, `<select>
		<optgroup label=g1><option>a</option></optgroup>
		<optgroup label=g2><option selected>b</option><option>c</option></optgroup>
	</select>`)
	got := strings.Join(strings.Fields(textIn(boxFor(built.Root, "select"))), " ")
	if got != "b" {
		t.Errorf("the drop-down shows %q, want %q", got, "b")
	}
}

// TestApproximatedControlsAreReported pins the finding that says a box is
// standing in for a widget, and — as importantly — pins where it does *not*
// fire. A rule that fired on every control would be noise, and noise is how a
// report stops being read.
func TestApproximatedControlsAreReported(t *testing.T) {
	quiet := []string{
		`<input type=text value=x>`,
		`<input type=password value=x>`,
		`<input type=submit value=go>`,
		`<button>go</button>`,
		`<textarea>words</textarea>`,
		`<input type=checkbox>`,
		`<input type=radio>`,
	}
	for _, markup := range quiet {
		built := controlBuild(t, markup)
		if got := findingsWith(built.Findings, RuleControlApproximated); len(got) != 0 {
			t.Errorf("%s was reported as approximated: %s", markup, got[0].Error())
		}
	}

	loud := []string{
		`<input type=file>`,
		`<input type=range>`,
		`<input type=color>`,
		`<input type=image src=x.png>`,
		// A checked box is drawn as an empty square, and the mark inside it is
		// the thing that cannot be drawn — so the state is what makes this
		// report, not the element.
		`<input type=checkbox checked>`,
		`<input type=radio checked>`,
	}
	for _, markup := range loud {
		built := controlBuild(t, markup)
		if got := findingsWith(built.Findings, RuleControlApproximated); len(got) == 0 {
			t.Errorf("%s was drawn as a plain box and said nothing: %v", markup, built.Findings)
			continue
		}
		fired[RuleControlApproximated] = true
	}
}

// TestToggleIsAFixedSquare pins that a checkbox is the same small square
// whatever is around it, which is what makes a row of them line up.
func TestToggleIsAFixedSquare(t *testing.T) {
	const css = `html, body { margin: 0; padding: 0 } input { margin: 0 }`
	for _, markup := range []string{`<input id=x type=checkbox>`, `<input id=x type=radio>`} {
		root := layoutWithFonts(t, StandardFonts(), markup, css)
		f := find(t, root, "x")
		if got, want := f.BorderRect.W, mustPx(13); got != want {
			t.Errorf("%s is %v wide, want %v", markup, got, want)
		}
		if got, want := f.BorderRect.H, mustPx(13); got != want {
			t.Errorf("%s is %v tall, want %v", markup, got, want)
		}
	}
}

// TestListBoxIsAsTallAsItsRows pins the height half of a select: a drop-down is
// one row whatever is in it, and a list box is as many as its size says — four
// when "multiple" is written without one, which is HTML's default.
//
// It is the height and not the content, and those differ: a list box showing
// three rows may hold thirty options, and the other twenty-seven are below the
// edge of a box nothing here can scroll. That is what the finding beside it is
// for.
func TestListBoxIsAsTallAsItsRows(t *testing.T) {
	const css = `
html, body { margin: 0; padding: 0 }
select { font-family: monospace; font-size: 20px; line-height: 30px;
  margin: 0; padding: 0; border: none }
`
	for _, tc := range []struct {
		name, markup string
		rows         float64
	}{
		{"drop-down", `<select id=x><option>a</option><option>b</option></select>`, 1},
		{"sized", `<select id=x size=3><option>a</option></select>`, 3},
		{"multiple", `<select id=x multiple><option>a</option></select>`, 4},
		// size=1 without "multiple" is still a drop-down, which is HTML's rule
		// and is the case an implementation reading the attribute as a row count
		// gets right by accident and size=0 gets wrong.
		{"size one", `<select id=x size=1><option>a</option></select>`, 1},
		{"size zero", `<select id=x size=0><option>a</option></select>`, 1},
	} {
		root := layoutWithFonts(t, StandardFonts(), tc.markup, css)
		if got, want := find(t, root, "x").ContentRect().H, mustPx(30).Mul(tc.rows); got != want {
			t.Errorf("%s: content height %v, want %v (%v rows of 30px)",
				tc.name, got, want, tc.rows)
		}
	}
}

// emptyFontSet has no faces at all, which is what a caller supplying its own set
// for a document in one script can hand this engine.
type emptyFontSet struct{}

func (emptyFontSet) Face(string, bool, bool) (*fonts.Face, bool) { return nil, false }

// TestControlWidthWithoutAFace pins the fallback in controlIntrinsicWidth, which
// would otherwise be a clause nothing has ever seen decide.
//
// A "ch" is the advance of "0" and there is nothing to measure when no face
// could be chosen. The answer must not be zero: a control of no width is the one
// result that is silently wrong — the page looks finished and the field is not
// on it. Half an em per character is the same stand-in CSS Values gives "ex" for
// a face that states no x-height.
func TestControlWidthWithoutAFace(t *testing.T) {
	built := Build(Input{HTML: `<textarea id=x cols=10></textarea>`, CSS: []Stylesheet{{
		Source: `html, body { margin: 0; padding: 0 }
		         textarea { font-size: 20px; margin: 0; padding: 0; border: none }`}}})
	rec := NewRecorder(nil)
	w, _ := style.FromPx(600)
	h, _ := style.FromPx(10000)
	root := Layout(built.Root, Size{W: w, H: h}, emptyFontSet{}, rec)

	if got, want := find(t, root, "x").ContentRect().W, mustPx(10*20/2.0); got != want {
		t.Errorf("with no face at all the control is %v wide, want %v", got, want)
	}
}

// TestObjectKeepsItsFallbackContent pins what replaced dropping the element.
//
// HTML says an object whose data cannot be used is represented by its children,
// and this engine can never use an object's data — so the children are always
// what is on the page. Dropping the element threw away markup an author wrote
// precisely for this case.
func TestObjectKeepsItsFallbackContent(t *testing.T) {
	built := controlBuild(t,
		`<object data="chart.svg" type="image/svg+xml">Quarterly <em>figures</em></object>`)
	box := boxFor(built.Root, "object")
	if box == nil {
		t.Fatalf("the object generated no box: %v", built.Findings)
	}
	if got := textIn(box); got != "Quarterly figures" {
		t.Errorf("the fallback content is %q, want %q", got, "Quarterly figures")
	}

	// Block fallback content survives too, and reaches the page through the
	// ordinary block-in-inline split rather than through anything of its own —
	// which is why this is checked from the root: an inline <object> holding
	// only a block leaves no box of its own for the block to hang from.
	built = controlBuild(t, `<object data="chart.svg"><p>Quarterly figures</p></object>`)
	if got := textIn(built.Root); !strings.Contains(got, "Quarterly figures") {
		t.Errorf("block fallback content was lost; the page holds %q", got)
	}
}

// TestObjectReportsItsBlockedData pins the other half: the page is showing an
// author's second choice, and a caller has to be able to know that rather than
// infer it from a paragraph reading "your browser cannot show this".
func TestObjectReportsItsBlockedData(t *testing.T) {
	built := controlBuild(t, `<object data="chart.svg">fallback</object>`)
	blocked := findingsWith(built.Findings, RuleResourceBlocked)
	if len(blocked) == 0 {
		t.Fatalf("an object's data was dropped silently: %v", built.Findings)
	}
	if !strings.Contains(blocked[0].Message, "chart.svg") {
		t.Errorf("the report does not name the resource: %s", blocked[0].Message)
	}
	// And nothing is fetched for it. The resolver here would answer, and must
	// not be asked: an <object> is not a second loading path.
	if !strings.Contains(blocked[0].Message, "embeds no objects") {
		t.Errorf("the report does not say that nothing was embedded: %s", blocked[0].Message)
	}

	// An object naming nothing has nothing to have failed, so it says nothing:
	// it is a box holding its children and always was.
	built = controlBuild(t, `<object>just markup</object>`)
	if got := findingsWith(built.Findings, RuleResourceBlocked); len(got) != 0 {
		t.Errorf("an object with no data reported %s", got[0].Error())
	}
}

// TestParamGeneratesNoBox pins the element that comes with <object> and puts
// nothing on the page. Reporting it as unknown, which is what it used to get,
// would be a false alarm on markup that is correct and invisible.
func TestParamGeneratesNoBox(t *testing.T) {
	built := controlBuild(t, `<object data=x><param name=a value=b>fallback</object>`)
	if boxFor(built.Root, "param") != nil {
		t.Error("a <param> generated a box")
	}
	for _, f := range built.Findings {
		if f.Rule == RuleUnsupportedElement && strings.Contains(f.Message, "param") {
			t.Errorf("<param> was reported: %s", f.Error())
		}
	}
}

// TestTextareaPreservesItsWhiteSpace pins the UA declaration that changes what
// the text says rather than how it looks. A textarea is "white-space: pre-wrap",
// so the spaces and the line breaks in it are the author's.
func TestTextareaPreservesItsWhiteSpace(t *testing.T) {
	built := controlBuild(t, "<textarea>two  spaces\nand a break</textarea>")
	box := boxFor(built.Root, "textarea")
	if box == nil {
		t.Fatal("no textarea box")
	}
	if got, want := textIn(box), "two  spaces\nand a break"; got != want {
		t.Errorf("the textarea holds %q, want %q", got, want)
	}
	// And a <div> beside it does not, which is what makes this a statement about
	// the user-agent stylesheet rather than about white-space processing.
	built = controlBuild(t, "<div>two  spaces\nand a break</div>")
	if got := textIn(boxFor(built.Root, "div")); got != "two spaces and a break" {
		t.Errorf("a div collapsed to %q", got)
	}
}

// TestControlLabelGoesThroughTheTextPath pins that a synthesised label is text
// like any other: it inherits the white-space and text-transform rules rather
// than getting a path of its own. A second path would be a second set of
// answers, and the second one is always the one missing a rule.
func TestControlLabelGoesThroughTheTextPath(t *testing.T) {
	built := controlBuild(t, `<input value="one  two">`,
		`input { text-transform: uppercase }`)
	if got, want := textIn(boxFor(built.Root, "input")), "ONE TWO"; got != want {
		t.Errorf("the label is %q, want %q — white space and case are the "+
			"ordinary rules", got, want)
	}
}

// layoutWithFonts lays a document out with real faces, which the intrinsic
// widths above need: a "ch" is a measurement and there is nothing to measure
// without one.
func layoutWithFonts(t *testing.T, set FontSet, htmlSrc, cssSrc string) *Fragment {
	t.Helper()
	built := Build(Input{HTML: htmlSrc, CSS: []Stylesheet{{Source: cssSrc}}})
	if built.Root == nil {
		t.Fatalf("the document produced no boxes")
	}
	rec := NewRecorder(nil)
	w, _ := style.FromPx(600)
	h, _ := style.FromPx(10000)
	frag := Layout(built.Root, Size{W: w, H: h}, set, rec)
	if frag == nil {
		t.Fatal("layout produced no fragment")
	}
	return frag
}

// zeroAdvanceOf measures the advance of "0" in a family at a size, which is what
// "ch" means and what every intrinsic width above is stated in.
//
// It is measured through the engine — an inline-block shrinks to fit exactly one
// character — rather than through the font layer, so that the number carries the
// same rounding to the layout unit that the control's own width will. A
// separately computed expectation would differ from it by a 64th and the test
// would fail on arithmetic rather than on the rule.
func zeroAdvanceOf(t *testing.T, set FontSet, family string, px float64) style.Unit {
	t.Helper()
	root := layoutWithFonts(t, set, `<div id=m>0</div>`,
		`html, body { margin: 0; padding: 0 }
		 #m { display: inline-block; font-family: `+family+
			`; font-size: `+strconv.FormatFloat(px, 'f', -1, 64)+`px;
		      margin: 0; padding: 0; border: none }`)
	w := find(t, root, "m").ContentRect().W
	if w <= 0 {
		t.Fatalf("no face for %q, so a ch cannot be measured", family)
	}
	return w
}
