// Command genjoining generates the Arabic joining types from Unicode's own
// ArabicShaping.txt.
//
// Joining type is what decides the shape a letter takes from its neighbours,
// and it is a property of the character rather than of any font — so it is
// Unicode's to state and not something to infer. Characters the file does not
// list take their type from their category: a non-spacing mark is transparent,
// so that a vowel sign written between two letters does not break their join,
// and everything else is non-joining.
//
//	go run ./cmd/genjoining <ArabicShaping.txt> > fonts/joining.go
package main

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: genjoining <ArabicShaping.txt>")
		os.Exit(2)
	}
	f, err := os.Open(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	types := map[rune]string{}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		fields := strings.Split(line, ";")
		if len(fields) < 3 {
			continue
		}
		cp, err := strconv.ParseUint(strings.TrimSpace(fields[0]), 16, 32)
		if err != nil {
			continue
		}
		t := strings.TrimSpace(fields[2])
		switch t {
		case "R", "L", "D", "C", "T", "U":
			types[rune(cp)] = t
		}
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	// Collapse to ranges: the types run in long blocks, and a range table is a
	// few hundred entries where a per-character map would be thousands.
	cps := make([]rune, 0, len(types))
	for r := range types {
		cps = append(cps, r)
	}
	sort.Slice(cps, func(i, j int) bool { return cps[i] < cps[j] })

	type rng struct {
		lo, hi rune
		t      string
	}
	var ranges []rng
	for _, r := range cps {
		t := types[r]
		if n := len(ranges); n > 0 && ranges[n-1].t == t && ranges[n-1].hi+1 == r {
			ranges[n-1].hi = r
			continue
		}
		ranges = append(ranges, rng{r, r, t})
	}

	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()
	fmt.Fprintf(w, `// Code generated by cmd/genjoining from Unicode's ArabicShaping.txt. DO NOT EDIT.

package fonts

// Joining types, from Unicode.
//
// A cursive script writes a letter differently depending on what it joins to:
// alone, joined on the right, on the left, or on both. Which of those a letter
// can do is its joining type, and it is a property of the character — Unicode's
// to state — rather than of the font, which only supplies the four shapes.
//
// %d ranges cover every character the file gives a type for. Anything else is
// non-joining, except a non-spacing mark, which is transparent: a vowel sign
// written between two letters must not break their join, and treating it as an
// ordinary character would.

type joiningRange struct {
	lo, hi rune
	t      joiningType
}

var joiningRanges = [...]joiningRange{
`, len(ranges))
	for _, r := range ranges {
		fmt.Fprintf(w, "\t{0x%04X, 0x%04X, join%s},\n", r.lo, r.hi, r.t)
	}
	fmt.Fprintln(w, "}")
}
