// Command genmatra generates the split vowel signs of the Indic scripts from
// Unicode's own canonical decompositions.
//
// A *split* vowel sign is one written as a single character and drawn as two or
// three marks, on different sides of the letter. Tamil's o-sign is written
// U+0BCA and drawn as a mark before the letter and another after it; Kannada's
// oo-sign is three marks. The reordering cannot place such a sign at all while
// it is one character — its parts do not go to the same place — so the model's
// second step is to take it apart, and the parts are then placed like any other
// signs.
//
// Which characters those are is Unicode's to say and is not guessed here: they
// are exactly the characters of the Indic blocks whose canonical decomposition
// is a sequence of combining marks. A decomposition into a *letter* and a mark
// is a different thing — a letter that happens to be written with a dot, like
// Devanagari's QA — and taking one apart would replace a letter with something
// else.
//
//	go run ./cmd/genmatra <UnicodeData.txt> > fonts/indicmatra.go
//
// The decomposition is applied to itself until it stops changing, because
// Unicode's are one step at a time and one of these needs two: Kannada's
// U+0CCB decomposes to U+0CCA and a length mark, and U+0CCA decomposes again.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
	"strings"
)

// maxMatraParts is how many marks one sign may be drawn as. Unicode's longest
// is three; a longer one is a file this generator does not understand.
const maxMatraParts = 3

// indicBlocks are the ranges whose signs this covers: the nine scripts that
// share the Indic shaping model. Another script's split signs are not wanted
// here — they are shaped by a different model, or not at all.
var indicBlocks = [][2]rune{
	{0x0900, 0x097F}, // Devanagari
	{0x0980, 0x09FF}, // Bengali
	{0x0A00, 0x0A7F}, // Gurmukhi
	{0x0A80, 0x0AFF}, // Gujarati
	{0x0B00, 0x0B7F}, // Oriya
	{0x0B80, 0x0BFF}, // Tamil
	{0x0C00, 0x0C7F}, // Telugu
	{0x0C80, 0x0CFF}, // Kannada
	{0x0D00, 0x0D7F}, // Malayalam
}

type entry struct {
	r     rune
	parts []rune
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: genmatra <UnicodeData.txt>")
		os.Exit(2)
	}
	decomp, mark := read(os.Args[1])

	var out []entry
	for r, d := range decomp {
		if !inIndicBlock(r) {
			continue
		}
		full, ok := expand(r, decomp, mark)
		if !ok || len(full) < 2 {
			continue
		}
		if len(full) > maxMatraParts {
			fmt.Fprintf(os.Stderr, "genmatra: U+%04X is drawn as %d marks, which the table cannot hold\n", r, len(full))
			os.Exit(1)
		}
		_ = d
		out = append(out, entry{r: r, parts: full})
	}
	if len(out) == 0 {
		fmt.Fprintln(os.Stderr, "genmatra: the file names no split signs, which cannot be right")
		os.Exit(1)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].r < out[j].r })

	var w bytes.Buffer
	fmt.Fprintf(&w, `// Code generated by cmd/genmatra from UnicodeData.txt. DO NOT EDIT.

package fonts

// The vowel signs written as one character and drawn as two or three marks.
//
// A split sign cannot be placed while it is one character: its parts go to
// different places, one before the letter and one after. So the reordering
// takes it apart first, and then places the parts as it places any other sign.
// That is the shaping model's own second step, and these %d characters are what
// it applies to.
//
// They are exactly the characters of the nine Indic blocks whose canonical
// decomposition is a sequence of combining marks. A character that decomposes
// into a *letter* and a mark is a letter written with a dot, not a split sign,
// and is left alone.
//
// The entries are sorted, so a lookup can binary-search.

// indicSplitMatra is one sign and the marks it is drawn as.
type indicSplitMatra struct {
	r     rune
	parts [%d]rune // a two-part sign has a zero third
}

var indicSplitMatras = [...]indicSplitMatra{
`, len(out), maxMatraParts)
	for _, e := range out {
		var parts [maxMatraParts]string
		for i := range parts {
			parts[i] = "0"
			if i < len(e.parts) {
				parts[i] = fmt.Sprintf("0x%04X", e.parts[i])
			}
		}
		fmt.Fprintf(&w, "\t{0x%04X, [%d]rune{%s}},\n", e.r, maxMatraParts, strings.Join(parts[:], ", "))
	}
	fmt.Fprintln(&w, "}")

	src, err := format.Source(w.Bytes())
	if err != nil {
		fmt.Fprintln(os.Stderr, "genmatra:", err)
		os.Exit(1)
	}
	if _, err := os.Stdout.Write(src); err != nil {
		fmt.Fprintln(os.Stderr, "genmatra:", err)
		os.Exit(1)
	}
}

func inIndicBlock(r rune) bool {
	for _, b := range indicBlocks {
		if r >= b[0] && r <= b[1] {
			return true
		}
	}
	return false
}

// expand applies the decompositions until they stop changing, and reports
// whether every part is a combining mark. Unicode states them one step at a
// time and one Kannada sign needs two.
func expand(r rune, decomp map[rune][]rune, mark map[rune]bool) ([]rune, bool) {
	parts := []rune{r}
	// The bound is the depth of the deepest chain Unicode states plus room to
	// notice one that is deeper, rather than trusting the data to terminate.
	for round := 0; round < 8; round++ {
		var next []rune
		changed := false
		for _, p := range parts {
			if d, ok := decomp[p]; ok && len(d) > 1 {
				next = append(next, d...)
				changed = true
				continue
			}
			next = append(next, p)
		}
		parts = next
		if !changed {
			break
		}
	}
	for _, p := range parts {
		if !mark[p] {
			return nil, false
		}
	}
	return parts, true
}

// read parses UnicodeData.txt for the two things this needs: each character's
// canonical decomposition, and whether it is a combining mark.
func read(path string) (decomp map[rune][]rune, mark map[rune]bool) {
	f, err := os.Open(path)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	decomp = map[rune][]rune{}
	mark = map[rune]bool{}
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<16), 1<<16)
	for sc.Scan() {
		fields := strings.Split(sc.Text(), ";")
		if len(fields) < 6 {
			continue
		}
		v, err := strconv.ParseUint(fields[0], 16, 32)
		if err != nil {
			continue
		}
		r := rune(v)
		switch fields[2] {
		case "Mn", "Mc", "Me":
			mark[r] = true
		}
		d := strings.TrimSpace(fields[5])
		// A decomposition beginning with a tag in angle brackets is a
		// compatibility one, which says how a character may be *approximated*
		// rather than what it is written as. Only the canonical ones are wanted.
		if d == "" || strings.HasPrefix(d, "<") {
			continue
		}
		var parts []rune
		for _, s := range strings.Fields(d) {
			c, err := strconv.ParseUint(s, 16, 32)
			if err != nil {
				parts = nil
				break
			}
			parts = append(parts, rune(c))
		}
		if len(parts) > 0 {
			decomp[r] = parts
		}
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	return decomp, mark
}
