package pdfa

import (
	_ "embed"
	"fmt"
	"strconv"

	lcms2 "github.com/mgilbir/golittlecms"
	"github.com/mgilbir/pdf0/internal/core"
	"github.com/mgilbir/pdf0/internal/xmp"
	"github.com/mgilbir/pdf0/object"
)

// This file builds conforming PDF/A documents rather than checking them: the
// minimal five-object skeleton (catalog, page tree, XMP metadata stream,
// output intent, ICC profile) that satisfies the ISO 19005 identification and
// output-intent requirements at every level, the pdfaid identification XMP
// packet (metadata clause 6.7 in ISO 19005-1, 6.6.2 in -2/-3), and the PDF
// version each part is defined against (1.4 for -1, 1.7 for -2/-3, 2.0 for -4).
//
// The sRGB destination profile is a genuine ICC profile generated by
// golittlecms, not a hand-assembled stub, and its version is chosen by level:
// PDF/A-1 targets PDF 1.4, which admits only ICC v2, so it gets v2.1 while the
// later parts get v4. Anything produced here must pass pdf0's own validator —
// the round trip through ValidatePDFA is what keeps the two sides honest.

// Skeleton returns the minimal five-object graph a conforming PDF/A file needs
// — catalog, page tree, XMP metadata, output intent, ICC profile — with the
// trailer and the header version that part is defined against.
//
// It returns the graph rather than a Document so that both sides can use it:
// NewPDFADocumentWithInfo wraps it into one, and this package's own tests wrap
// it into a view without needing the document type at all.
// It is Skeleton! with a zero OutputIntentSpec: pdf0's own embedded sRGB
// profile, described as sRGB.
func Skeleton(level Level, title, author string) (map[int]*object.IndirectObject, object.Dictionary, string, error) {
	return SkeletonWith(SkeletonOptions{Level: level, Title: title, Author: author})
}

// SkeletonOptions is what a generated skeleton is made of.
type SkeletonOptions struct {
	Level        Level
	Title        string
	Author       string
	OutputIntent OutputIntentSpec

	// FileID is the document's /ID, both halves. Empty means a fresh random
	// one, which is what a document wants: the identifier exists to tell this
	// file from every other.
	//
	// Supply one when the output has to be reproducible — the same inputs
	// giving the same bytes, so a build can be compared, cached or signed for.
	// It is the last thing in a generated document that varies between runs;
	// with it set and an ICCProfile supplied, two builds are byte-identical.
	// A digest of the content is the usual choice.
	//
	// Sixteen bytes is conventional (ISO 32000-2 14.4) and nothing enforces it.
	// The bytes are copied, so the caller may reuse the slice.
	FileID []byte
}

// SkeletonWith is Skeleton with the output intent under the caller's control:
// their profile, their output-condition identifier, and no claim by pdf0 about
// either. See OutputIntentSpec.
//
// The error is real here, which is the answer to why Skeleton has one. A
// supplied profile can be too short to be a profile, can disagree with its own
// declared length, can be in a colour space a PDF/A output intent may not use,
// or can be ICC v4 at a level based on PDF 1.4 — and each of those is a
// document that should not be built rather than one built wrongly.
func SkeletonWith(opts SkeletonOptions) (map[int]*object.IndirectObject, object.Dictionary, string, error) {
	level, title, author := opts.Level, opts.Title, opts.Author
	if !level.Valid() {
		// LevelDeclared included: there is no document yet to take a
		// declaration from, and a level that names no profile names nothing
		// to build.
		return nil, object.Dictionary{}, "", fmt.Errorf("pdfa: %s is not a level a document can be built at", level)
	}
	iccData, iccN, intentID, intentRegistry, intentInfo, err := opts.OutputIntent.resolve(level)
	if err != nil {
		return nil, object.Dictionary{}, "", err
	}
	version := pdfaVersion(level)

	// The file identifier. A caller who supplies one gets a document whose
	// bytes depend on nothing but its content; otherwise it is random, for the
	// reasons on core.RandomFileID.
	fileID := core.RandomFileID()
	if len(opts.FileID) > 0 {
		fileID = object.String{Value: append([]byte(nil), opts.FileID...), IsHex: true}
	}

	// Object 1: Catalog
	catalog := &object.Dictionary{}
	catalog.Set("Type", object.Name("Catalog"))
	catalog.Set("Pages", object.IndirectRef{Number: 2})
	catalog.Set("Metadata", object.IndirectRef{Number: 3})
	catalog.Set("OutputIntents", object.Array{object.IndirectRef{Number: 4}})
	if level.IsA() {
		// A Level A file is a Tagged PDF with a logical structure tree. The empty
		// page tree carries no content, so a minimal marked, empty structure tree
		// satisfies the structural requirement (audit C19).
		markInfo := &object.Dictionary{}
		markInfo.Set("Marked", object.Boolean(true))
		catalog.Set("MarkInfo", markInfo)
		structTreeRoot := &object.Dictionary{}
		structTreeRoot.Set("Type", object.Name("StructTreeRoot"))
		catalog.Set("StructTreeRoot", structTreeRoot)
	}
	if level.variant() == "F" {
		// A PDF/A-4f file shall contain an /EmbeddedFiles key in the catalog's
		// name dictionary (6.9). The skeleton has nothing to attach yet, so it
		// gets the empty name tree — the same answer Level A gets above, for
		// the same reason: the structure the level requires, holding the
		// nothing the skeleton has. A caller attaches to it; inventing a file
		// to put in it would be inventing content.
		embedded := &object.Dictionary{}
		embedded.Set("Names", object.Array{})
		names := &object.Dictionary{}
		names.Set("EmbeddedFiles", embedded)
		catalog.Set("Names", names)
	}

	// Object 2: Pages (empty page tree)
	pages := &object.Dictionary{}
	pages.Set("Type", object.Name("Pages"))
	pages.Set("Kids", object.Array{})
	pages.Set("Count", object.Integer(0))

	// Object 3: Metadata stream (XMP, unfiltered)
	xmpData, err := GenerateXMPMetadata(level, title, author)
	if err != nil {
		return nil, object.Dictionary{}, "", err
	}
	metaStream := &object.Stream{
		Dict: object.Dictionary{},
		Data: xmpData,
	}
	metaStream.Dict.Set("Type", object.Name("Metadata"))
	metaStream.Dict.Set("Subtype", object.Name("XML"))
	metaStream.Dict.Set("Length", object.Integer(len(xmpData)))

	// Object 4: OutputIntent dictionary
	outputIntent := &object.Dictionary{}
	outputIntent.Set("Type", object.Name("OutputIntent"))
	outputIntent.Set("S", object.Name("GTS_PDFA1"))
	outputIntent.Set("OutputConditionIdentifier", object.String{Value: []byte(intentID)})
	outputIntent.Set("RegistryName", object.String{Value: []byte(intentRegistry)})
	outputIntent.Set("Info", object.String{Value: []byte(intentInfo)})
	outputIntent.Set("DestOutputProfile", object.IndirectRef{Number: 5})

	// Object 5: ICC profile stream. /N is the profile's own component count,
	// read from its header rather than assumed: a caller's CMYK press profile
	// is four, and a document claiming three would misdescribe it.
	iccStream := &object.Stream{
		Dict: object.Dictionary{},
		Data: iccData,
	}
	iccStream.Dict.Set("N", object.Integer(iccN))
	iccStream.Dict.Set("Length", object.Integer(len(iccData)))

	return map[int]*object.IndirectObject{
			1: {Number: 1, Generation: 0, Value: catalog},
			2: {Number: 2, Generation: 0, Value: pages},
			3: {Number: 3, Generation: 0, Value: metaStream},
			4: {Number: 4, Generation: 0, Value: outputIntent},
			5: {Number: 5, Generation: 0, Value: iccStream},
		}, *object.NewDictionary(
			object.Entry{Key: "Root", Value: object.IndirectRef{Number: 1}},
			object.Entry{Key: "ID", Value: object.Array{fileID, fileID}},
		), version, nil
}

func pdfaVersion(level Level) string {
	switch level.Part() {
	case 1:
		return "1.4"
	case 2, 3:
		return "1.7"
	default:
		return "2.0"
	}
}

// GenerateXMPMetadata creates the XMP metadata packet for the given PDF/A
// level: the pdfaid identification, xmp:CreatorTool, and the title and author
// when given.
//
// It is built through the XMP model, which escapes every value and refuses one
// that cannot be XML at all — invalid UTF-8, a C0 control, U+FFFE — with an
// error wrapping pdf0.ErrInvalidMetadataText (audit C72). Such a title used to be passed
// through (or its control characters silently dropped), which produced a packet
// that was not well-formed and a document that failed its own level.
func GenerateXMPMetadata(level Level, title, author string) ([]byte, error) {
	p := xmp.New()
	if err := setPDFAIdentification(p, level); err != nil {
		return nil, err
	}
	if title != "" {
		// dc:title is a language alternative; x-default is the one a reader
		// shows when no language matches.
		if err := p.SetAltText(xmp.NSDC, "dc", "title", "x-default", title); err != nil {
			return nil, fmt.Errorf("pdfa: title: %w", err)
		}
	}
	if author != "" {
		// dc:creator is an ordered sequence of authors.
		if err := p.SetSeq(xmp.NSDC, "dc", "creator", []string{author}); err != nil {
			return nil, fmt.Errorf("pdfa: author: %w", err)
		}
	}
	if err := p.SetText(xmp.NSXMP, "xmp", "CreatorTool", "pdf0"); err != nil {
		return nil, err
	}
	return p.Bytes()
}

// setPDFAIdentification writes the pdfaid identification for level into a
// packet: part, the conformance letter where the level has one, and the
// revision PDF/A-4 requires. A conformance letter already in the packet is
// removed when the level has none (plain PDF/A-4).
func setPDFAIdentification(p *xmp.Packet, level Level) error {
	if !level.Valid() {
		return fmt.Errorf("pdfa: %s names no level to identify a document as", level)
	}
	if err := p.SetText(xmp.NSPDFAID, pdfaIDPrefix, "part", strconv.Itoa(level.Part())); err != nil {
		return err
	}
	if c := level.Conformance(); c != "" {
		if err := p.SetText(xmp.NSPDFAID, pdfaIDPrefix, "conformance", c); err != nil {
			return err
		}
	} else {
		p.Remove(xmp.NSPDFAID, "conformance")
	}
	if rev := level.revision(); rev != "" {
		return p.SetText(xmp.NSPDFAID, pdfaIDPrefix, "rev", rev)
	}
	p.Remove(xmp.NSPDFAID, "rev")
	return nil
}

// DefaultSRGBProfile returns a real sRGB ICC profile (ICC v2.1, valid at every
// PDF/A level) generated by golittlecms, a pure-Go Little CMS port. It is
// exported for callers that assemble their own OutputIntent; NewPDFADocument
// uses sRGBProfile to select a level-appropriate profile version.
//
// The copy is deliberate: the profile is embedded, so the bytes behind it are
// shared by every caller in the process and a caller that wrote to them would
// change what every later document gets. The error is nil for the same reason
// Skeleton's is.
func DefaultSRGBProfile() ([]byte, error) {
	return copyProfile(sRGBProfile(PDFA1b)), nil
}

//go:embed icc/srgb-v2_1.icc
var srgbV21 []byte

//go:embed icc/srgb-v4_3.icc
var srgbV43 []byte

// sRGBProfile is the sRGB ICC profile for the given PDF/A level. PDF/A-1
// targets PDF 1.4, which permits only ICC v2 profiles, so it receives an ICC
// v2.1 profile; PDF/A-2/3/4 target PDF 1.7/2.0 and receive the compact ICC v4
// profile. Both are genuine profiles emitted by — and re-readable through — a
// real colour-management engine.
//
// They are embedded rather than built per document. golittlecms builds them
// from a built-in sRGB definition and serialises to memory, so the bytes are a
// deterministic function of fixed constants: the same input every time, and
// measurably the same output. Building them at run time therefore added a
// failure that could not happen to every document created, and the code stood
// a panic in its place. Embedding removes the operation, so there is nothing
// left to fail and nothing to panic about.
//
// internal/cmd/genicc writes them, and
// TestTheEmbeddedProfilesAreWhatTheEngineBuilds rebuilds both through
// golittlecms and compares, so they cannot drift from what the engine would
// produce.
//
// The returned slice is the embedded one. Callers put it in a stream and do
// not modify it; copyProfile is there for any that would.
func sRGBProfile(level Level) []byte {
	if level.Part() == 1 {
		return srgbV21
	}
	return srgbV43
}

// copyProfile returns a copy, for a caller that hands the bytes somewhere that
// might write to them. An embedded slice is shared across every caller in the
// process, so a mutation would be seen by all of them.
func copyProfile(p []byte) []byte {
	out := make([]byte, len(p))
	copy(out, p)
	return out
}

// buildSRGBProfile generates an sRGB ICC profile serialized at the requested ICC
// version (e.g. 2.1 or 4.3) using golittlecms.
func buildSRGBProfile(version float64) ([]byte, error) {
	p, err := lcms2.Create_sRGBProfile()
	if err != nil {
		return nil, err
	}
	p.SetProfileVersion(version)
	return p.SaveProfileToMem()
}
