// Command genglyphlist generates the glyph-name to Unicode mapping that the
// standard Latin encodings need, from Adobe's own Glyph List.
//
// Only the names the standard encodings actually use are emitted. The full AGL
// is four thousand entries and a font naming a glyph outside those encodings
// says what it means with a uniXXXX name, which GlyphNameToRune already
// resolves without a table.
//
//	go run ./cmd/genglyphlist <glyphlist.txt> > internal/font/glyphnames.go
package main

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/mgilbir/pdf0/internal/font"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: genglyphlist <glyphlist.txt>")
		os.Exit(2)
	}
	agl, err := parse(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	// The names the three standard encodings use, which is the set a simple
	// font can name without saying uniXXXX.
	wanted := map[string]bool{}
	for _, table := range []map[byte]string{
		font.StandardEncodingNames, font.WinAnsiEncodingNames, font.MacRomanEncodingNames,
	} {
		for _, name := range table {
			wanted[name] = true
		}
	}

	out := map[string]rune{}
	var missing []string
	for name := range wanted {
		r, ok := agl[name]
		if !ok {
			missing = append(missing, name)
			continue
		}
		out[name] = r
	}
	if len(missing) > 0 {
		sort.Strings(missing)
		fmt.Fprintf(os.Stderr, "not in the AGL: %v\n", missing)
	}

	names := make([]string, 0, len(out))
	for n := range out {
		names = append(names, n)
	}
	sort.Strings(names)

	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()
	fmt.Fprint(w, `// Code generated by cmd/genglyphlist from Adobe's Glyph List. DO NOT EDIT.

package font

// glyphNameRunes maps the glyph names the standard Latin encodings use to the
// characters they stand for.
//
// It exists because the encodings are not identity where it matters most. A
// name is resolvable by inspection for ASCII and for Latin-1 above 0xA0, and
// the codes between — 0x80 to 0x9F, which is where WinAnsiEncoding puts the
// curly quotes, the dashes, the bullet, the ellipsis and the euro — are named
// glyphs whose values nothing about the code implies. Without this a document
// setting a quotation mark in a simple font has a character no reader of this
// module can name.
var glyphNameRunes = map[string]rune{
`)
	for _, n := range names {
		fmt.Fprintf(w, "\t%q: %d, // U+%04X\n", n, out[n], out[n])
	}
	fmt.Fprintln(w, "}")
}

func parse(path string) (map[string]rune, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	out := map[string]rune{}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if strings.HasPrefix(line, "#") {
			continue
		}
		name, codes, ok := strings.Cut(line, ";")
		if !ok {
			continue
		}
		// A name may map to a sequence; only the single-character ones are a
		// character this can stand for.
		fields := strings.Fields(codes)
		if len(fields) != 1 {
			continue
		}
		v, err := strconv.ParseUint(fields[0], 16, 32)
		if err != nil {
			continue
		}
		out[name] = rune(v)
	}
	return out, sc.Err()
}
