// Command genignorable generates the Default_Ignorable_Code_Point set from
// Unicode's own DerivedCoreProperties.txt.
//
// A default-ignorable character is one a renderer should show nothing for when
// it cannot do better — the soft hyphen, the bidirectional controls, the
// variation selectors, the word joiner. They are instructions, not letters, and
// a font that maps one to a visible glyph is not saying it should be drawn: it
// is saying what it would look like if it were, which is a question nobody
// asked.
//
// The property is Unicode's to state, so it is read rather than reasoned about.
// Which of these characters this package *acts* on is a separate question with a
// separate answer — see fonts/ignorable.go, which keeps two of them because they
// change what the font is asked for, and four more because a renderer that hid
// them would be wrong about Korean.
//
//	go run ./cmd/genignorable <DerivedCoreProperties.txt> > fonts/ignorabletable.go
package main

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

type span struct{ lo, hi rune }

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: genignorable <DerivedCoreProperties.txt>")
		os.Exit(2)
	}
	f, err := os.Open(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	version := "unknown"
	var spans []span
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		// The file names its own version on the first line.
		if strings.HasPrefix(line, "# DerivedCoreProperties-") {
			version = strings.TrimSuffix(strings.TrimPrefix(line, "# DerivedCoreProperties-"), ".txt")
		}
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		fields := strings.Split(line, ";")
		if len(fields) < 2 || strings.TrimSpace(fields[1]) != "Default_Ignorable_Code_Point" {
			continue
		}
		lo, hi, ok := parseRange(strings.TrimSpace(fields[0]))
		if !ok {
			continue
		}
		spans = append(spans, span{lo, hi})
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if len(spans) == 0 {
		fmt.Fprintln(os.Stderr, "no Default_Ignorable_Code_Point lines found")
		os.Exit(1)
	}

	sort.Slice(spans, func(i, j int) bool { return spans[i].lo < spans[j].lo })
	// Adjacent runs are stated separately in the file — by category, mostly —
	// and are one range as far as a lookup is concerned.
	merged := []span{spans[0]}
	for _, s := range spans[1:] {
		last := &merged[len(merged)-1]
		if s.lo <= last.hi+1 {
			if s.hi > last.hi {
				last.hi = s.hi
			}
			continue
		}
		merged = append(merged, s)
	}

	var w strings.Builder
	fmt.Fprintf(&w, `// Code generated by cmd/genignorable from Unicode's DerivedCoreProperties.txt.
// DO NOT EDIT.

package fonts

// Default_Ignorable_Code_Point. Unicode %s.
//
// %d ranges. A character in one of them is an instruction rather than a letter,
// and a renderer that can do nothing better than show a glyph for it should show
// nothing at all. Which of them this package acts on is decided in
// ignorable.go, not here: this table is Unicode's statement, not a policy.
var defaultIgnorableRanges = [...]struct{ lo, hi rune }{
`, version, len(merged))
	for _, s := range merged {
		fmt.Fprintf(&w, "\t{0x%04X, 0x%04X},\n", s.lo, s.hi)
	}
	fmt.Fprintln(&w, "}")
	fmt.Print(w.String())
}

func parseRange(s string) (rune, rune, bool) {
	lo, hi, found := strings.Cut(s, "..")
	a, err := strconv.ParseUint(lo, 16, 32)
	if err != nil {
		return 0, 0, false
	}
	if !found {
		return rune(a), rune(a), true
	}
	b, err := strconv.ParseUint(hi, 16, 32)
	if err != nil {
		return 0, 0, false
	}
	return rune(a), rune(b), true
}
