// Command genuse generates the Universal Shaping Engine's categories from
// Unicode's own property files.
//
// The engine covers several dozen scripts that behave like the Indic ones —
// Javanese, Balinese, Buginese, Chakma, Tai Tham, Tibetan and more — none of
// which has a shaper of its own anywhere. What they share is a syllable that is
// not stored in the order it is drawn, and the engine is the one model that
// handles all of them: the categories below are what tell it what each character
// is, and use_positions what side of the letter each mark sits.
//
// # It is derived, not stated
//
// Unicode publishes no "USE category" property. The engine's specification
// derives it from five properties Unicode does publish — Indic_Syllabic_Category,
// Indic_Positional_Category, General_Category, Default_Ignorable_Code_Point and
// the Arabic Joining_Type — and the derivation below is that specification,
// written out. It follows HarfBuzz's gen-use-table.py, which is the reference
// implementation of the same derivation and where its handful of corrections to
// the published rules are recorded; those corrections are marked where they
// appear.
//
// Deriving rather than tabulating is what keeps this honest: every answer traces
// to a property Unicode states, so a new Unicode release is a re-run rather than
// a re-reading.
//
//	go run ./cmd/genuse <IndicSyllabicCategory.txt> <IndicPositionalCategory.txt> \
//		<UnicodeData.txt> <DerivedCoreProperties.txt> <ArabicShaping.txt> > fonts/usetable.go
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
	"strings"
)

func main() {
	if len(os.Args) != 8 {
		fmt.Fprintln(os.Stderr, "usage: genuse <IndicSyllabicCategory.txt> "+
			"<IndicPositionalCategory.txt> <UnicodeData.txt> "+
			"<DerivedCoreProperties.txt> <ArabicShaping.txt> "+
			"<IndicSyllabicCategory-Additional.txt> <IndicPositionalCategory-Additional.txt>")
		os.Exit(2)
	}
	// Unicode's values, then the engine's corrections to them. The corrections
	// are not derivable from anything — see testdata/ms-use/NOTICE.md — and
	// there are characters whose Unicode value is right for Unicode and wrong
	// for laying out a syllable, so they are read last and win.
	syllabic := override(readRanged(os.Args[1]), readRanged(os.Args[6]))
	positional := override(readRanged(os.Args[2]), readRanged(os.Args[7]))
	general, version := readUnicodeData(os.Args[3])
	ignorable := readProperty(os.Args[4], "Default_Ignorable_Code_Point")
	joining := readJoining(os.Args[5])

	// Every character any of the inputs says something about, plus every
	// unassigned one the derivation asks about, is answered by the same code —
	// so the walk is over the whole code space and the ranges are merged after.
	type answer struct{ cat, pos string }
	answers := map[rune]answer{}
	for r := rune(0); r <= 0x10FFFF; r++ {
		c := character{
			r:    r,
			isc:  valueAt(syllabic, r, "Other"),
			ipc:  valueAt(positional, r, "NA"),
			gc:   general[r],
			di:   ignorable[r],
			join: joining[r],
		}
		if c.gc == "" {
			c.gc = "Cn" // unassigned
		}
		cat := categoryOf(c)
		if cat == "O" {
			continue // the default, and by far the commonest
		}
		answers[r] = answer{cat, positionOf(cat, c.ipc)}
	}

	type span struct {
		lo, hi   rune
		cat, pos string
	}
	keys := make([]rune, 0, len(answers))
	for r := range answers {
		keys = append(keys, r)
	}
	sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
	var spans []span
	for _, r := range keys {
		a := answers[r]
		if n := len(spans); n > 0 && spans[n-1].hi == r-1 &&
			spans[n-1].cat == a.cat && spans[n-1].pos == a.pos {
			spans[n-1].hi = r
			continue
		}
		spans = append(spans, span{r, r, a.cat, a.pos})
	}

	var w bytes.Buffer
	fmt.Fprintf(&w, `// Code generated by cmd/genuse from Unicode's IndicSyllabicCategory.txt,
// IndicPositionalCategory.txt, UnicodeData.txt, DerivedCoreProperties.txt and
// ArabicShaping.txt. DO NOT EDIT.

package fonts

// The Universal Shaping Engine's categories. Unicode %s.
//
// %d ranges. A character in none of them is of category useOther, which is the
// zero value and what every character outside these scripts reads as.
//
// Unicode publishes no such property: it is derived from five that Unicode does
// publish, and cmd/genuse is that derivation. See its documentation for why it
// is computed rather than tabulated.
var useRanges = [...]useRange{
`, version, len(spans))
	for _, s := range spans {
		fmt.Fprintf(&w, "\t{0x%04X, 0x%04X, use%s, usePos%s},\n", s.lo, s.hi, s.cat, s.pos)
	}
	fmt.Fprintln(&w, "}")

	out, err := format.Source(w.Bytes())
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	os.Stdout.Write(out)
}

// character is everything the derivation asks about one code point.
type character struct {
	r    rune
	isc  string // Indic_Syllabic_Category
	ipc  string // Indic_Positional_Category
	gc   string // General_Category
	di   bool   // Default_Ignorable_Code_Point
	join string // Arabic Joining_Type
}

// categoryOf is the derivation itself: the first rule that answers wins, and
// they are written in the order the specification resolves them.
//
// The rules are stated as they are published, with the corrections HarfBuzz
// records against them. Those are marked, and each says what it is for.
func categoryOf(c character) string {
	// Corrections to the published data, which HarfBuzz carries and which are
	// about characters Unicode gives a position to and no syllabic category.
	isc := c.isc
	switch {
	case c.r >= 0x1CE2 && c.r <= 0x1CE8:
		isc = "Cantillation_Mark"
	case c.r >= 0x0F18 && c.r <= 0x0F19, c.r >= 0x0F3E && c.r <= 0x0F3F:
		isc = "Vowel_Dependent"
	case c.r == 0x1CED:
		isc = "Tone_Mark"
	}
	c.isc = isc

	switch {
	// The two that are split off from Halant and must be tested before it.
	case c.r == 0x0DCA:
		return "HVM" // halant or vowel modifier
	case c.r == 0x1A60:
		return "Sk" // sakot
	case isc == "Invisible_Stacker":
		return "IS"
	case isc == "Virama":
		return "H"

	case isc == "Non_Joiner":
		return "ZWNJ"
	case isCGJ(c):
		return "CGJ"
	case isWordJoiner(c):
		return "WJ"

	case isc == "Brahmi_Joining_Number":
		return "N"
	case isc == "Number_Joiner":
		return "HN"
	case isc == "Consonant_With_Stacker":
		return "CS"
	case isc == "Consonant_Preceding_Repha", isc == "Consonant_Prefixed":
		return "R"
	case isc == "Reordering_Killer":
		return "RK"
	case isc == "Symbol_Modifier":
		return "SM"
	case isc == "Nukta", isc == "Gemination_Mark", isc == "Consonant_Killer":
		return "CM"
	case isc == "Syllable_Modifier":
		return "FM"
	case isc == "Consonant_Final" && c.gc != "Lo",
		isc == "Consonant_Succeeding_Repha":
		return "F"
	case isc == "Consonant_Medial" && c.gc != "Lo",
		isc == "Consonant_Initial_Postfixed":
		return "M"
	case isc == "Consonant_Subjoined" && c.gc != "Lo":
		return "SUB"

	case isBase(c):
		return "B"
	case isc == "Consonant_Placeholder",
		c.r == 0x2015, c.r == 0x2022,
		c.r >= 0x25FB && c.r <= 0x25FE:
		return "GB"

	case isc == "Pure_Killer",
		c.gc != "Lo" && (isc == "Vowel" || isc == "Vowel_Dependent"):
		return "V"
	case isc == "Tone_Mark", isc == "Cantillation_Mark",
		isc == "Register_Shifter", isc == "Visarga",
		c.gc != "Lo" && isc == "Bindu":
		return "VM"
	}
	return "O"
}

// isBase is the specification's Base rule.
//
// The middle clause is HarfBuzz's, and is the one part of this that is not the
// published rule: a character that joins cursively is a base whatever else it
// is, because a script that joins has letters and the engine must be able to
// find them.
func isBase(c character) bool {
	switch c.isc {
	case "Number", "Consonant", "Consonant_Head_Letter", "Tone_Letter", "Vowel_Independent":
		return true
	}
	switch c.join {
	case "C", "D", "L", "R":
		if c.isc != "Joiner" {
			return true
		}
	}
	if c.gc == "Lo" {
		switch c.isc {
		case "Avagraha", "Bindu", "Consonant_Final", "Consonant_Medial",
			"Consonant_Subjoined", "Vowel", "Vowel_Dependent":
			return true
		}
	}
	return false
}

// isCGJ also covers the variation selectors and the zero width joiner: all
// three are transparent to the syllable and none is drawn.
func isCGJ(c character) bool {
	if c.isc == "Joiner" {
		return true
	}
	return c.di && (c.gc == "Mc" || c.gc == "Me" || c.gc == "Mn")
}

// isWordJoiner also covers the reserved code points, which are treated as
// something that breaks nothing rather than as a letter.
//
// The Hangul fillers are excluded for the reason they are excluded everywhere:
// they are letters, and they occupy width.
func isWordJoiner(c character) bool {
	switch c.r {
	case 0x115F, 0x1160, 0x3164, 0xFFA0, 0x1BCA0, 0x1BCA1, 0x1BCA2, 0x1BCA3:
		return c.gc == "Cn"
	}
	if c.di && c.isc == "Other" && !isCGJ(c) {
		return true
	}
	return c.gc == "Cn"
}

// positionOf maps the Indic position onto the four the engine names, for the
// categories that have one. A category not listed takes no position.
func positionOf(cat, ipc string) string {
	table, ok := map[string]map[string]string{
		"F": {"Top": "Abv", "Bottom": "Blw", "Right": "Pst"},
		"M": {
			"Top": "Abv", "Bottom": "Blw", "Bottom_And_Left": "Blw",
			"Bottom_And_Right": "Blw", "Right": "Pst", "Left": "Pre",
			"Top_And_Bottom_And_Left": "Pre",
		},
		"CM": {"Top": "Abv", "Bottom": "Blw", "Overstruck": "Blw"},
		"V": {
			"Top": "Abv", "Top_And_Bottom": "Abv", "Top_And_Bottom_And_Right": "Abv",
			"Top_And_Right": "Abv", "Bottom": "Blw", "Overstruck": "Blw",
			"Bottom_And_Right": "Blw", "Right": "Pst", "Left": "Pre",
			"Top_And_Left": "Pre", "Top_And_Left_And_Right": "Pre",
			"Left_And_Right": "Pre",
		},
		"VM": {"Top": "Abv", "Bottom": "Blw", "Overstruck": "Blw",
			"Right": "Pst", "Left": "Pre"},
		"SM": {"Top": "Abv", "Bottom": "Blw"},
		"FM": {"Top": "Abv", "Bottom": "Blw", "NA": "Pst"},
	}[cat]
	if !ok {
		return "None"
	}
	if p, ok := table[ipc]; ok {
		return p
	}
	return "None"
}

// --- reading Unicode's files ---

type ranged struct {
	lo, hi rune
	value  string
}

func valueAt(rs []ranged, r rune, dflt string) string {
	i := sort.Search(len(rs), func(i int) bool { return rs[i].hi >= r })
	if i < len(rs) && rs[i].lo <= r {
		return rs[i].value
	}
	return dflt
}

// readRanged reads a file of "range ; value" lines, which is the shape of every
// Unicode property file that states one property.
func readRanged(path string) []ranged {
	var out []ranged
	eachField(path, func(fields []string) {
		if len(fields) < 2 {
			return
		}
		lo, hi, ok := parseRange(fields[0])
		if !ok {
			return
		}
		out = append(out, ranged{lo, hi, fields[1]})
	})
	sort.Slice(out, func(i, j int) bool { return out[i].lo < out[j].lo })
	return out
}

// override lays one set of ranges over another, so that a character the second
// names takes the second's value and every other keeps the first's.
//
// It works on the flattened characters rather than on the ranges because the two
// files divide the code space differently, and merging ranges that overlap
// partially is a great deal of care for a table that is rebuilt in a second.
func override(base, over []ranged) []ranged {
	if len(over) == 0 {
		return base
	}
	out := append([]ranged(nil), base...)
	for _, o := range over {
		out = append(out, o)
	}
	// A later range wins, which sort.SliceStable preserves for equal keys only
	// if the search below prefers the last match — so instead the overrides are
	// applied by rewriting: every base range is split around each override.
	flat := map[rune]string{}
	for _, r := range base {
		for c := r.lo; c <= r.hi; c++ {
			flat[c] = r.value
		}
	}
	for _, r := range over {
		for c := r.lo; c <= r.hi; c++ {
			flat[c] = r.value
		}
	}
	keys := make([]rune, 0, len(flat))
	for c := range flat {
		keys = append(keys, c)
	}
	sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
	out = out[:0]
	for _, c := range keys {
		v := flat[c]
		if n := len(out); n > 0 && out[n-1].hi == c-1 && out[n-1].value == v {
			out[n-1].hi = c
			continue
		}
		out = append(out, ranged{c, c, v})
	}
	return out
}

// readProperty reads the ranges a derived-property file gives one property.
func readProperty(path, want string) map[rune]bool {
	out := map[rune]bool{}
	eachField(path, func(fields []string) {
		if len(fields) < 2 || fields[1] != want {
			return
		}
		lo, hi, ok := parseRange(fields[0])
		if !ok {
			return
		}
		for r := lo; r <= hi; r++ {
			out[r] = true
		}
	})
	return out
}

// readUnicodeData reads the General_Category of every assigned character, and
// the ranges UnicodeData.txt states with a First/Last pair rather than a line
// each.
func readUnicodeData(path string) (map[rune]string, string) {
	out := map[rune]string{}
	f, err := os.Open(path)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()
	var firstOfRange rune = -1
	var firstCategory string
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	for sc.Scan() {
		fields := strings.Split(sc.Text(), ";")
		if len(fields) < 3 {
			continue
		}
		cp, err := strconv.ParseUint(fields[0], 16, 32)
		if err != nil {
			continue
		}
		r, name, gc := rune(cp), fields[1], fields[2]
		switch {
		case strings.HasSuffix(name, ", First>"):
			firstOfRange, firstCategory = r, gc
		case strings.HasSuffix(name, ", Last>") && firstOfRange >= 0:
			for k := firstOfRange; k <= r; k++ {
				out[k] = firstCategory
			}
			firstOfRange = -1
		default:
			out[r] = gc
		}
	}
	// UnicodeData.txt carries no version line, so it is taken from the file
	// that does — the caller passes them from one release.
	return out, unicodeVersion
}

// readJoining reads the Arabic joining type, defaulting as ArabicShaping.txt's
// own header says: a non-spacing mark is transparent and everything else does
// not join.
func readJoining(path string) map[rune]string {
	out := map[rune]string{}
	eachField(path, func(fields []string) {
		if len(fields) < 3 {
			return
		}
		cp, err := strconv.ParseUint(strings.TrimSpace(fields[0]), 16, 32)
		if err != nil {
			return
		}
		out[rune(cp)] = strings.TrimSpace(fields[2])
	})
	return out
}

// unicodeVersion is read from whichever input names it first.
var unicodeVersion = "unknown"

// eachField calls fn with the semicolon-separated fields of every data line,
// comments and blanks skipped, and picks the version out of the header.
func eachField(path string, fn func(fields []string)) {
	f, err := os.Open(path)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	for sc.Scan() {
		line := sc.Text()
		if unicodeVersion == "unknown" {
			if _, v, ok := strings.Cut(line, "-"); ok && strings.HasPrefix(line, "# ") &&
				strings.HasSuffix(v, ".txt") {
				unicodeVersion = strings.TrimSuffix(v, ".txt")
			}
		}
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		if strings.TrimSpace(line) == "" {
			continue
		}
		fields := strings.Split(line, ";")
		for i := range fields {
			fields[i] = strings.TrimSpace(fields[i])
		}
		fn(fields)
	}
}

func parseRange(s string) (rune, rune, bool) {
	lo, hi, found := strings.Cut(s, "..")
	a, err := strconv.ParseUint(lo, 16, 32)
	if err != nil {
		return 0, 0, false
	}
	if !found {
		return rune(a), rune(a), true
	}
	b, err := strconv.ParseUint(hi, 16, 32)
	if err != nil {
		return 0, 0, false
	}
	return rune(a), rune(b), true
}
