// Command genvowel generates the invalid vowel clusters from the script
// development specifications' own list of them.
//
// An independent vowel followed by certain vowel signs spells a sequence that
// looks like a different vowel, and no language writes it. Unicode does not
// forbid it, so a shaper is handed it, and drawing it as though it were meant
// would show the reader a letter nobody wrote. Every shaper instead shows the
// vowel, then a dotted circle, then the sign — which says plainly that the sign
// belongs to nothing.
//
// Which sequences those are is not derivable from any character property. It is
// a list, one per script, published as Indic_Shaping_Invalid_Cluster in the
// Microsoft script development specifications and mirrored in HarfBuzz's source
// tree, which is where this reads it from:
//
//	go run ./cmd/genvowel <IndicShapingInvalidCluster.txt> > fonts/indicvowel.go
//
// The file is small and has not changed since 2019, but it is generated rather
// than transcribed for the same reason the category tables are: a list nobody
// can regenerate is a list nobody can check.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
	"strings"
)

// maxInvalidCluster is how many characters one entry may name. The published
// list holds pairs and one triple; anything longer is a file this generator
// does not understand, and it says so rather than truncating.
const maxInvalidCluster = 3

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: genvowel <IndicShapingInvalidCluster.txt>")
		os.Exit(2)
	}
	dates, clusters := read(os.Args[1])
	if len(clusters) == 0 {
		fmt.Fprintln(os.Stderr, "genvowel: the file names no clusters")
		os.Exit(1)
	}
	sort.Slice(clusters, func(i, j int) bool {
		a, b := clusters[i], clusters[j]
		for k := 0; k < len(a) && k < len(b); k++ {
			if a[k] != b[k] {
				return a[k] < b[k]
			}
		}
		return len(a) < len(b)
	})

	var w bytes.Buffer
	fmt.Fprintf(&w, `// Code generated by cmd/genvowel from IndicShapingInvalidCluster.txt. DO NOT EDIT.

package fonts

// Sequences that spell a vowel nobody writes. %s
//
// An independent vowel followed by one of these vowel signs looks like a
// different vowel, so no language writes the pair — but nothing forbids it, and
// a shaper handed one would otherwise draw it as though it were meant. What
// every shaper draws instead is the vowel, a dotted circle, and then the sign,
// which says plainly that the sign belongs to nothing.
//
// The list is not derivable from any character property: it is published as
// Indic_Shaping_Invalid_Cluster in the script development specifications, and
// these %d entries are it. They are sorted, so a lookup can binary-search.

// indicInvalidClusters are the sequences shown against a dotted circle. Each is
// two or three characters; a two-character entry has a zero third.
var indicInvalidClusters = [...][%d]rune{
`, strings.Join(dates, " "), len(clusters), maxInvalidCluster)
	for _, c := range clusters {
		var parts [maxInvalidCluster]string
		for i := range parts {
			parts[i] = "0"
			if i < len(c) {
				parts[i] = fmt.Sprintf("0x%04X", c[i])
			}
		}
		fmt.Fprintf(&w, "\t{%s},\n", strings.Join(parts[:], ", "))
	}
	fmt.Fprintln(&w, "}")

	src, err := format.Source(w.Bytes())
	if err != nil {
		fmt.Fprintln(os.Stderr, "genvowel:", err)
		os.Exit(1)
	}
	if _, err := os.Stdout.Write(src); err != nil {
		fmt.Fprintln(os.Stderr, "genvowel:", err)
		os.Exit(1)
	}
}

// read parses the published list: the dates its header carries, and one
// whitespace-separated run of code points per line before the semicolon.
func read(path string) (dates []string, clusters [][]rune) {
	f, err := os.Open(path)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if strings.HasPrefix(line, "# Date:") {
			dates = append(dates, strings.TrimSpace(strings.TrimPrefix(line, "# Date:")))
			continue
		}
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		line = strings.TrimSpace(strings.TrimSuffix(strings.TrimSpace(line), ";"))
		if line == "" {
			continue
		}
		var seq []rune
		for _, field := range strings.Fields(line) {
			v, err := strconv.ParseUint(field, 16, 32)
			if err != nil {
				fmt.Fprintf(os.Stderr, "genvowel: %q is not a code point\n", field)
				os.Exit(1)
			}
			seq = append(seq, rune(v))
		}
		if len(seq) < 2 || len(seq) > maxInvalidCluster {
			fmt.Fprintf(os.Stderr, "genvowel: a cluster of %d characters, which the table cannot hold\n", len(seq))
			os.Exit(1)
		}
		clusters = append(clusters, seq)
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	return dates, clusters
}
